Tsc 310 apply column settings from settings file
earthhistoryviz/tsconline pull request #100
Opened 2024-05-10 01:33 UTC by jay-jhk-lee

added the backend for loading settings files. Created a function to recursively go down the info given by the settings file and accessing the respective column info state. Standardized the parameters of the setter functions for columnInfo. Added formatting to the column names when parsing datapack to align with tscreator and the settings file.

2024-05-10 14:30 UTC, paologum requested changes

2024-05-10 18:03 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +  }
it only does it if curcol is undefined from the initial map access, so `Chart Root` and `Chart Title` are already covered.

2024-05-10 21:34 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
one more thing, is there a reason that this is a nested function?

2024-05-10 21:38 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    console.log("Unknown column name " + columnName + " found while loading settings");
this would make more sense like
```
if (curcol === undefined) {
    if (extractColumnType(settings._id) === "RootColumn") {
      curcol = state.settingsTabs.columnHashMap.get("Chart Title in " + columnName);
    } else {
      pushSnackbar("Unknown column name '" + columnName + "' found while loading settings", "warning");
    console.log("Unknown column name " + columnName + " found while loading settings");
    }
  } else  setColumnProperties(curcol, settings);
```

easier to read and less dupe

2024-05-10 21:41 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    console.log("Unknown column name " + columnName + " found while loading settings");
actually wait let me think for a second

2024-05-10 21:50 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    console.log("Unknown column name " + columnName + " found while loading settings");
```
let curcol: ColumnInfo | undefined = state.settingsTabs.columnHashMap.get(columnName) || state.settingsTabs.columnHashMap.get("Chart Title in " + columnName");
if (!curcol) {
  pushSnackbar stuff
} else setColumnProps
if (BlockSeriesMetaColumn) {
  for loop with diff name
} else {
  normal for loop
}

```

2024-05-10 21:51 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
can't this be it's own function outs of this (same comment from before but on your most recent commit)

2024-05-10 21:58 UTC, paologum commented on app/src/state/parse-settings.ts
> +          key = child.getAttribute("function")! as keyof FontsInfo;
you should also check to make sure the key exists on `FontsInfo` as well

2024-05-10 21:59 UTC, paologum commented on app/src/state/parse-settings.ts
> +        fonts[key].inheritable = Boolean(child.getAttribute("inheritable"));
check `child.getAttr` here too, but default this to false if it doesn't find one

2024-05-10 22:00 UTC, paologum commented on app/src/state/parse-settings.ts
> +          fonts[child.getAttribute("function")! as keyof FontsInfo].fontFace =
change to key

2024-05-10 22:05 UTC, paologum commented on app/src/state/parse-settings.ts
> +      }
it would be beneficial for us to split `fontProps[i]` early by ": " and call it like `fontPropKey` then check includes on that for less comparisons. also the nested ifs can just be one `if` statement with `&&`

2024-05-10 22:07 UTC, paologum commented on server/src/parse-datapacks.ts
>      name: trimInvisibleCharacters(currentColumn),
take this out so we don't have unecessary nested functions, also format the column name after the trim happens `name: formatColumnName(trimInvisibleCharacters(currentColumn)`

2024-05-10 22:08 UTC, paologum commented on app/src/state/parse-settings.ts
> +              : "Arial";
idk if you wanna do this in this pr but we should change this to a regex in shared like `EventType` just in case we wanna do more fonts

2024-05-11 18:52 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +  }
yes, but I think that this function is super specific to this use case so for scope I wanted to leave it inside. I'm good with either tho

2024-05-11 18:58 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
it's more so for the fact of readability than scope

2024-05-11 19:00 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
honestly this could benefit into being turned into an action as well, but that's up to you

2024-05-11 19:03 UTC, jay-jhk-lee commented on server/src/parse-datapacks.ts
>      name: trimInvisibleCharacters(currentColumn),
for the first part, same reasoning as before

2024-05-11 19:14 UTC, paologum commented on server/src/parse-datapacks.ts
>      name: trimInvisibleCharacters(currentColumn),
this could be a utility function that's generalized as sanitizing a string and also i looked into simpler ways of executing this command and you can just do

```
 return text
    .trim()
    .trimQuotes()
    .replace(/^"(.*)"$/, '$1')
    .replace(/""/g, '"')
    .replace(/(\d),(\d)/g, '$1.$2');
```

for easier readability

2024-05-15 17:25 UTC, closed without merging