Tsc 275 create encryption UI and route
earthhistoryviz/tsconline pull request #101
Opened 2024-05-10 19:15 UTC by JacquiFreeElectron

Users can encrypt the datapacks they upload. They can download the encrypted version or simply retrieve the original file. The download button will only show for user-uploaded datapacks.

2024-05-11 15:58 UTC, jay-jhk-lee commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
small spelling error

2024-05-11 15:58 UTC, jay-jhk-lee commented on server/src/routes.ts
> +        console.log("file is already encrpted before");
same

2024-05-11 16:00 UTC, jay-jhk-lee commented on server/src/routes.ts
> +  const checkIfAlreadyEncrypted = path.join(encryptedFilepathDir.replaceAll("\\", "/"), filename);
this sounds like a boolean, so I think a better name could be `MaybeEncryptedFilepath`

2024-05-11 18:54 UTC, paologum requested changes

2024-05-11 18:54 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +    }
this can just be `fileBlob = await actions.requestDownload(needEncryption, fileName);

2024-05-11 18:54 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +        </div>
Use react fragment, also use pascal case for the options

2024-05-11 18:54 UTC, paologum commented on server/src/routes.ts
> +};
we shouldn't have a route for getting server datapacks only, that's already a route. the way that this should be done is not with a rest api call. you should use a boolean on the `DatapackParsingPack` that is called `isUserDatapack`

2024-05-11 18:54 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    }
display errors, you shouldn't throw errors on the app side

2024-05-11 18:54 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +  }
no need for a method, it should just be a field on the parsing pack

2024-05-11 18:54 UTC, paologum commented on server/src/index.ts
> +  routes.requestDownload
routes should be nouns and not predicates so this route should be `/downloads/:filename` with a query of `encrypted`
filename is still a param but encrypted should be a query
we use query when it's an optional "param"

then you can default to the original file they uploaded and anyone accessing this doesn't need the overhead of knowing whether they want to encrypt or not

2024-05-11 18:54 UTC, paologum commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
this can throw an error, should check

2024-05-11 18:54 UTC, paologum commented on server/db/TSC.db
should not be committed

2024-05-11 18:54 UTC, paologum commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
use `await access`  (async for everything here, no sync)

2024-05-11 18:54 UTC, paologum commented on server/src/routes.ts
> +        console.log("file is already encrpted before");
you should just remove this `console.log`

2024-05-11 18:54 UTC, paologum commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
no `console.log`

2024-05-11 18:56 UTC, paologum commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
also, if this directory exists, before, that must mean the file has been encrypted before, meaning that you should check that file and send it. if that file isn't encrypted, delete it and remake it

2024-05-11 18:57 UTC, paologum commented on server/src/routes.ts
> +    reply.send(file);
should verify it encrypted properly

2024-05-12 22:57 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
I think line 79 to 82 checked if a file has been encrypted before. 
Also, if I verify each encryption worked properly by checking the header in line 141 to 143, do I need to check again in here?

2024-05-12 23:09 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
Do I need to change `if (fs.existsSync(checkIfAlreadyEncrypted))` too? Cause I don't know how to use access to check if a file exist

2024-05-12 23:30 UTC, paologum commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
this is the case where the user has uploaded an unencrypted file, and has requested an encrypted file a second time, meaning it already exists as an encrypted file and we shouldn't encrypt it again

2024-05-12 23:30 UTC, paologum commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
`await access` checks if a file exists

2024-05-12 23:33 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
yes line 79 to 82 does that. The java program will not be called again

2024-05-12 23:36 UTC, paologum commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
ah ok but it should verify it is encrypted again on those lines

2024-05-12 23:39 UTC, paologum commented on server/src/routes.ts
> +  const checkIfAlreadyEncrypted = path.join(encryptedFilepathDir.replaceAll("\\", "/"), filename);
also is there a reason that `encryptedFilepathDir` needs to be replaced? `path` should handle the system path separator logic and we shouldn't replace them unless we are using it to execute a command. it technichally won't do anything either because `path.join` normalizes those back if it was replaced if the system uses back slashes

2024-05-12 23:39 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
But `await access` doesn't have a return value. I need a boolean value to decide if I need to return. Or is there a better way?

2024-05-12 23:42 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +    await mkdirp(encryptedFilepathDir);
ok

2024-05-12 23:42 UTC, paologum commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
you have an implementation of `await access` on line 89 already?

2024-05-12 23:43 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  const checkIfAlreadyEncrypted = path.join(encryptedFilepathDir.replaceAll("\\", "/"), filename);
ok I see. Thanks for telling me this

2024-05-12 23:44 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +    console.log("file is encrpted when uploaded");
ok I see what you mean

2024-05-13 00:03 UTC, paologum commented on server/src/routes.ts
> +  if (needEncryption === "true") {
one more thing, you need a case for when it's not encrypted, in that case just send the file and don't call java program

2024-05-13 01:21 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
Yes I have that

2024-05-13 02:19 UTC, paologum commented on server/src/routes.ts
> +  if (needEncryption === "true") {
from what i see, it will always run the java program if the user has uploaded an encrypted file

2024-05-13 02:39 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
No it won't. bc it first check if there is an encrypted file that exist in `encrypted-datapacks` folder, if there exist one, it will return that file without calling the java program. if not, by default the download path is `uuid/datapacks/file.txt`. If `needEncryption` is false, then the download path will never be changed and it will directly download the original file, also the command will not be executed since needEncryption is false. So if you upload an encrypted file the java program will never be called. I just tested it again and it is the case.

2024-05-13 02:41 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
And if you upload an ecrypted file and request encrypted download, it will also first check the header of the file and if it is encrypted it will return and the java program also won't be called in that case.

2024-05-13 18:02 UTC, paologum commented on server/src/routes.ts
> +  if (needEncryption === "true") {
the problem is that you only check `encrypted-datapacks`, the original file could just be encrypted and you don't have any checks for that, so it will run the java program

2024-05-13 18:06 UTC, paologum commented on server/src/routes.ts
> +  if (needEncryption === "true") {
hmm wait i see, but technically if you do it this way for both an encrypted file in the encrypted directory, or the uploaded directory you will potentially delete their uploaded directory datapack

we don't want that because that's their file, and the file in the `uploaded` is guaranteed to be valid

2024-05-13 18:09 UTC, paologum commented on server/src/routes.ts
> +        return;
since we are using this method of checking a header a lot, you should refactor this to a method that returns a boolean. additionally, since we just need the first line and datapacks can be very big it could slow down the process a lot if we are reading in the whole file, so just create a stream and read the first line in that method

2024-05-13 18:25 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
I don't think it will because I don't call rm inside` if (needEncryption)` and it will directly return as long as it finds it is an encrypted file. if it's not then the file has to be encrypted by the java program

2024-05-13 18:27 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
`rm`is only called when 1. the file is in `encrypted-datapacks` 2. the java program gets called and a encrypted-file is generated. Otherwise it will directly return the target file

2024-05-13 18:29 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +        return;
ok

2024-05-13 19:10 UTC, paologum commented on server/src/routes.ts
> +  if (needEncryption === "true") {
then there isn't really a need to dynamically set a `downloadPath`, you should just return the file if `!needEncryption` in the very beginning and just run the encryption checks after the java file runs

it's more confusing if you merge the two cases together, when you can just return early on without running any extra code

2024-05-13 19:12 UTC, paologum commented on server/src/routes.ts
> +      reply.status(404).send({ error: "File not found" });
this should be more specific, because anyone looking at this won't understand what `File not found` means

2024-05-13 19:15 UTC, paologum commented on server/src/routes.ts
> +      reply.status(404).send({ error: "File not found" });
It doesn't have to be anything crazy just give a little more context

2024-05-13 19:16 UTC, paologum commented on server/src/routes.ts
> +      reply.status(500).send({ error: "An error occurred" });
for this and all other 500 status codes, you should send the error with it

2024-05-13 19:17 UTC, paologum commented on server/src/index.ts
> +  "/requestDownload/:filename",
this should just be `/downloads/:filename`

2024-05-13 19:19 UTC, paologum commented on server/src/index.ts
> +  "/requestDownload/:filename",
actually it should be `/downloads/user-datapacks/:filename` because we might download settings xml in the future

2024-05-13 19:19 UTC, paologum commented on server/src/index.ts
> +//download datapack
this also should stay `server.post("/upload", routes.uploadDatapack);`

2024-05-13 19:20 UTC, paologum commented
you should also upload a demo of every use case

2024-05-13 19:29 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
I don't think the cases are merged because rn my workflow does directly return if `!needEncryption` without running any extra code, becasue the huge block inside `if(needEncryption)` won't be executed. I think the part I need to change is that I mistakenly put line 79-82 (which checks if we've encrypted a file before) outside `if(needEncryption)`. I should put that inside `if(needEncryption)` or else it will always return the encrypted file even if the user requests to retrieve the original file. Maybe that's the part where you think that I'm running extra code. Besides that, there's no other code that will be executed.

2024-05-13 19:45 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  if (needEncryption === "true") {
But yeah I can put the immediate return before `if(needEncryption)` if you think that's easier to for other people to read my code

2024-05-13 21:35 UTC, JacquiFreeElectron commented
See demo in my dropbox

2024-05-14 17:27 UTC, paologum requested changes

2024-05-14 17:27 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +        </Fragment>
actually technically since `Menu` is one item, you can just remove the `Fragment` completely i think

2024-05-14 17:27 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +    if (typeof fileURL === "string") {
you should add `fileURL && typeof fileURL === "string"` so they don't download an empty file since you return `""` when `getFileURL` has a bad or empty file

2024-05-14 17:27 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +        ErrorCodes.INCORRET_ENCRYPTION_HEADER,
`INCORRECT`

2024-05-14 17:27 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    } else if (response.status === 422) {
can you make this a switch so it's easier to read

2024-05-14 17:27 UTC, paologum commented on app/src/util/error-codes.ts
> +  FILE_NOT_FOUND = "FILE_NOT_FOUND",
`FILE_NOT_FOUND` is too generic it should be `USER_DATAPACK_FILE_NOT_FOUND_FOR_DOWNLOAD`

2024-05-14 17:27 UTC, paologum commented on app/src/util/error-codes.ts
> +  [ErrorCodes.FILE_NOT_FOUND]: "The file you want to download was not found.",
this is too direct, use "The datapack requested was not found on the server. Please try again later or contact our support team"

2024-05-14 17:27 UTC, paologum commented on app/src/util/error-codes.ts
> +    "Java file was unable to encrypt the file you want to download, resulting in an incorrect encryption header."
we don't need to tell the user that the java file couldn't encrypt, this should be a message that the `displayServerError` handles since it takes in the server response variable. The user should just see "Unable to encrypt the file, please try again later."

2024-05-14 17:27 UTC, paologum commented on server/src/parse-datapacks.ts
> +  isUserDataPack?: boolean
you should do `isUserDatapack?: boolean = false` or however to default it to false then make `isUserDatapack` a required field on `DatapackParsingPack` for better structure, otherwise you have `undefined` `false` and `true` when we just want two of those values.

2024-05-14 17:27 UTC, paologum commented on server/src/routes.ts
> +  request: FastifyRequest<{ Params: { filename: string }; Querystring: { needEncryption: boolean } }>,
still needs resolution

2024-05-14 17:27 UTC, paologum commented on server/src/routes.ts
> +  } else if (needEncryption) {
so we aren't nesting you can just do `if (!needEncryption)` then you won't need an `else if` because you return

2024-05-14 17:27 UTC, paologum commented on server/src/routes.ts
> +    const downloadPath = path.join(encryptedFilepathDir, filename);
this is a duplicate variable of `maybeEncryptedFile`

2024-05-14 17:27 UTC, paologum commented on server/src/routes.ts
> +        reply.status(404).send({ error: "File not found" });
this should be more specific that it can't find the user datapack requested

2024-05-14 19:10 UTC, paologum commented on server/src/routes.ts
> +  request: FastifyRequest<{ Params: { filename: string }; Querystring: { needEncryption: boolean } }>,
it should be `needEncryption?: boolean`

2024-05-14 19:23 UTC, JacquiFreeElectron commented on server/src/routes.ts
> +  request: FastifyRequest<{ Params: { filename: string }; Querystring: { needEncryption: boolean } }>,
Oh do you mean just do `Querystring: { needEncryption?: boolean }`?

2024-05-14 19:24 UTC, paologum commented on server/src/routes.ts
> +  request: FastifyRequest<{ Params: { filename: string }; Querystring: { needEncryption: boolean } }>,
yup!

2024-05-14 19:29 UTC, paologum commented on server/src/routes.ts
> +    const file = await readFile(filepath);
also this should be in a try

2024-05-14 20:46 UTC, paologum requested changes

2024-05-14 20:46 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +          null,
you should send `response` as the first parameter

2024-05-14 20:46 UTC, paologum commented on app/src/util/error-codes.ts
> +  USER_DATAPACK_FILE_NOT_FOUND_FOR_DOWNLOAD = "FILE_NOT_FOUND",
change `FILE_NOT_FOUND`

2024-05-14 20:46 UTC, paologum commented on server/__tests__/__data__/column-keys.json
to make this a cleaner merge, can you just copy paste the original file so there isn't 4000 lines of difference and change only the couple of lines you need. the reason for these test files isn't to copy paste every time we change something but to change the small things we add

2024-05-14 20:46 UTC, paologum commented on server/src/index.ts
> +server.get<{ Params: { filename: string }; Querystring: { needEncryption: boolean } }>(
`needEncryption?:`

2024-05-14 20:46 UTC, paologum commented on server/src/parse-datapacks.ts
> +  const isUserDatapack = isUserDataPack;
no need for this variable?

2024-05-14 20:46 UTC, paologum commented on server/src/util.ts
> +}
we should have a small test set for this, but not a part of this pr

2024-05-14 20:52 UTC, JacquiFreeElectron commented on server/src/parse-datapacks.ts
> +  const isUserDatapack = isUserDataPack;
I tried to eliminate this variable but the `isUserDatapack` of datapackParsingPack will become undefined. Not sure why. I can try again but I think I need this variable

2024-05-14 20:57 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
> +          null,
Do you mean `displayServerError(response, ErrorCodes.SERVER_RESPONSE_ERROR, ErrorMessages[ErrorCodes.SERVER_RESPONSE_ERROR]);`

2024-05-14 20:58 UTC, JacquiFreeElectron commented on app/src/util/error-codes.ts
> +  USER_DATAPACK_FILE_NOT_FOUND_FOR_DOWNLOAD = "FILE_NOT_FOUND",
right🤦🏻‍♀️

2024-05-14 21:01 UTC, JacquiFreeElectron commented on server/__tests__/__data__/column-keys.json
ok

2024-05-14 21:01 UTC, JacquiFreeElectron commented on server/src/util.ts
> +}
sure

2024-05-14 21:08 UTC, JacquiFreeElectron commented on server/__tests__/__data__/column-keys.json
oh but I think the reason there are 4000 lines of difference is that the lines I modified moved the places of other lines. Probably copy-paste the original file won't fix that?  I can try it tho.

2024-05-14 21:14 UTC, JacquiFreeElectron commented on server/src/parse-datapacks.ts
> +  const isUserDatapack = isUserDataPack;
I tried again and I have to either keep this variable or do `datapackParsingPack.isUserDatapack = isUserDataPack` after line 286. Otherwise, it will become undefined.

2024-05-14 22:07 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +          null,
yes

2024-05-14 22:46 UTC, paologum commented on server/src/parse-datapacks.ts
> +  const isUserDatapack = isUserDataPack;
it's because you're passing it as `isUserDataPack` instead of `isUserDatapack`

2024-05-14 22:49 UTC, JacquiFreeElectron commented on server/src/parse-datapacks.ts
> +  const isUserDatapack = isUserDataPack;
ahh yes. Changed it

2024-05-14 23:22 UTC, paologum approved these changes
nice job!!:)

2024-05-15 00:44 UTC, merged