Tsc 331 style emails
earthhistoryviz/tsconline pull request #103
Opened 2024-05-12 17:10 UTC by asivath

PreHeader:
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/be1c433a-8b45-4963-bb62-f81bb09e31f1)
Email with button:
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/a99039d1-5306-4a73-926a-9778c772c62e)
One more with button:
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/982c6918-5c3e-44d8-9be6-1ff4ec8c492b)
Email without button:
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/55b6f597-141f-490d-bd5d-4b6b0fd4b3cb)

2024-05-12 23:49 UTC, paologum commented
future note: we should add contact details here or a link to the support page

2024-05-12 23:57 UTC, paologum requested changes

2024-05-12 23:57 UTC, paologum commented on server/src/login-routes.ts
> +    await sendEmail(invalidateEmail);
do we need to `await` these now?

2024-05-12 23:57 UTC, paologum commented on server/src/send-email.ts
> +  action: string,
do you need to sanitize these just in case a user email or something has bad stuff in it, or a username?

also for future reliability for other programmers to not call this template with dumb things

2024-05-13 00:22 UTC, asivath commented on server/src/login-routes.ts
> +    await sendEmail(invalidateEmail);
initially i didn't want to await because sending an email could take a bit but it can throw errors and that should be shown to the user

2024-05-13 00:58 UTC, asivath commented on server/src/send-email.ts
> +  action: string,
yeah i'll use dompurify for this

2024-05-14 17:13 UTC, paologum approved these changes

2024-05-15 01:25 UTC, merged