Tsc 310 backend for load settings
earthhistoryviz/tsconline pull request #104
Opened 2024-05-12 23:17 UTC by jay-jhk-lee

**migrated changes on prior task 310 to this branch due to a rebase issue, delete the other one after this is merged**

added the backend for loading settings files. Created a function to recursively go down the info given by the settings file and accessing the respective column info state. Standardized the parameters of the setter functions for columnInfo. Added formatting to the column names when parsing datapack to align with tscreator and the settings file.

2024-05-13 00:27 UTC, paologum requested changes

2024-05-13 00:27 UTC, paologum commented on app/src/SettingsTabs/EditNameField.tsx
> +          </Button>
if you're already changing/moving this
1. the team discussed removing the confirm removal, so can you remove that button and change the event to `onChange` of the Text Field
2. instead of using a `useRef` hook, just make the value `column.editName` (this is sorta the same as 1.)
3. remove the css for the button
4. if you can make this a react fragment ( verify it works as a react fragment )

2024-05-13 00:27 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +        setEventColumnSettings(column.columnSpecificSettings, { type: settings.type, rangeSort: settings.rangeSort });
you will need to add `PointSettings` because it's on main now

2024-05-13 00:27 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    console.log("Unknown column name " + columnName + " found while loading settings");
There should be a hard limit to the max character count that we can push to a snackbar. Not sure what it is but this should truncate `columnName` to fit that character count. If it's not a constant variable and we just set it somewhere can you move it to `constant.ts`

2024-05-13 00:27 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
we shouldn't need `blockSeriesColumn` right? we can just do `if... else`? or is there a case im unaware of

2024-05-13 00:27 UTC, paologum commented on app/src/state/parse-settings.ts
> +        }
previous comment of 

it would be beneficial for us to split `fontProps[i]` early by ": " and call it like `fontPropKey` then check includes on that for less comparisons. also the nested ifs can just be one if statement with `&&`

2024-05-13 19:27 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +  }
that should work

2024-05-14 17:38 UTC, paologum requested changes

2024-05-14 17:38 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          }
i made a `util` function for this that converts `PointShape` to the other type on my pr, just a comment for how you or i might rebase fyi

2024-05-14 17:38 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      "warning"
don't you have to account for the other string lengths as well?

2024-05-14 17:38 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    console.log(columnName);
remove

2024-05-14 17:38 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +});
oops, on my pr i change it to `Object.assign` so it's just one line and you should also probably go that way. I realized since we can gurantee that the `newSettings` has all of the `PointSettings` fields, we can just assign since there will be no new keys

2024-05-14 17:38 UTC, paologum commented on server/src/parse-datapacks.ts
> +  if (column.name.includes("Nanno Zone")) console.log(column.name);
remove

2024-05-14 17:38 UTC, paologum commented on server/src/parse-datapacks.ts
> +    parent = formatColumnName(parent);
will this propagate to the recursive function properly

2024-05-14 17:38 UTC, paologum commented on app/src/state/parse-settings.ts
> +  //assertChartInfoTSC(settingsTSC);
you can remove this

2024-05-14 23:50 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +      "warning"
What other string lengths are you referring to?

2024-05-14 23:51 UTC, jay-jhk-lee commented on server/src/parse-datapacks.ts
> +    parent = formatColumnName(parent);
This will properly work for the key and values in the `allEntries` mapping

2024-05-15 16:56 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      "warning"
the whole string is `snackbarTextLengthLimit` not just the `columnName`

2024-05-15 16:56 UTC, paologum commented on server/src/parse-datapacks.ts
> +    parent = formatColumnName(parent);
ok looks good

2024-05-15 17:22 UTC, paologum approved these changes

2024-05-15 17:25 UTC, merged