Tsc 312 shift column order
earthhistoryviz/tsconline pull request #113
Opened 2024-05-21 13:01 UTC by Changk820

Updated shift row buttons to fix alignment and included text to tell what buttons do

2024-05-22 01:42 UTC, paologum commented
can you upload a demo to the git description

2024-05-22 01:51 UTC, paologum requested changes
nice work, you probably will need another task right after this, i'll add one and lyk

2024-05-22 01:51 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +            </div>
you can keep this in this file, but can you abstract this away into its own component

2024-05-22 01:51 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +
these should move to that component as well and should just use the passed in `column` that you would send through that component like the other menu fields

2024-05-22 01:51 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +});
you should add the check `if (index < parent.children.length - 1 && index > -1)` to decrement just to be robust if our hash map doesn't contain the necessary and correct columns

2024-05-23 01:31 UTC, Changk820 commented
Demo: 
https://www.youtube.com/watch?v=3zZtT2hiqmg
It was 100mb even after I lowered the FPS, video and audio quality, so I just made it into Youtube video

2024-05-23 01:35 UTC, Changk820 commented
I think I fixed the changes you requested and pushed them, let me know if you are able to see the pushes, thanks.

2024-05-23 03:14 UTC, paologum requested changes

2024-05-23 03:14 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +            />
instead of passing in the function, to keep it more clean since this menu might get bigger/more complex just pass in column and use the `useContext` hook within the function

2024-05-23 03:14 UTC, paologum commented on app/src/SettingsTabs/AccordionPositionControls.tsx
> +  };
since the props guarantee the existence of column as `ColumnInfo` these `if` statementes aren't needed

2024-05-23 03:15 UTC, paologum commented
buttons and demo look great!

2024-05-23 17:49 UTC, paologum approved these changes

2024-05-23 17:50 UTC, paologum commented
make sure to rebase

2024-05-23 23:40 UTC, merged