Tsc 330 frontend for load save settings
earthhistoryviz/tsconline pull request #115
Opened 2024-05-22 17:53 UTC by jay-jhk-lee

added the frontend for load and save settings
can specify filename when saving
various snackbar notifications for success/error

https://github.com/earthhistoryviz/tsconline/assets/89719669/7cb84338-8759-4b1a-acf7-726be36751fb

2024-05-23 17:46 UTC, paologum requested changes
frontend looks good!

2024-05-23 17:46 UTC, paologum commented on app/package.json
> +    "@mui/material": "^5.15.18",
is there a reason? if not you should revert so that the diff isn't huge

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/LoadSettings.tsx
> +      actions.pushSnackbar("failed to load settings: no files uploaded", "info");
capitalize failed

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/LoadSettings.tsx
> +    actions.pushSnackbar("successfully loaded settings from " + file.name + "!", "success");
capitalize successfully

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/LoadSettings.tsx
> +          <DialogContentText id="alert-dialog-description">
if you aren't using the id's just remove them so that errors don't popup if anyone else uses the template

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/LoadSettings.tsx
> +        <FileUploadIcon className="load-button" />
can you make the className's `icon-load-settings-button` and `load-settings-button` since those `className`'s are a little generic if we ever incorporate a load button for anything else

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/SaveSettings.tsx
> +    actions.pushSnackbar("successfully saved settings!", "success");
capitalize successfully

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/SaveSettings.tsx
> +        <DownloadIcon className="save-button" />
same as above for here

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/SaveSettings.tsx
> +          onSubmit: (e: { preventDefault: () => void }) => {
shouldn't the param just be `e: React.FormEvent<HTMLFormElement>`

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/SaveSettings.tsx
> +  const handleChange = (e: { target: { value: string } }) => {
same here since this syntax is a little odd it should be the event type

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/SaveSettings.tsx
> +export default function SaveSettings() {
this should be in an observer right because how does it know to reload when `state.loadSaveFileName` changes on multiple loads

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/SaveSettings.tsx
> +            handleClose();
you should probably add the filename format check here?

2024-05-23 17:46 UTC, paologum commented on app/src/components/TSCFileUpload.tsx
> +        startIcon={startIcon}
i think it should work fine without the if statement

2024-05-23 17:46 UTC, paologum commented on app/src/components/TSCFileUpload.tsx
> +  color,
you should do `color = "inherit"` here to reduce the ternary below

2024-05-23 17:46 UTC, paologum commented on app/src/components/TSCFileUpload.tsx
> +  variant: "text" | "outlined" | "contained";
this should also have a default value and should be optional

2024-05-23 17:46 UTC, paologum commented on app/src/state/parse-settings.ts
> +      settings[settingName].push({ unit: settingNode.getAttribute("unit")!, text: settingValue === "true" });
you should have checks for if they don't have a `unit` attribute

2024-05-23 17:46 UTC, paologum commented on app/src/state/parse-settings.ts
> +
have checks for if those indexes don't exist

2024-05-23 17:46 UTC, paologum commented on app/src/state/parse-settings.ts
> +    } else if (key === "type" && extractColumnType(column._id) === "sequence") {
the column type should be `SequenceColumn`

2024-05-23 17:46 UTC, paologum commented on package-lock.json
i'm not sure why this diff is so large, i'll recheck if you rollback the `mui` or lmk why

2024-05-23 17:46 UTC, paologum commented on app/src/SettingsTabs/LoadSettings.tsx
> +    }
i don't see a reason for this to be in a `try...finally` block?

2024-05-23 22:55 UTC, jay-jhk-lee commented on app/src/SettingsTabs/SaveSettings.tsx
> +          onSubmit: (e: { preventDefault: () => void }) => {
yeah that works

2024-05-23 23:58 UTC, jay-jhk-lee commented on app/package.json
> +    "@mui/material": "^5.15.18",
No reason, I'm not sure why it changed

2024-05-24 00:15 UTC, jay-jhk-lee commented on app/src/SettingsTabs/SaveSettings.tsx
> +export default function SaveSettings() {
I've tested it and the filename changes properly on multiple loads, it's probably because the save modal rerenders everytime it opens. But I agree that adding the observer is a good idea just in case

2024-05-24 00:15 UTC, jay-jhk-lee commented on app/src/SettingsTabs/LoadSettings.tsx
> +    }
yeah you right

2024-05-24 00:47 UTC, jay-jhk-lee commented on package-lock.json
it might be because I have a bunch of different packages for some reason, I just pushed my yarn cache folder and it looks to be that way

2024-05-27 15:58 UTC, paologum approved these changes
hopefully the large yarn changes don't stop the dev server from pulling but looks good!

2024-05-27 23:04 UTC, merged