Tsc 303 add account customization and deleting account
earthhistoryviz/tsconline pull request #118
Opened 2024-05-27 19:37 UTC by asivath

https://github.com/earthhistoryviz/tsconline/assets/94872897/42da7d7e-e049-4321-aa57-e39ff0495caa

Things that need to be added are forgot username and also admin controls

2024-05-27 19:52 UTC, paologum commented
your video shows only username and delete account but i assume the change email, change password are the same as the signup/login page flows? also does the change profile picture works? and anything else that you didn't demo. i haven't yet looked at the code btw

2024-05-27 20:03 UTC, asivath commented
the first video shows me changing the password. it works differently from the login page since it doesn't require you to go through your email, instead just needing your current password and the session. email change follows the normal flow. the profile picture does work I show me changing it to the tscreator logo. none of the settings stuff do anything just frontend.

2024-05-27 20:52 UTC, paologum requested changes
also one thing, instead of a large file upload button, can you make the profile picture and icon button or however with like a pencil in the bottom right. like the picture below but in the bottom right but have both the pro pic and the pencil be clickable/do the same thing as the button.

![image](https://github.com/earthhistoryviz/tsconline/assets/89664317/f965a2d7-9ac9-4ae7-b6f1-7d63b710e3b1)

2024-05-27 20:52 UTC, paologum commented on app/src/Profile.tsx
> +        actions.pushSnackbar("Profile deleted successfully. Please log in again.", "success");
i think we can just keep it `Profile deleted successfully` and not the second part since they don't technically need/want to log in again

2024-05-27 20:52 UTC, paologum commented on app/src/Profile.tsx
> +                      }
styling comment so you don't have to do this but you can just combine these

2024-05-27 20:52 UTC, paologum commented on app/src/Profile.tsx
> +                          window.location.reload();
does this not update properly since `pictureUrl` is observable? bc i think this causes the site to flash right

2024-05-27 20:52 UTC, paologum commented on app/src/Profile.tsx
> +export const Profile: React.FC<Profile> = observer(({ pictureUrl }) => {
since most of the values are kept in state that are used in this component, shouldn't we just access `pictureUrl` through the state

2024-05-27 20:52 UTC, paologum commented on app/src/components/TSCAccountMenu.tsx
> +            aria-expanded={open ? "true" : undefined}>
small q what does `aria` do

2024-05-27 20:52 UTC, paologum commented on server/src/login-routes.ts
> +    reply.send({ message: "Profile deleted" });
also delete file metadata entries

2024-05-27 20:52 UTC, paologum commented on server/src/login-routes.ts
> +    reply.status(500).send({ error: "Unknown Error" });
shouldn't we send error object?

2024-05-27 20:52 UTC, paologum commented on app/src/Profile.tsx
> +            break;
no 403 status? they might not understand if they have a google account

2024-05-27 20:52 UTC, paologum commented on server/src/login-routes.ts
> +    reply.status(500).send({ error: "Unknown Error" });
same with error obj

2024-05-27 20:52 UTC, paologum commented on server/src/login-routes.ts
> +    await mkdirp(userDirectory);
try catch?

2024-05-27 20:52 UTC, paologum commented on app/src/components/TSCAccountMenu.tsx
> +        </MenuItem>
since i don't think there's support for adding another account, do they get signed out of their current account if they attempt to login to two different accounts?

2024-05-27 20:52 UTC, paologum commented on server/src/index.ts
> +server.post("/auth/send-forgotpassword-email", strictRateLimit, loginRoutes.sendForgotPasswordEmail);
lowk this should be `forgot-password` with a dash it looks kinda weird

2024-05-27 21:50 UTC, asivath commented on app/src/Profile.tsx
> +                          window.location.reload();
this ties in with the next comment but for some reason the observer is not reacting to changes in pictureUrl after uploading. i tried just using state before but that doesn't work either. after uploading the only way to get it to change was to refresh the page or keep track of the url in local state.

2024-05-27 21:52 UTC, asivath commented on app/src/Profile.tsx
> +export const Profile: React.FC<Profile> = observer(({ pictureUrl }) => {
above

2024-05-27 21:54 UTC, asivath commented on app/src/components/TSCAccountMenu.tsx
> +            aria-expanded={open ? "true" : undefined}>
it helps people with disabilities that use screen readers. it provides screen readers context about the website

2024-05-27 22:20 UTC, asivath commented on app/src/Profile.tsx
> +            break;
a normal user will not come across 403 since I hide the change password section to google users. should we allow google users to change their password here because then they would have no current password to enter.

2024-05-27 22:24 UTC, asivath commented on server/src/login-routes.ts
> +    await mkdirp(userDirectory);
its surrounded by a try catch

2024-05-27 22:30 UTC, asivath commented on app/src/components/TSCAccountMenu.tsx
> +        </MenuItem>
that will make them go through the email link thing where they will get assigned a new session.

2024-05-28 17:01 UTC, paologum commented on app/src/Profile.tsx
> +                          window.location.reload();
can you try making the onChange handler an action

2024-05-28 17:03 UTC, paologum commented on app/src/components/TSCAccountMenu.tsx
> +        </MenuItem>
what email link thing, in your demo it looked like they were still signed in on the sign in page?

2024-05-28 17:04 UTC, paologum commented on app/src/Profile.tsx
> +            break;
hmm ok yeah that's fine

2024-05-29 20:46 UTC, asivath commented on app/src/components/TSCAccountMenu.tsx
> +        </MenuItem>
i didn't show this, if they were to try to add an account they would be going through user/pass verification which would send them an email which when they clicked on it would set them a new session. i'm still logged in because I did not actually go through that entire flow.

2024-06-02 17:43 UTC, asivath commented on app/src/Profile.tsx
> +                          window.location.reload();
the issue was that the url was never changing so the browser was caching the request for the image. the solution was to add a random parameter to the url to force it to fetch the new content.

2024-06-03 22:25 UTC, paologum commented
that pencil is so big LMAO, can you make it smaller? maybe like 1/2 the size? send me a pic before you push and i'll lyk

2024-06-03 23:12 UTC, paologum commented on app/src/Profile.tsx
> +                          window.location.reload();
that is crazy, good find

2024-06-03 23:13 UTC, paologum commented on app/src/components/TSCAccountMenu.tsx
> +        </MenuItem>
oh ok so they can't go back and forth between emails like google does right, this is just a way of skipping essentially signing out

2024-06-03 23:35 UTC, asivath commented
https://github.com/earthhistoryviz/tsconline/assets/94872897/1d42bd50-e326-4519-ab48-c1985747fd65

2024-06-04 00:27 UTC, asivath commented on app/src/components/TSCAccountMenu.tsx
> +        </MenuItem>
yes

2024-06-05 16:42 UTC, paologum requested changes

2024-06-05 16:42 UTC, paologum commented on app/src/Profile.tsx
> +              onMouseLeave={() => setIsHovered(false)}
instead of `pencil-hover`
```
.editable-profile-picture:hover + .MuiBadge-badge .badge .pencil {
  color: #188de6;
}
```
`+` is same level and space between css selecters mean direct descendents

2024-06-07 06:56 UTC, paologum approved these changes

2024-06-08 04:38 UTC, merged