added function to apply row order
earthhistoryviz/tsconline pull request #119
Opened 2024-05-28 19:58 UTC by jay-jhk-lee

loading settings file now applies the correct row order

https://github.com/earthhistoryviz/tsconline/assets/89719669/e80c5ca7-20bb-4ee1-9896-4493bbfa904d

2024-05-30 00:46 UTC, paologum requested changes

2024-05-30 00:46 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
should add a check that `columnIndex == column.children.length` for robustness

2024-05-30 00:46 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
for readability, i think `indexOf` would make this easier to read

also add a check for index value `-1` for robustness

2024-05-30 00:46 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      "Chart Title in " + currName !== column.children[columnIndex].name
since you check if the hash map has `currName`, the check for `"Chart Title in " + currName !== column.children[columnIndex].name` will never be hit

instead you should normalize `currName` earlier if the parent is `Chart Root` and the type of column is `RootColumn` and the unit is not `Ma` then it should append `Chart Title in` to the beginning.

also since we are using it a lot of places now, it might be better to localize `Chart Title in ` to a constant then apply it everywhere we use it for easier readability and change. Call it maybe `altUnitNamePrefix`

2024-06-01 18:40 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
oops i meant this line can be `column.children.findIndex(child => child.name == childName)`

2024-06-01 18:40 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
do we want to increment the `columnIndex` if `indexOfMatch !== -1`?

2024-06-01 23:39 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +  }
I've made some changes so it should work now

2024-06-02 05:37 UTC, paologum approved these changes

2024-06-02 14:49 UTC, merged