Tsc 373 fix download of datapack error
earthhistoryviz/tsconline pull request #121
Opened 2024-05-30 04:43 UTC by JacquiFreeElectron

fix the problem of uuid being undefined when requesting a download. Also, no file will be downloaded to user's computer if not logged in

https://github.com/earthhistoryviz/tsconline/assets/104879321/e0491008-a2ac-4725-a496-f149a83bff8f

2024-05-30 21:50 UTC, paologum requested changes

2024-05-30 21:50 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      }
for less dupe code, and also for a default value to be in place, you should have the cases change the error code, and at the end of the `if`, `displayServerError` and set a default value initially, that way unknown status codes will still print a value

2024-05-30 21:50 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
>      }
if `getFileURL` returns null or empty, `handleDownload` creates an `aTag` that never gets removed, so you should either always remove it or only create it if `fileURL` exists

2024-05-31 01:25 UTC, JacquiFreeElectron commented on app/src/settings_tabs/Datapack.tsx
>      }
I think `handleDownload `only create `aTag` when `fileURL` exists bc I checked `if (fileURL && typeof fileURL === "string") `

2024-05-31 02:00 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    displayServerError(response, errorCode, errorMessage);
errormessage is just `ErrorMessages[errorCode]` so you don't need to set it each time, you can just set `errorCode` then abstract it here

2024-06-01 18:44 UTC, paologum approved these changes

2024-06-01 19:42 UTC, merged