added tests for parsing columns
earthhistoryviz/tsconline pull request #123
Opened 2024-06-02 19:44 UTC by jay-jhk-lee

added tests for font change, basic, event, point columns, and a comprehensive settings file.

2024-06-03 21:52 UTC, paologum commented
no test file

2024-06-03 22:13 UTC, paologum requested changes

2024-06-03 22:13 UTC, paologum commented on app/__tests__/parse-settings.test.ts
> +});
the way this should be testing is below, that way errors can be caught easily and found easily in the correct function. This tests the whole function and doesn't go with a unit testing approach.

make keys and test `columnInfoTSCToXml`, `extractColumnType` `generateFontsXml`, `translateColumnInfoToColumnInfoTSC`, `escapeHtmlChars` and `generateSettingsXml`.

you should also reduce a lot of the test size by mocking things simpler. for example `jsonToXml` is really simple. you don't need to use `jsonToXml` as an overarching test. you can just mock `generateSettingsXml` and `columnInfoTSCToXml` to return `""` so that you can just test that function. This means tests are a lot easier to read and are more unit testy. In the same area, you would use `generateSettingsXml` to see the settings only, and any other calls to this from other tests shouldn't need to worry about whether or not `generateSettingsXml` works

2024-06-05 16:05 UTC, paologum requested changes

2024-06-05 16:05 UTC, paologum commented on app/__tests__/parse-settings.test.ts
> +});
you probably shouldn't have the key in a seperate file like above stated. also can't you use a previous `ColumnInfo` test instead of making a new one that technically isn't tested? also what does prolog mean

2024-06-05 16:05 UTC, paologum commented on shared/src/constants.ts
> +  doNotSetWindowAuto: true,
i set this to always false because i do the logic myself and it wouldn't be good if the frontend changes from what is displayed without the user knowing why

2024-06-05 17:02 UTC, jay-jhk-lee commented on app/__tests__/parse-settings.test.ts
> +      }
I tried instantiating it outside as a const which resulted in "ReferenceError: Cannot access 'fontsInfo' before initialization" and putting it inside the mock statement which resulted in "Cannot find name 'fontsInfo'" but both didn't work, so I had to put it for each variable

2024-06-05 17:03 UTC, jay-jhk-lee commented on app/__tests__/parse-settings.test.ts
> +      }
and i can't import it from shared since it also throws the cannot access before initialization error

2024-06-05 17:14 UTC, jay-jhk-lee commented on app/__tests__/parse-settings.test.ts
> +  });
> you can add the `it` to the `test.each` ?

I've tried it and it throws an error: `Tests cannot be nested. Test "" cannot run because it is nested within "should return undefined for incorrectly formatted id".`

2024-06-05 21:55 UTC, jay-jhk-lee commented on app/__tests__/parse-settings.test.ts
> +});
prolog is the very top line of the xml with the xml version and encoding

2024-06-07 07:06 UTC, paologum approved these changes

2024-06-07 15:28 UTC, merged