Tsc 353 ask for cookies
earthhistoryviz/tsconline pull request #124
Opened 2024-06-03 18:39 UTC by Changk820

Demo: https://www.youtube.com/watch?v=6aEuoBVOVwo

2024-06-03 22:15 UTC, paologum commented
can you just disable the buttons instead of removing them? if you do so that way you shouldn't need to refresh the page if you use `useState`. I also haven't read the code yet but this is just from the demo

2024-06-03 22:24 UTC, paologum requested changes

2024-06-03 22:24 UTC, paologum commented on app/src/CookieConsent.tsx
> +  }, [persistent]);
i'm not sure if we need a `useEffect` hook that updates on `persistent`
what's wrong with just having these two statements and settings
to my knowledge, `isVisible` is the refresher, and `persistent` does not need to enable refreshes
```
  const savedConsent = localStorage.getItem("cookieConsent");
  const shouldShowConsent = !savedConsent || (persistent && savedConsent !== "accepted");
  const [isVisible, setIsVisible] = useState(shouldShowConsent);
```

2024-06-03 22:24 UTC, paologum commented on app/src/CookieConsent.tsx
> +    window.location.reload(); // Refresh the page after accepting cookies
i don't believe this is necessary, could you explain why you need to reload?

2024-06-03 22:24 UTC, paologum commented on app/src/CookieConsent.tsx
> +  zIndex: 1000 // Ensure it's above everything else
verify this goes over map points

2024-06-03 22:24 UTC, paologum commented on app/src/Login.tsx
> +              </TSCButton>
you should probs just disable instead of not showing it

2024-06-03 22:24 UTC, paologum commented on app/src/Login.tsx
> +              />
same here if possible

2024-06-03 22:24 UTC, paologum commented on app/src/Login.tsx
> +              />
also for future reference if you only want to load based on a condition you can do
```
cookieConsent === "accepted" && <Component/>
```

2024-06-03 22:24 UTC, paologum commented on app/src/CookieConsent.tsx
> +const CookieConsent: React.FC<CookieConsentProps> = ({ persistent = false }) => {
is persistent needed anymore?

2024-06-05 19:47 UTC, Changk820 commented on app/src/CookieConsent.tsx
> +    window.location.reload(); // Refresh the page after accepting cookies
Aaron wanted the sign in button to be removed if the cookies are not accepted, but after accepting, I had to refresh the page to see the buttons show up again.

2024-06-05 19:51 UTC, Changk820 commented on app/src/CookieConsent.tsx
> +  zIndex: 1000 // Ensure it's above everything else
I thought we were only displaying this while you were on the homepage/signin? So it doesn't show up at same time asa map point

2024-06-05 20:15 UTC, Changk820 commented on app/src/CookieConsent.tsx
> +  }, [persistent]);
You're right

2024-06-05 20:32 UTC, Changk820 commented on app/src/Login.tsx
> +              </TSCButton>
made the changes

2024-06-05 20:33 UTC, Changk820 commented on app/src/Login.tsx
> +              />
apparently GoogleLogin doesn't have a disable component, but did it with CSS

2024-06-05 20:35 UTC, Changk820 commented on app/src/CookieConsent.tsx
> +const CookieConsent: React.FC<CookieConsentProps> = ({ persistent = false }) => {
I think so.
isVisible makes it show or not show
Persistent is to differentiate between being on the home page and being on the sign in page(persistent)

2024-06-05 21:12 UTC, Changk820 commented
New video
https://youtu.be/vgWTW4cLy0g
<sup><sub>~~Like, subscribe and hit that notification button~~<sub><sup>

2024-06-07 06:06 UTC, paologum commented on app/src/CookieConsent.tsx
> +  zIndex: 1000 // Ensure it's above everything else
ok i guess that's fine then

2024-06-07 06:08 UTC, paologum commented on app/src/CookieConsent.tsx
> +    if (persistent) window.location.reload(); // Refresh the page after accepting cookies so sign in shows
we don't want to do `window.location.reload()` because it refreshes components that don't need to be refreshed. instead we want to hold the cookie acceptance policy in the state. if cookie acceptance policy is accepted, enable the `sign-in` if not disable all `sign-in`. on `initialize` we should then set that state variable to the `localStorage` keys value

2024-06-07 06:10 UTC, paologum commented on app/src/Login.tsx
> +  const cookieConsent = localStorage.getItem("cookieConsent");
from my previous comment, this would be a part of the large state object and would auto refresh the components that use it

2024-06-10 23:29 UTC, paologum requested changes

2024-06-10 23:29 UTC, paologum commented on app/src/state/state.ts
> +  cookieConsent: boolean | null;
this should probably just be `boolean` and auto set to `false`

2024-06-10 23:29 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    if (data.authenticated && state.cookieConsent) {
you don't need to have consent to check the session so this should stay what it was

2024-06-10 23:29 UTC, paologum commented on app/src/Login.css
> +.disabled {
call this a more specific name like `disabled-google-login` just so no overlap in css occurs elsewhere

2024-06-10 23:29 UTC, paologum commented on app/src/CookieConsent.tsx
> +  const shouldShowConsent = !savedConsent || (persistent && savedConsent !== "true");
these should change to what you have now in state and `CookieConsent` should be wrapped in an `observer`

2024-06-10 23:29 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +});
like aaron said, this should also set `localStorage` so that whenever you change it, it changes both vars to be the same value

2024-06-11 00:20 UTC, Changk820 commented on app/src/state/actions/general-actions.ts
> +    if (data.authenticated && state.cookieConsent) {
But what if say use accepted the cookies, logged in, then signed in and cleared localstorage/cookies? they would be put in a  weird place, where they are signed in, but cookies are technically not accepted, so I feel like this should be here.

2024-06-11 00:21 UTC, Changk820 commented on app/src/state/state.ts
> +  cookieConsent: boolean | null;
I have to have it null because if I initialize it as false, the home screen cookie notification would go away because if any action is taken, it disappears. Being set as false means action was taken.

2024-06-11 00:22 UTC, Changk820 commented on app/src/Login.css
> +.disabled {
okay

2024-06-11 00:26 UTC, paologum commented on app/src/state/state.ts
> +  cookieConsent: boolean | null;
i see i see nvm then

2024-06-11 00:28 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    if (data.authenticated && state.cookieConsent) {
if they cleared local storage/cookies then they won't have a valid session anymore and shouldn't be signed in on reload

2024-06-21 06:50 UTC, paologum requested changes

2024-06-21 06:50 UTC, paologum commented on app/src/CookieConsent.tsx
> +import { context, state } from "./state";
don't import `state` from `./state`,
do `const { state, actions } = useContext(context)`

2024-06-21 06:50 UTC, paologum commented on app/src/Login.tsx
> +              disabled={state.cookieConsent === false}>
shouldn't this just be `!state.cookieConesnt` because if `state.cookieConsent = null` it won't be disabled.

applies to line 165 and 154 as well

2024-06-21 06:50 UTC, paologum commented on app/src/Login.tsx
> +            <div className={state.cookieConsent === false ? "disabled-google-login" : ""}>
same here

2024-06-21 06:50 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  state.cookieConsent = localStorage.getItem("cookieConsent") === "true";
this should check if it exists and set the boolean to the corresponding value, but if it doesn't exist then the `state.cookieConsent` should be `null`

2024-06-22 18:51 UTC, paologum approved these changes
great!

2024-06-23 17:37 UTC, merged