Tsc 393 fix min max problems with datamining auto scaling
earthhistoryviz/tsconline pull request #129
Opened 2024-06-14 21:46 UTC by JacquiFreeElectron

2024-06-15 19:30 UTC, paologum requested changes
have you verified this auto scales the same as the java program? should be the same number

2024-06-15 19:30 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  );
you're assuming here the column is in the unit at index 0 but what if it's at 1,2,etc

2024-06-30 19:09 UTC, JacquiFreeElectron commented
Now the datamining auto scale range is the same as the jar, expect for a very small different due to round up/ precision difference (and I verified the way jar calculate the range is most accurate for drawing the chart so I used their way tho it doesn't look very elegant)

Combined:
![combined](https://github.com/earthhistoryviz/tsconline/assets/104879321/8957e915-d24b-4574-83c5-5006eacc9dae)
FAD:
![FAD](https://github.com/earthhistoryviz/tsconline/assets/104879321/a3d080fb-b3e3-4860-97f6-a377623bf41a)
LAD:
![LAD](https://github.com/earthhistoryviz/tsconline/assets/104879321/381beb5a-8659-43f1-a231-665f65192f8a)
Freq:
![Freq](https://github.com/earthhistoryviz/tsconline/assets/104879321/e82a9614-2b6b-4560-8a21-15a9bda19815)
Max:
![max](https://github.com/earthhistoryviz/tsconline/assets/104879321/76b4e4c9-6dac-4ff1-926c-f7de834f142b)
Min:
![min](https://github.com/earthhistoryviz/tsconline/assets/104879321/651a008c-67ee-492f-86ca-4d65e0465a9c)
Avg:
![Avg](https://github.com/earthhistoryviz/tsconline/assets/104879321/ebbff817-5ae3-46ba-92fe-8565a66bc906)
Combined Event:
RoC:
![RoC](https://github.com/earthhistoryviz/tsconline/assets/104879321/6386af39-202d-4104-a01f-78fb5041ecb6)

2024-07-01 01:49 UTC, paologum reviewed
some comments but overall great

also add a picture of the `chron` frequency being the same as well

2024-07-01 01:49 UTC, paologum commented on app/src/state/actions/column-actions.ts
>          windowStats = computeWindowStatisticsForDataPoints(
just wondering why you don't filter the age if it's lower or higher than the `baseStageAge` and `topStageAge`

also why do you `shift` and `pop`

2024-07-01 01:49 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          column.columnSpecificSettings.stepSize,
why no filter here either

2024-07-01 01:50 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          });
i'm also slightly confused as to why you filter here if we find the correct window later on

2024-07-01 02:17 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
>          windowStats = computeWindowStatisticsForDataPoints(
yeah it's just the way jar used. if I use filter in here, the result will be a lot different, and some case will even cause the jar to throw an error

2024-07-01 02:17 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +          column.columnSpecificSettings.stepSize,
same reason

2024-07-01 02:19 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +          column.columnSpecificSettings.stepSize,
actually for this one I need to double check, because when I was rewriting the functions, I didn't rebase, so I haven't really checked the situation for `chron` yet

2024-07-01 02:19 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +          });
if I don't filter here it , the range will be slightly different than the jar  I think it's bc when we're using the mid point to find the correct window it's not that accurate. Somehow, for events, they want it to be more accurate, so they give the function filtered data, while for other data points, they just give the function unfiltered data.

2024-07-01 02:20 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
>          windowStats = computeWindowStatisticsForDataPoints(
and the reason for using `shift `and `pop `is the same as ^

2024-07-01 20:28 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          });
interesting but alright, can you add a comment in the code saying that for future reference if anyone else visits this

2024-07-01 20:29 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          column.columnSpecificSettings.stepSize,
ok i would double check that before i review again then

2024-07-01 20:35 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +          });
sure

2024-07-02 22:02 UTC, JacquiFreeElectron commented
chron is the same as the jar now: 
![Screenshot 2024-07-02 at 5 55 25 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/04736540-79b6-4441-a9fa-46cf2020b457)

2024-07-03 17:18 UTC, paologum commented on app/src/state/actions/column-actions.ts
>          windowStats = computeWindowStatistics(
your comment says we don't filter data, but you are filtering?

2024-07-03 18:20 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
>          windowStats = computeWindowStatistics(
yeah actually I shouldn't filter

2024-07-04 15:45 UTC, paologum approved these changes
i'm assuming with the non-filter you changed/checked recently that chron is still the same and if not check that real quick before you merge

2024-07-04 18:11 UTC, merged