Tsc 381 add tests for google login login and signup
earthhistoryviz/tsconline pull request #130
Opened 2024-06-18 00:11 UTC by asivath

Migrated to vitest and started login route tests.

2024-06-19 06:59 UTC, paologum requested changes

2024-06-19 06:59 UTC, paologum commented on app/package.json
> +    "vitest": "^1.6.0"
do the root packages not get inherited?

2024-06-19 06:59 UTC, paologum commented on package.json
>      "clean": "yarn workspaces foreach -A --parallel run clean"
does `vitest run` have functionality to accept test names like jest did so you don't have to run all the tests?

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      spy.mockRestore();
does spy carry over ? isn't the scope only in this `it`?

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().message).toBe("Email sent");
should add checks that `sendEmail`, `createVerification` `createUser` and `findUser` are called once

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +  describe("/signup", () => {
should add a test for any missing field recaptchaToken and non-matching email regex email

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    });
can a recaptchaToken be 0 btw? if it can then a token of 0 might return invalid form, weird case that i don't think will happen though

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    });
i think to be robust you should also check to make sure that `checkRecaptchaToken` gets called once

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Recaptcha failed");
above

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +  describe("/signup", () => {
also super super robust but you should mock a situation where the database doesn't insert the user so that we know this function handles it correctly and throws an error and returns the proper status code

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.statusCode).toBe(400);
also check message

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.statusCode).toBe(409);
msg

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    it("should return 409 is user/pass user exists", async () => {
if ** right

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    it("should return 200 if successful is google users exists", async () => {
kinda confused with the test message, can you make it more clear

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    it("should return 200 if successful is google users exists", async () => {
also should add a test for if `userRow` isn't found then we create the entry in the database. make sure to look for `createUser` being called once and checking session for that. technically you might have to add the same code from `signup` to where the database doesn't insert because that code doesn't exist yet. similar test to the above comments also applies here for mocking the situation where the database doesn't insert correctly

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +
i would add the check just to be explicit since we aren't intentionally mocking here for it to make sure we call `compare` method once

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Account locked");
above

2024-06-19 06:59 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +
also for this and the other failures, i think it might be good to make sure the session isn't set properly or that `checkSession` fails

2024-06-19 06:59 UTC, paologum commented on server/src/login-routes.ts
> +    if (hashedPassword && (await compare(password, hashedPassword ?? ""))) {
do you need the `??`, shouldn't the types be happy if you checked for `hashedPassword` alr

2024-06-19 06:59 UTC, paologum commented on vite.config.ts
> +    include: ["server/__tests__/**.test.ts", "app/__tests__/**.test.ts"],
shared has tests

2024-06-19 11:21 UTC, asivath commented on app/package.json
> +    "vitest": "^1.6.0"
vitest works without this but ts can't get the types without this for some reason, there is potentially a fix with some of the workspace stuff they have but it didn't seem worth my time when this works

2024-06-19 11:23 UTC, asivath commented on package.json
>      "clean": "yarn workspaces foreach -A --parallel run clean"
you just need to specify a name so `yarn test util` would run all the util tests

2024-06-19 11:24 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      spy.mockRestore();
yes but it should only mock 0.0 for this `it` not the other ones

2024-06-19 12:41 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +    });
the token is actually some random string that the google api creates and gives to the frontend which then passes it to the backend where we use the token to retrieve the actual score

2024-06-19 12:52 UTC, asivath commented on server/src/login-routes.ts
> +    if (hashedPassword && (await compare(password, hashedPassword ?? ""))) {
i forgot about this it was to make jest happy but vitest handles it better

2024-06-19 14:00 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +    it("should return 200 if successful is google users exists", async () => {
not sure 100% what you mean but lmk if i should add something else

2024-06-19 18:15 UTC, paologum commented on package.json
>      "clean": "yarn workspaces foreach -A --parallel run clean"
can it also run like a specific test in `util`?

2024-06-19 18:16 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      spy.mockRestore();
wait but since we redeclare `const spy` everytime aren't they seperate `spy` instances?

2024-06-19 18:19 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    it("should return 200 if successful is google users exists", async () => {
```
    await createUser(newUser);
    const insertedUser = (await findUser({ email }))[0];
    if (!insertedUser) {
      throw new Error("User not inserted");
    }
```
^ signup route
should add code in google login that checks if the user was correctly made since this isn't in the googleLogin route
also should add a test for `googleLogin` and `signup` where the database doesn't create the correct entry (`findUser` returns `[]`)

then to just add an expects `findUser` and `createUser` are called once

2024-06-19 18:25 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    it("should return 200 if successful is google users exists", async () => {
ah ok i saw you added the fix, but for google user you check if `createUser` throws an Error but we should also keep it consistent with the sign up code above right and `findUser` ourselves then test that way?

2024-06-19 21:35 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      spy.mockRestore();
the spy variable itself is different but the module we mocked stays there. getting rid of the mockRestore causes other tests to start giving out 422. but honestly I should have done this the way I did the others and just use mockResolvedValueOnce.

2024-06-19 21:37 UTC, asivath commented on package.json
>      "clean": "yarn workspaces foreach -A --parallel run clean"
yea you can I'll add a command for that

2024-06-19 21:42 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +    it("should return 200 if successful is google users exists", async () => {
for consistency sake yeah

2024-06-19 21:50 UTC, asivath commented
on line 93 there is a commented out mock that suppresses the error messages thrown by the routes. idk if we want that because they can be kind of annoying to read through and unless u know that its supposed to throw errors it can also be unclear. I could also just use the silent mode for vitest but that would stop everything. wdyt?

2024-06-20 03:59 UTC, paologum commented
i think that you should just suppress the `console.errors` for these tests (uncomment that line) since it won't really be useful imo

2024-06-20 04:00 UTC, paologum approved these changes

2024-06-20 13:08 UTC, merged