Tsc 350 reformat chart page
earthhistoryviz/tsconline pull request #134
Opened 2024-06-20 23:34 UTC by jay-jhk-lee

added an options bar above the chart display.
added Zoom In, Zoom Out, reset transformation, Zoom fit, and download svg functionality.

https://github.com/earthhistoryviz/tsconline/assets/89719669/ce0d233f-6ce6-4c1b-8f47-814b8fbad1c0

2024-06-21 06:53 UTC, paologum commented
one comment based on what i saw on the demo, i think that control/cmd + should zoom in on where the cursor is, if it is within the bounds.

we can talk with aaron more about it tomorrow as well

2024-06-21 06:57 UTC, paologum commented
also i just realized that we can limit the panning to the image boundaries so it can't overreach the bounds, which might make panning possible now :D (the same way we display map points)

i do still like the scrolling, so we would still disable zooming on scroll.
we alternatively could have like a toggle button that toggles scrolling to zoom and scrolling to pan like the java.
because there are pros and cons to both so maybe functionality for both would be desirable

we can talk more about it tomorrow for sure.

2024-06-21 07:27 UTC, paologum requested changes
looks really good so far!

2024-06-21 07:27 UTC, paologum commented on app/src/Chart.tsx
> +    const wrapper = document.getElementsByClassName("react-transform-wrapper")[0].getBoundingClientRect();
is there a different way you can grab the wrapper? maybe assigning an `id`? because this `react-transform-wrapper` is used in map points

2024-06-21 07:27 UTC, paologum commented on app/src/Chart.tsx
> +    const wrapper = document.getElementsByClassName("react-transform-wrapper")[0].getBoundingClientRect();
also don't we have a ref to this `transformContainerRef`?

2024-06-21 07:27 UTC, paologum commented on app/src/Chart.tsx
> +    const id = open ? "simple-popover" : undefined;
is there a reason you need to conditionally load an `id`?

2024-06-21 07:27 UTC, paologum commented on app/src/Chart.tsx
> +        </Popover>
i feel like you can just put this in the tooltip, instead of them having to click it

2024-06-21 17:27 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +    const wrapper = document.getElementsByClassName("react-transform-wrapper")[0].getBoundingClientRect();
I cant access the function using the ref and I can't assign an id directly on the transform wrapper so I wrapped it in another div and used an id which works

2024-06-21 17:27 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +    const id = open ? "simple-popover" : undefined;
I'm not sure, I copied it from mui but it probably works without it

2024-06-21 17:50 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +        </Popover>
I couldn't find a way to wrap strings, so I used this but since then I found a workaround for tooltips

2024-06-21 19:03 UTC, paologum commented on app/src/Chart.tsx
> +        </Popover>
have you tried setting a hard coded width in css and do `white-space: wrap` and `overflow-x: hidden`

2024-06-21 19:03 UTC, paologum commented on app/src/Chart.tsx
> +    const id = open ? "simple-popover" : undefined;
yeah probably should take it out

2024-06-22 00:00 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +        </Popover>
I haven't tried it, but I figured out a different way that works

2024-06-22 00:42 UTC, jay-jhk-lee commented
for the zooming in to cursor using keyboard shortcuts, I've spent some time working on it and it's more complicated then I expected. For now, since I've completed the essential features, I'm happy with merging it as is and I've put the keyboard zoom in the backlog.

2024-06-22 18:48 UTC, paologum commented
you should add a demo of the pr changes you made

i'm assuming that they should have a download chart change name dialog (which also probably should be able to quickly click and press `Return`/`Enter` to bypass quickly) and also a pan/scroll toggle

2024-06-23 20:03 UTC, jay-jhk-lee commented
I've replaced the demo when I uploaded my new changes

2024-06-24 04:05 UTC, paologum requested changes
try this on different screen sizes, the fit to screen doesn't adjust for resizes


https://github.com/earthhistoryviz/tsconline/assets/89664317/55e10e4a-45d3-4fec-9e39-641155395c6a

2024-06-24 04:05 UTC, paologum commented on app/src/Chart.tsx
> +              limitToBounds={false}
why `false`? i think this should be `true`

2024-06-24 04:05 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +            if (!content || !wrapper) return;
change won't need this query

2024-06-24 04:05 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +          }}>
use `CustomTooltip`

2024-06-24 18:10 UTC, jay-jhk-lee commented
Can you reproduce the bug for the zoom fit? I'm not facing an issues with resizing on my end

2024-06-24 20:50 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +              limitToBounds={false}
There's a bug when setting this to true which I found a workaround for. I'll add a comment in the code explaining it, and lmk what you think. But it should work as expected with that workaround.

2024-06-24 20:52 UTC, jay-jhk-lee commented
Fixed the resize issue, I missed a step in my calculation

2024-06-24 20:53 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +    const wrapper = document.getElementById("chart-transform-wrapper")?.getBoundingClientRect();
That works

2024-06-24 20:54 UTC, jay-jhk-lee commented on app/src/ChartOptionsBar.tsx
> +          }}>
Custom tool tip takes in a string, so I can't use it with this approach

2024-06-25 01:07 UTC, jay-jhk-lee commented
reset and zoom fit works after resizing window

https://github.com/earthhistoryviz/tsconline/assets/89719669/298a412d-efc9-4939-ab0d-05228984e060

2024-06-25 18:57 UTC, paologum commented
i'm playing with the chart right now, and it should probably on smaller screens, start zoom fit.

right now it starts like this
![image](https://github.com/earthhistoryviz/tsconline/assets/89664317/8b13db52-3297-4321-9352-462cff5d300f)

2024-06-25 19:48 UTC, jay-jhk-lee commented
Good idea I'll set it to start on zoom fit. It looks like the java program does that too.
Yes, reset transformation mimics 1:1.

2024-06-25 20:21 UTC, jay-jhk-lee commented
chart starts fitted
https://github.com/earthhistoryviz/tsconline/assets/89719669/45b46a5b-b0e3-4314-b8a5-f1a4757c89d2

2024-06-25 21:49 UTC, paologum commented
is this supposed to be able to pan through horizontally scroll? or is it only supposed to pan by mouse click


https://github.com/earthhistoryviz/tsconline/assets/89664317/6af19afd-8898-47d2-b497-f08e77283471

2024-06-25 22:06 UTC, paologum requested changes
also for ref, depending which one gets merged first, you or me will need to check compatibility with light/dark mode (specifically for popup and option bar)

2024-06-25 22:06 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +            </div>
does this need to be in a `div` or can you just apply a `margin` to the `Switch`

2024-06-25 22:06 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +  };
if this is because of animation times being weird, shouldn't you make this a `setTimeout` `Promise` because toggling would have more time differential per system that might affect the correct bounds being calculated

2024-06-25 22:07 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +  };
you can also look into `toggle`

2024-06-27 19:40 UTC, paologum commented
![image](https://github.com/earthhistoryviz/tsconline/assets/89664317/7ecfb682-7b33-4a15-816e-3a873c87a7ed)

^ can't see Zoom on Scroll in dark mode

![image](https://github.com/earthhistoryviz/tsconline/assets/89664317/f7da1e3b-10ef-4e30-b622-1161b75dd200)

^should be white dropdown (use icon color)


https://github.com/earthhistoryviz/tsconline/assets/89664317/70d1fd7a-858a-4878-823c-0d95bb421fc1

hovering is white, making the line disappear on light mode

2024-06-27 19:45 UTC, paologum commented
![image](https://github.com/earthhistoryviz/tsconline/assets/89664317/56b7584b-0fd9-4809-8d3d-ab3be07a2988)

one more thing, can you make this color `divider`
if you use theme it's `theme.palette.divider`
if you use a mui component, you can just do `border=" 2px solid" borderColor="divider"` if you don't want to import `useTheme`

2024-06-27 19:57 UTC, paologum requested changes

2024-06-27 19:57 UTC, paologum commented on app/src/Chart.tsx
> +      }
i think i was wrong in my previous comment because even if you go below `minScale` or above `maxScale` you're always able to come back down. so i'm not sure if the `while` was for my comment but you may not need it unless that's for something else

2024-06-27 19:57 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +              console.log(container.instance.transformState);
log

2024-06-27 19:57 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +            }
same here unless this is something else, lmk

2024-06-27 19:57 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +            console.log(state.chartTab.resetMidX);
log

2024-06-27 19:57 UTC, paologum commented on app/src/settings_tabs/SaveSettings.tsx
> +          <TSCButton component="label" variant="text" sx={{ bgcolor: "button.main" }} type="submit">
just use `buttonType="primary"` so that we can uniformly change these instead of `sx={{ bgcolor: "button.main" }}`

2024-06-27 20:09 UTC, jay-jhk-lee commented on app/src/Chart.tsx
> +      }
You're right, they can always zoom back if there is a case where it goes out of bounds

2024-06-28 00:19 UTC, paologum requested changes
error on use

```
MUI: A component is changing the default checked state of an uncontrolled SwitchBase after being initialized. To suppress this warning opt to use a controlled SwitchBase. 
    at SwitchBase2 (http://localhost:5173/node_modules/.vite/deps/chunk-NRQIJTAX.js?v=b9aadb0b:131:5)
    at http://localhost:5173/node_modules/.vite/deps/chunk-QCPCZYPI.js?v=b9aadb0b:1567:50
    at span
    at http://localhost:5173/node_modules/.vite/deps/chunk-QCPCZYPI.js?v=b9aadb0b:1567:50
    at Switch2 (http://localhost:5173/node_modules/.vite/deps/chunk-NRQIJTAX.js?v=b9aadb0b:534:17)
    at div
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-QCPCZYPI.js?v=b9aadb0b:1567:50
    at Box3 (http://localhost:5173/node_modules/.vite/deps/chunk-XFO5PCNM.js?v=b9aadb0b:640:19)
    at div
    at OptionsButton (http://localhost:5173/src/ChartOptionsBar.tsx:67:35)
    at div
    at div
    at observerComponent (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=b9aadb0b:313:12)
    at div
    at div
    at observerComponent (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=b9aadb0b:313:12)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/chunk-DXNQRIOC.js?v=b9aadb0b:3646:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/chunk-DXNQRIOC.js?v=b9aadb0b:4151:5)
    at RtlProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XFO5PCNM.js?v=b9aadb0b:1017:5)
    at ThemeProvider (http://localhost:5173/node_modules/.vite/deps/chunk-XFO5PCNM.js?v=b9aadb0b:966:5)
    at ThemeProvider2 (http://localhost:5173/node_modules/.vite/deps/chunk-XFO5PCNM.js?v=b9aadb0b:1056:5)
    at ThemeProvider (http://localhost:5173/node_modules/.vite/deps/chunk-JPMICJZ5.js?v=b9aadb0b:298:12)
    at StyledEngineProvider (http://localhost:5173/node_modules/.vite/deps/chunk-QCPCZYPI.js?v=b9aadb0b:2328:5)
    at observerComponent (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=b9aadb0b:313:12)
    at Router (http://localhost:5173/node_modules/.vite/deps/chunk-DXNQRIOC.js?v=b9aadb0b:4094:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=b9aadb0b:552:5)
    at GoogleOAuthProvider (http://localhost:5173/node_modules/.vite/deps/@react-oauth_google.js?v=b9aadb0b:42:32)
overrideMethod @ console.js:273
(anonymous) @ chunk-QDV2L4SL.js?v=b9aadb0b:481
commitHookEffectListMount @ chunk-7QBOF2PQ.js?v=b9aadb0b:16936
commitPassiveMountOnFiber @ chunk-7QBOF2PQ.js?v=b9aadb0b:18184
commitPassiveMountEffects_complete @ chunk-7QBOF2PQ.js?v=b9aadb0b:18157
commitPassiveMountEffects_begin @ chunk-7QBOF2PQ.js?v=b9aadb0b:18147
commitPassiveMountEffects @ chunk-7QBOF2PQ.js?v=b9aadb0b:18137
flushPassiveEffectsImpl @ chunk-7QBOF2PQ.js?v=b9aadb0b:19518
flushPassiveEffects @ chunk-7QBOF2PQ.js?v=b9aadb0b:19475
commitRootImpl @ chunk-7QBOF2PQ.js?v=b9aadb0b:19444
commitRoot @ chunk-7QBOF2PQ.js?v=b9aadb0b:19305
performSyncWorkOnRoot @ chunk-7QBOF2PQ.js?v=b9aadb0b:18923
flushSyncCallbacks @ chunk-7QBOF2PQ.js?v=b9aadb0b:9135
(anonymous) @ chunk-7QBOF2PQ.js?v=b9aadb0b:18655
Show 14 more frames
Show lessUnderstand this error
```

2024-06-28 00:19 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +                }}
you should overload all of these for `variant="standard"` in `theme.ts`
i reference it in the comment with the video

2024-06-28 01:34 UTC, paologum requested changes

2024-06-28 01:34 UTC, paologum commented on app/src/theme.ts
> +          ":after": { borderBottomColor: "#FF9900" }
this should be for `variant=standard`

2024-06-28 01:34 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +                    sx={{ ":after": { borderBottomColor: "orange" } }}
this should also change

2024-06-28 01:47 UTC, paologum requested changes

2024-06-28 01:47 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +                    sx={{ ":after": { borderBottomColor: "orange" } }}
remove

2024-06-28 04:41 UTC, merged