added tests for verifyEmail, resendVerifyEmail, sendForgotPasswordEmail
earthhistoryviz/tsconline pull request #135
Opened 2024-06-22 17:16 UTC by asivath

2024-06-22 19:16 UTC, paologum requested changes

2024-06-22 19:16 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email already verified");
if this happens, shouldn't it delete the verification row as well?

2024-06-22 19:16 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email service not configured");
session check

2024-06-22 19:16 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().message).toBe("Email sent");
delete the verification row here like above?

2024-06-22 19:16 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email service not configured");
check session

2024-06-22 19:16 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(emailSpy).not.toHaveBeenCalled();
i feel like for these local spies watching local methods, you could create one for this `describe` and reset them in an `afterEach` method, that way you're not instantiating them every time and also can `expect.not.toHaveBeenCalled()` easily. because technically we should be consistent if we are starting `not.toHavBeenCalled` here for other tests

2024-06-22 21:27 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +          expiresAt: expect.any(String),
i didn't do that because I thought that verifying it's an actual date string would be verifying the date object did not fail. one thing I could to check the logic in the route is to see whether it actually added an hour or whatever to the current time.

2024-06-22 21:29 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email already verified");
the reason I didn't delete in the route is so that I could tell the user that they have already verified their email. this token will eventually get cleaned up every week by the interval thing.

2024-06-22 21:29 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().message).toBe("Email sent");
same logic as above

2024-06-22 21:39 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email already verified");
isn't `emailVerified` kept in the `users` table though?

2024-06-22 21:48 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email already verified");
yeah but this route identifies users by their tokens

2024-06-22 22:59 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      expect(emailSpy).not.toHaveBeenCalled();
for the not.toHaveBeenCalled I wanted it specifically for the things that return 200 even though the operation was technically not successful (like no username/email existing) since it's important those functions are not called for security reasons.

2024-06-23 19:39 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(response.json().error).toBe("Email already verified");
ok then i would add a check to make sure it doesn't get called here

2024-06-24 03:37 UTC, paologum approved these changes

2024-06-24 04:06 UTC, merged