added tests for forgotPassword, changeEmail, accountRecovery
earthhistoryviz/tsconline pull request #137
Opened 2024-06-25 02:30 UTC by asivath

2024-06-25 18:53 UTC, paologum requested changes

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    });
i feel like you should `expect` a `findVerification` is called with the `token` passed in here

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    });
also add test for if `reason !== password)`

the code also confuses me a little
```
const verificationRow = (await findVerification({ token }))[0];
    if (!verificationRow || verificationRow.reason !== "password") {
      reply.status(404).send({ error: "Password reset token not found" });
      return;
    }
    const { userId, expiresAt, reason } = verificationRow;
    const expiresAtDate = new Date(expiresAt);
    if (expiresAtDate < new Date() || reason !== "password") {
      await deleteVerification({ token, reason: "password" });
      reply.status(401).send({ error: "Password reset token expired or invalid" });
      return;
    }
```
don't you check `reason` twice

also one of them calls `deleteVerification` while the other doesn't

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    });
i think you `expect(findUser)` here just for clarity and `expect` `updateUser` and `deleteVerification`

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +        headers: { cookie: `loginSession=${cookieHeader}` }
might be better to make `header` a var

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      vi.mocked(databaseModule.findUser).mockResolvedValueOnce([]);
fails feels different than this test, probably `user doesn't exist`

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(checkSession(response.headers["set-cookie"] as string)).toBe(false);
i would `expect` it to be called just to be super robust that it fails there since we don't really check an error message that was thrown

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +
same with these

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +
ope and here

2024-06-25 18:53 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +
also should have one for if the reason is wrong

2024-06-26 20:47 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +    });
yeah the second one shouldn't be there

2024-06-28 01:46 UTC, paologum approved these changes

2024-06-28 21:58 UTC, merged