finished adding tests for login routes
earthhistoryviz/tsconline pull request #145
Opened 2024-06-29 01:29 UTC by asivath

2024-06-30 00:36 UTC, paologum requested changes
just some small things

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      expect(checkSession(response.headers["set-cookie"] as string)).toBe(false);
wait maybe i don't understand how this works but since they should be logged in should this be true? or is this only true when we want to set the cookie on the app side for when they successfully login for the first time

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +        expect(response.json().message).toBe("Username changed");
can you also listen to the `delete()` session method to make sure that gets called?

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      });
same here for passwords if you can

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      });
should check that `loadFileMetadata` gets called still
and `rm` should still get checked with the same params as the successful test below
and session delete

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +    });
also expect the session to delete

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      });
session delete here too

2024-06-30 00:36 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +  });
delete here too

2024-06-30 13:46 UTC, asivath commented on server/__tests__/login-routes.test.ts
> +      expect(checkSession(response.headers["set-cookie"] as string)).toBe(false);
yes only sent on routes that give a user a new session

2024-07-01 23:06 UTC, paologum requested changes

2024-07-01 23:06 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      });
one last thing is since we do check that we delete session now, we probably should check it doesn't delete session on failures

2024-07-01 23:06 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      });
same

2024-07-01 23:06 UTC, paologum commented on server/__tests__/login-routes.test.ts
> +      });
here too

2024-07-03 17:15 UTC, paologum approved these changes

2024-07-03 23:14 UTC, merged