TSC-145-Top-Base-Age
earthhistoryviz/tsconline pull request #15
Opened 2024-02-16 16:31 UTC by SejalKumar03

Connected drop down to text (correctly working for base age, not the correct age value for top age), moved inline method to routes.ts, moved useEffect, and moved type and assert

2024-02-16 16:50 UTC, SejalKumar03 commented
![Screenshot 2024-02-16 114932](https://github.com/earthhistoryviz/tsconline/assets/119654886/2b378245-a808-4c78-adb3-50b2110e38aa)

2024-02-16 22:22 UTC, paologum requested changes

2024-02-16 22:22 UTC, paologum commented on app/src/state/initialize.ts
> +  }
the above should be generalized to be done in `fetchTimeScaleData`

2024-02-16 22:22 UTC, paologum commented on app/src/state/initialize.ts
> +  }
Is there a reason you are returning here?

2024-02-16 22:22 UTC, paologum commented on app/src/state/state.ts
> +  timescaleData: [],
you should make two arrays, one with top stage ages and base stage ages

2024-02-16 22:22 UTC, paologum commented on app/src/state/initialize.ts
> -  actions.fetchPresets()
just read the reset and you do make a `actions.fetchTimeScaleData` but should do everything to do with that (setting the arrays and such) in that method

2024-02-16 22:22 UTC, paologum commented on server/src/routes.ts
> +    timescaleData = timescaleData.filter(item => item.key && item.key !== 'Stage' && item.key !== 'TOP');
you shouldn't filter out these keys and correctly parse them into the proper arrays on the app side

2024-02-16 22:22 UTC, paologum commented on server/tsconfig.json
> +    // "declaration": false
remove comment

2024-02-16 22:22 UTC, paologum commented on app/src/state/state.ts
> +export interface TimescaleItem {
ah i just read that you use the same type in `shared`.

instead of defining a new type, import `TimescaleItem` from `shared`

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +  }, []);
you shouldn't set these using `useEffect` also you shouldn't call `intialize` here

`initialize` runs once at the beginning of the app so if you call `fetchTimescale` in `initialize` then it should set the timescale appropriately

this is because `timescale` never updates, so it should never be updated after the first time

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +  const [timescaleData, setTimescaleData] = useState<TimescaleItem[]>([]);
you define `timescaleData` in here and again in `state.ts`

definitely keep the one in `state` and deprecate this

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +  const [previousValues, setPreviousValues] = useState<Record<string, number | null>>({});
instead of using previous values reference my `state.ts` comments about creating two arrays `GeologicalTopStageAges` and `GeologicalBaseStageAges` or however you want to name them that distinctly separated them and classifies them.

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +  const [previousValues, setPreviousValues] = useState<Record<string, number | null>>({});
i wouldn't use `previousValues` and `timescaleData` since that seems very ambiguous to any other code readers

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +            const selectedAge = previousValue !== undefined && previousValue !== null ? previousValue.toString() : '0.000';
if you properly parse the required values in `fetchTimescale` in `initialize` then you should have two arrays that have a key and proper age which would mean you wouldn't need these exceptions and can just do `actions.setSelectedTopStage...` and the such

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +                {item.key} ({previousValues[item.key] !== null ? previousValues[item.key] : '0.000'} Ma)
same as the last comment

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +          style={{ marginBottom: '10px', width: '100%' }}
could you move this to a css file?

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +          style={{ marginBottom: '20px', width: '100%' }}
also move this to a css file?

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +            actions.setBaseStageAge(isNaN(parseInt(selectedAge)) ? 0 : parseInt(selectedAge));
this corresponds to the last top stage comments i had

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +            actions.setBaseStageAge(isNaN(parseInt(selectedAge)) ? 0 : parseInt(selectedAge));
you will also need to check if the age makes sense i.e `BaseStageAge > TopStageAge`

2024-02-16 22:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +            actions.setTopStageAge(isNaN(parseFloat(selectedAge)) ? 0 : parseFloat(selectedAge));
you will also need to check if the age makes sense i.e `BaseStageAge > TopStageAge`

2024-02-16 22:22 UTC, paologum commented on app/src/state/actions/GeneralActions.ts
> +export const setSelectedTopStage = action("setSelectedTopStage", (key: string) => {
if you change to `BaseStageKey` or `TopStageKey` then change/deprecate appropriately these actions and the ones below

2024-02-16 22:22 UTC, paologum commented on app/src/state/state.ts
> +export interface TimescaleItem {
i might have commented this already but use the export of this from `shared`

2024-02-16 22:22 UTC, paologum commented on app/src/state/state.ts
> +    selectedStage: string;
is this used for anything?

2024-02-16 22:32 UTC, paologum requested changes

2024-02-16 22:32 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +// }
remove this

2024-02-16 22:32 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +import { TimescaleItem } from '../state/state';
also import this from `shared` not from `state`

2024-02-21 02:59 UTC, SejalKumar03 commented on app/src/state/initialize.ts
> +  }
If I don't return, it's not letting me use the variables under useEffect in Time.tsx. But you've also told me a lot to get rid of useEffect since you don't need it but when I do that and I look at the console, it turns into an infinite loop where everything keeps on loading. And I don't know how to fix that.

2024-02-21 02:59 UTC, SejalKumar03 commented on server/src/index.ts
> +  let chartrequest;
I compared this section of code to the main and I think I'm supposed to replace this part of the code:
server.post('/charts', async (request, reply) => {
  // const key = Buffer.from('016481d57e032c18f750919bcd7dba2e', 'hex');
  // const iv = Buffer.from('2e918edf00c37c9c722512e35cf498a4', 'hex');
  // console.log('key: ', key);
  // console.log('iv: ', iv);
  // readAndDecryptFile('assets/datapacks/TimeTree of Life GTS2020.dpk', key, iv);

  let chartrequest;
  try {
    chartrequest = JSON.parse(request.body as string);
    assertChartRequest(chartrequest);
  } catch (e: any) {
    console.log('ERROR: chart request is not valid.  Request was: ', chartrequest, '.  Error was: ', e);
    reply.send({ error: 'ERROR: chart request is not valid.  Error was: '+e.toString() });
    return;
  }

  // Compute the paths: chart directory, chart file, settings file, and URL equivalent for chart
  const hash = md5(chartrequest.settings + chartrequest.datapacks.join(','));
  const chartdir_urlpath = '/public/charts/'+hash;
  const chart_urlpath = chartdir_urlpath+ '/chart.pdf';

  const chartdir_filepath = chartdir_urlpath.slice(1); // no leading slash
  const chart_filepath = chart_urlpath.slice(1);
  const settings_filepath = chartdir_filepath + '/settings.tsc';

  // If this setting already has a chart, just return that
  try {
    await stat(chart_filepath);
    console.log('Request for chart that already exists (hash:',hash,'.  Returning cached version');
    reply.send({ chartpath: chart_urlpath }); // send the browser back the URL equivalent...
    return;
  } catch(e: any) { 
    // Doesn't exist, so make one
    console.log('Request for chart', chart_urlpath, ': chart does not exist, creating...');
  }

  // Create the directory and save the settings there for java:
  try {
    await mkdirp(chartdir_filepath);
    await writeFile(settings_filepath, chartrequest.settings);
    console.log('Successfully created and saved chart settings at',settings_filepath);
  } catch(e: any) {
    console.log('ERROR: failed to save settings at',settings_filepath,'  Error was:', e);
    reply.send({ error: 'ERROR: failed to save settings' });
    return;
  }
  for (const datapack of chartrequest.datapacks) {
    if (!assetconfigs.activeDatapacks.includes(datapack)) {
      console.log('ERROR: datapack: ',datapack,' is not included in activeDatapacks')
      console.log('assetconfig.activeDatapacks:', assetconfigs.activeDatapacks)
      console.log('chartrequest.datapacks: ', chartrequest.datapacks)
      reply.send({ error: 'ERROR: failed to load datapacks' });
      return;
    }
  }


  // Call the Java monster...
  //const jarArgs: string[] = ['xvfb-run', '-jar', './jar/TSC.jar', '-node', '-s', `../files/${title}settings.tsc`, '-ss', `../files/${title}settings.tsc`, '-d', `../files/${title}datapack.txt`, '-o', `../files/${title}save.pdf`];
  //const jarArgs: string[] = ['-jar', './jar/TSC.jar', '-d', `./files/${title}datapack.txt`, '-s', `./files/${title}settings.tsc`];
  const cmd = `java -Xmx2048m -jar ${assetconfigs.activeJar} -node `
    // Add settings:
    + `-s ${settings_filepath} -ss ${settings_filepath} ` 
    // Add datapacks:
    + `-d ${chartrequest.datapacks} `
    // Tell it where to save chart
    + `-o ${chart_filepath} `;

  
  // Exec Java command and send final reply to browser
  await new Promise<void>((resolve, _reject) => {
    console.log('Calling Java: ', cmd);
    exec(cmd, function (error, stdout, stderror) {
      console.log('Java finished, sending reply to browser');
      console.log("Java error param: " + error);
      console.log("Java stdout: " + stdout.toString());
      console.log("Java stderr: " + stderror.toString());
      console.log('Sending reply to browser: ', { chartpath: chart_urlpath });
      reply.send({ chartpath: chart_urlpath });
      resolve();
    });
  });

});

With 
// generates chart and sends to proper directory
// will return url chart path and hash that was generated for it
server.post<{ Params: { usecache: string, useSuggestedAge: string } }>(
  "/charts/:usecache/:useSuggestedAge",
  routes.fetchChart
);

2024-02-22 04:55 UTC, paologum commented on server/src/index.ts
> +  let chartrequest;
yes that's correct :D

2024-02-22 04:59 UTC, paologum commented on app/src/state/initialize.ts
> +  }
you're not supposed to actually return values, you should be changing the state itself. are you completely getting rid of `useEffect`? it should have everything in the `useEffect` hook you have now in the `initialize.ts` basically (only should be a method call the `fetchTimeScaleData`

2024-02-22 05:00 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +  }, []);
reference last reply

2024-02-22 05:22 UTC, paologum requested changes

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
>      fetchData();
fetchData should be defined in `GeneralActions.ts` and `GeologicalTopStageAges` and `GeologicalBaseStageAges` should be in the state, not used as a hook here

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +import { fetchTimescaleDataAction } from "../state/actions";
if you use actions you shouldn't import them straight from actions
call context
`{state, actions} = useContext(context)`

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +          style={{ marginBottom: '20px', width: '100%' }} // Not working
you will have to target it like `.MuiTextField-root.[class-name-here]` in the css file

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +          value={state.settings.baseStageKey ? state.settings.baseStageKey : state.settings.baseStageAge.toString()}
i think we always want this to be a number so keep this to just `state.settings.baseStageAge.toString()` and make sure whenever you change the `baseStageKey` it changes accordingly. Additionally if the user decides to change the text field itself it should set the `baseStageAgeKey` to `N/A` since at that point it's the user's age and not related to the displayed key

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +          style={{ marginBottom: '20px', width: '100%' }} // Not working
same `.MuiTextField.[class-name]`

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +          style={{ marginBottom: "20px", width: "100%" }} // Not working
above

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +            // marginTop: "10px",
remove these

2024-02-22 05:22 UTC, paologum commented on app/src/state/actions/GeneralActions.ts
> +    return data;
instead of returning `data` you do the stuff that you did in the `useEffect` hook above should all be moved here and then this method called in `initialize.ts`

this shouldn't cause an infinite loop

2024-02-22 05:22 UTC, paologum commented on app/src/state/actions/GeneralActions.ts
> +    return { GeologicalBaseStageAges: [], GeologicalTopStageAges: [], loading: false };
no return as per above

2024-02-22 05:22 UTC, paologum commented on app/src/state/initialize.ts
> +// import fetchTimescaleData from "./TimeParser"
remove

2024-02-22 05:22 UTC, paologum commented on app/src/state/initialize.ts
> +    actions.fetchTimescaleDataAction();
ok this is good i didn't see this before but if you take the `useEffect` variables and insert them into this function `actions.fetchTimescaleDataAction` you should be good and no infinite loop occurs.

big thing is you want to change the stages on the `state` not through `useState` within the component

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +// import {MuiColorInput} from "mui-color-input";
you need to uncomment this

if it's causing problems do `yarn add mui-color-input` in `app`

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +                    {/* <MuiColorInput value={fontOpts.color} size="small" label="Color" format="hex" onChange={handleColor}
above

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
>  import { initialize } from "../state/initialize";
remove

2024-02-22 05:22 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +  const [GeologicalBaseStageAges, setGeologicalBaseStageAges] = useState<TimescaleItem[]>([]);
these are defined in state so use the hook `{state, actions} = useContext(context)` to access them `state.GeologicalTopStageAges`

2024-02-22 05:22 UTC, paologum commented on app/src/state/state.ts
> +  GeologicalBaseStageAges: TimescaleItem[];
can you make the first letter lowercase to keep in format with everything else

2024-02-22 05:22 UTC, paologum commented on server/src/routes.ts
> +    reply.send({ GeologicalTopStageAges, GeologicalBaseStageAges });
if both geological stages are the same you can just send one and process it on the other side

2024-02-22 05:22 UTC, paologum commented on shared/src/index.ts
> +export function assertTimescale(val: any): asserts val is TimescaleItem {
function name should be `assertTimescaleItem`

2024-02-22 05:22 UTC, paologum commented on app/src/state/TimeParser.ts
> +      return { GeologicalTopStageAges, GeologicalBaseStageAges, loading: false };
you shouldn't need `loading` once you implement everything to not do `useEffect`

2024-02-22 05:26 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
>      fetchData();
you do define a `fetchTimescaleDataAction` so just move these items into that and don't use `useEffect`

2024-02-25 18:04 UTC, closed without merging