Tsc 424 event search
earthhistoryviz/tsconline pull request #152
Opened 2024-07-03 21:29 UTC by jay-jhk-lee

Added event search functionality.
Added "in context" functionality.
notes:
- state holds list of added events so that if multiple events are added and one (or more) is removed, then the time interval goes back to the last highest/lowest ages added.
- this list only persists on the search page and is removed on tab change. This is to reduce possible confusion on changing time intervals when removing events on search page after leaving and returning.
- the "add to chart" checkbox for an event resets on search change or tab change.
- unchecking "add to chart" resets the "on" state of the parents to before toggling.

https://github.com/earthhistoryviz/tsconline/assets/89719669/5ef82396-087c-4447-8669-58057b7d0628

https://github.com/earthhistoryviz/tsconline/assets/89719669/e8e9a2ed-5d17-4a9b-9ccf-139334856e16

2024-07-04 21:21 UTC, paologum commented
this is my comments from just watching the video

so we are not going to let them select multiple different "critters" or events to generate?
you didn't really show it in the demo but in your description you said that it'll "reset the add to chart" when they search for another event. why should they not be able to search different ones?

2024-07-04 22:53 UTC, paologum requested changes
some small things but nice!

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +      onClick={() => {
to be more deliberate, i think you should make the handler function `onChange`

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +          if ("age" in info) {
probably also assert that `age` is what you want it to be with a regex

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Search.tsx
> +  const count = useRef(0);
why `useRef` instead of `useState`

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Search.tsx
> +  function columnPath(name: string): string[] {
i would call this `makeColumnPath` since `columnPath` is vague

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Search.tsx
> +      if (columnInfo.editName.toLowerCase().includes(state.settingsTabs.eventSearchTerm)) {
`state.settingsTabs.eventSearchTerm.toLowercase()`?

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Search.tsx
> +            if (subInfo.label!.toLowerCase().includes(state.settingsTabs.eventSearchTerm)) {
`state.settingsTabs.eventSearchTerm.toLowercase()`?

2024-07-04 22:53 UTC, paologum commented on app/src/settings_tabs/Search.tsx
> +          }}
same here with `onChange`

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +export const InsertEventInContextTopList = action((term: { key: string; age: number }, unit: string) => {
can you camel case this

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    }
instead of an extra if statement `index === prevLength`, you can just `return` after you splice and always push at the end

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +export const InsertEventInContextBaseList = action((term: { key: string; age: number }, unit: string) => {
camelCase

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
same here

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
if you are already returning, you don't need to `else` just for less indentation to promote readability

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
same

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
you should break to prevent more iterations that are unecessary

2024-07-04 22:53 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
same

2024-07-04 23:09 UTC, jay-jhk-lee commented
The "reset add to chart" only refers to the checkbox, not the adding of the event itself. The user can add as many events as they want.

2024-07-04 23:29 UTC, jay-jhk-lee commented on app/src/settings_tabs/Search.tsx
> +  const count = useRef(0);
Using state causes the site to crash because it causes a re-render on every increment.

2024-07-06 16:08 UTC, paologum requested changes

2024-07-06 16:08 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +});
because we reset the event context wouldn't we want to reset the `ageBeforeContext`?

i also think from a design perspective when we allow the user to center a column in the future in the second column, it seems odd that we allow them to revert back to the context. I don't personally think they should be able to revert because it creates unneeded remembering of state. I could see this being implemented in a larger undo function that remembers events using like preactions so they could revert, but the manual way we reset the `ageBeforeContext` seems unecessary. I look at it as the same way we allow manual top and base age changes, which we don't allow undos/resets on. It's just a further of that which makes it feel weird having memory for this but not that

2024-07-07 19:50 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +});
I agree with your comment as we've discussed in the meeting on Friday. I'm cleaning up all of the remembering stuff on a different branch, which is almost done and will be up for a pr soon. I personally think we can close this pr and the event search can be implemented through the other branch, let me know what you think.

2024-07-08 23:21 UTC, closed without merging