TSC-199-font-options
earthhistoryviz/tsconline pull request #16
Opened 2024-02-16 16:45 UTC by lbostre

![fontOptions](https://github.com/earthhistoryviz/tsconline/assets/29764221/01757d03-f511-4d52-8fcb-1917447255d8)
- finished frontend for the font options popup
- allows user to change options for the font

2024-02-16 21:41 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +                <TextField sx={{width: "60px", marginRight: "10px", minWidth:"60px"}} id="FontSizeInput"label="Size" variant="outlined"
you define both an id for the css and sx? probably pick one or the other or add a comment saying that you have to do both of these things.

however you set `min-width` in css and here so at least choose one or the other there. preferably all within `FontSizeInput` if possible

2024-02-17 18:29 UTC, jay-jhk-lee commented on server/src/parse-datapacks.ts
> +    fontsInfo: JSON.parse(JSON.stringify(defaultFontsInfo)),
Can you double check if you need to stringify and parse? if defaultFontsInfo is already a json object, I think it shouldn't be necessary

2024-02-17 19:07 UTC, paologum commented on server/src/parse-datapacks.ts
> +    fontsInfo: JSON.parse(JSON.stringify(defaultFontsInfo)),
however if you know for a fact it won't change the shared object then you can remove it

2024-02-18 14:11 UTC, lbostre commented on app/src/SettingsTabs/FontMenu.tsx
> +                <TextField sx={{width: "60px", marginRight: "10px", minWidth:"60px"}} id="FontSizeInput"label="Size" variant="outlined"
CSS styling doesn't work on this specific component for some reason, so I removed the CSS class and kept the inline styling. I also added a comment signifying that only inline styling works on this component as well.

2024-02-19 01:00 UTC, paologum requested changes
I found something while playing around with the viewbox and you can see that the right examples of the sample text are coming out of the dialog box. You can either fix this with  switching over earlier to the flex-wrap.

<img width="524" alt="Screenshot 2024-02-18 at 7 25 22 PM" src="https://github.com/earthhistoryviz/tsconline/assets/89664317/78230e0d-1e1a-483c-8a2d-b761236fd5af">

2024-02-19 02:03 UTC, lbostre commented on app/src/SettingsTabs/FontMenu.tsx
> +          sx={{ width: "60px", marginRight: "10px", minWidth: "60px" }}
Applied and pushed!

2024-02-19 02:45 UTC, paologum requested changes

2024-02-19 02:45 UTC, paologum commented on app/src/SettingsTabs/FontMenu.css
> +.MuiTextField-root.font-size-container { width: 60px; margin-right: 10px; min-width: 60px; }
little picky here but can you format this like the rest of the id classes in the css file 😃

2024-02-19 20:34 UTC, merged