error message fix
earthhistoryviz/tsconline pull request #161
Opened 2024-07-06 20:21 UTC by JacquiFreeElectron

![Uploading Screenshot 2024-07-06 at 1.19.03 PM.png…]()

2024-07-07 02:37 UTC, paologum commented
from the demo i see, it shouldn't pop up with the snackbar component as an error. it should be what we talked about when you go to the `/verify` and enter an incorrect email

![image](https://github.com/earthhistoryviz/tsconline/assets/89664317/58646a4a-7875-49b3-aa21-6819a9d853ad)

2024-07-07 09:41 UTC, JacquiFreeElectron commented
<img width="601" alt="Screenshot 2024-07-07 at 2 39 21 AM" src="https://github.com/earthhistoryviz/tsconline/assets/104879321/5e0cfddb-7a9b-41cd-aee9-f70487ceccc5">
The error will disappear when the user click anywhere or hover over it

2024-07-07 09:48 UTC, JacquiFreeElectron commented
btw I think the style in `/verify` depends on what browser we use (it looks different when I use Safari), which means it's rendered/offered by the browser(or some other API), I couldn't find how they do the styling, so I just use a tooltip to mimic a popup dialog

2024-07-08 17:47 UTC, paologum requested changes

2024-07-08 17:47 UTC, paologum commented on app/src/components/TSCError.tsx
> +  }
instead of sort rewiring in a hard coded sort of way across components, i would create a wrapper of a text field and make this a `CustomErrorPopoverTextField` sort of deal, that way we can use this for other things as well

2024-07-08 17:48 UTC, paologum commented on app/src/components/TSCError.tsx
> +  }
which would make it easier to attach an `AnchorEl` since the component is available

2024-07-08 17:48 UTC, paologum commented on app/src/components/TSCError.tsx
> +  }
also 1 more thing, we want this for top age too. if it's lower than the base age it should have one, which should make this refactor make more sense

2024-07-10 01:06 UTC, paologum commented on app/src/components/TSCError.tsx
> +  }
also, i misspoke the error should be if top age is higher than base age*

2024-07-11 07:31 UTC, JacquiFreeElectron commented
how it looks now:
https://github.com/earthhistoryviz/tsconline/assets/104879321/abdb2a81-ea60-43fb-9571-99431fea62bb

2024-07-11 17:55 UTC, JacquiFreeElectron commented
new demo: 

https://github.com/earthhistoryviz/tsconline/assets/104879321/cc0058b6-5530-405e-a416-73c1f6a401ce

2024-07-11 20:22 UTC, paologum commented
from the demo, it probably should still show the error if `isNan` so that it doesn't go away when it is blank and they think it is fixed. also just in case, i could see this happening is that they are on a different tab and they click generate , they might not know what happened if they aren't on the time tab so you should add the error message that gets pushed on invalid base/top age
except this time it should just be a general one of the nature "Is bad range"

2024-07-11 20:32 UTC, paologum requested changes

2024-07-11 20:32 UTC, paologum commented on app/src/components/CustomErrorPopoverTextField.tsx
> +    const anchorElement = document.getElementById(anchorElementID);
we don't wanna query here when we are using javascript with the elements, instead pass in the actual ref of the component.

2024-07-11 20:32 UTC, paologum commented on app/src/settings_tabs/Time.tsx
> +  }
use `removeError`, you don't want to change state out of an action

2024-07-12 01:58 UTC, JacquiFreeElectron commented
new demo:

https://github.com/user-attachments/assets/2434c200-52ab-4a74-9e8d-fc8ed5d59d6b

2024-07-12 05:01 UTC, paologum commented on app/src/components/CustomErrorPopoverTextField.tsx
> +    }
i'm confused how this works, your demo has clickaway remove the error, but here in the code it seems to me like it would ignore clickaway?

just wondering how this works in the demo

2024-07-12 05:23 UTC, JacquiFreeElectron commented on app/src/components/CustomErrorPopoverTextField.tsx
> +    }
I honestly don't know, I didn't even notice it bc I was directly using it from the original code, didn't change anything. Probably it won't make a difference if I remove this?

2024-07-12 05:29 UTC, JacquiFreeElectron commented on app/src/components/CustomErrorPopoverTextField.tsx
> +    }
Just tried, I can totally remove this

2024-07-12 05:41 UTC, paologum approved these changes

2024-07-12 05:56 UTC, merged