Background color frontend in column settings
earthhistoryviz/tsconline pull request #17
Opened 2024-02-18 23:04 UTC by rohnach29

![Screenshot 2024-02-18 at 6 04 05 PM](https://github.com/earthhistoryviz/tsconline/assets/112187753/99cad8b8-7a28-491f-b649-44751f751935)

2024-02-19 01:32 UTC, paologum requested changes

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +            <FormLabel id="color-label" style={{ color: 'black', marginTop: '3px', margin: '5px' }}>Background Color:</FormLabel>
add this to css

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +            <Button color="secondary" variant="contained" onClick={handleOpen} style={{backgroundColor: currentColor, width: '60px', height: '30px', margin: '0 10px', marginTop: '1px'}}></Button>
add this to css

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +                    <div style={{ display: 'grid', placeItems: 'center' }}>
add this to css

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +                                            styles={styles} onAccept={() => {handleCurrentChange(selectedColor); handleClose();}}
change styles to just use css

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
>                                  // value={this.state.color} - for controlled component
not part of your task in terms of the commits but could you remove this

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +                {state.settingsTabs.columnSelected && <EditNameField/>}
change this to `state.settingsTabs.columnSelected && (...<EditNameFIeld/>....<FontMenu/>... etc)`

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +      };
add this to css

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +                                            styles={styles} onAccept={() => {handleCurrentChange(selectedColor); handleClose();}}
if this is hard to change to css, just leave it because i have a new task for making a general colorpicker given a mockup i found.

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +                            <Grid item xs={12} style={{ display: 'flex', justifyContent: 'center'}}>
add this to css

2024-02-19 01:32 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +            <Button color="secondary" variant="contained" onClick={handleOpen} style={{backgroundColor: currentColor, width: '60px', height: '30px', margin: '0 10px', marginTop: '1px'}}></Button>
leave currentColor since it's dynamic ofc

2024-02-20 06:13 UTC, paologum requested changes

2024-02-20 06:13 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +      };
remove this now

2024-02-20 06:13 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +};
remove this

2024-02-20 06:13 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
remove the styles object above, for some reason it doesn't let me comment on that line 😢

2024-02-22 17:16 UTC, paologum approved these changes

2024-02-22 18:37 UTC, jay-jhk-lee submitted a review, later dismissed
Looks Good!

2024-02-22 18:41 UTC, jay-jhk-lee reviewed
Move the change color component to a different file (ex. "changeColorMenu") and import it into the column menu. Move the css as well.

2024-02-23 12:48 UTC, SejalKumar03 approved these changes
It looks good!

2024-02-23 14:10 UTC, lbostre approved these changes
Looks good!

2024-04-02 00:53 UTC, closed without merging