Tsc 351 encryption jar tests (new branch)
earthhistoryviz/tsconline pull request #174
Opened 2024-07-12 06:52 UTC by JacquiFreeElectron

new branch since there are too many test logs on the old one

2024-07-15 02:21 UTC, paologum requested changes
sometimes the tests take longer, so for these tests specifically you should configure the timeouts to be longer ~20 seconds

also, mock ignore `console.logs`

2024-07-15 02:21 UTC, paologum commented on server/__tests__/encryption.test.ts
> +describe("requestDownload", () => {
should have a test that checks for if the access fails for if the regular datapack file check throws an error that is not `ENOENT` on line 131 in `routes.ts`
```
if (error.code === "ENOENT") {
      const errormsg = "The file requested " + filename + " does not exist within user's upload directory";
      reply.status(404).send({ error: errormsg });
    } else {
      reply.status(500).send({ error: "An error occurred: " + e });
    }
```

2024-07-15 02:21 UTC, paologum commented on server/__tests__/encryption.test.ts
> +describe("requestDownload", () => {
also should have a test for errors that get thrown and caught on line 168-175 in `routes.ts`
the last access check which is basically the same code as above but you should still check that this gets correctly sent back as the correct message

2024-07-15 02:21 UTC, paologum commented on server/__tests__/encryption.test.ts
> +    if (typeof contents.activeJar !== "string") throw new Error('AssetConfig must have an "activeJar" string');
you should just `assertAssetConfig` from `types`

2024-07-15 02:21 UTC, paologum commented on server/src/encryption.ts
> +      ]);
this should be not synchronous so use the async version

2024-07-15 02:21 UTC, paologum commented on server/__tests__/encryption.test.ts
> +const { rm: unmockedRm } = await import("fs/promises");
what is this last import for

2024-07-16 03:02 UTC, JacquiFreeElectron commented on server/__tests__/encryption.test.ts
> +const { rm: unmockedRm } = await import("fs/promises");
his is for using the real implementation of `rm `in clearing all generated files. `doUnmock()` requires importing again to make it effective.

2024-07-16 03:24 UTC, JacquiFreeElectron commented on server/__tests__/encryption.test.ts
> +  });
Do you mean I should also call `rm` on `maybeEncryptedFilepath` when `mkdir` fails and expect `rm` gets called in here? Or you mean I should check `rm `is not called?

2024-07-16 16:30 UTC, paologum commented on server/__tests__/encryption.test.ts
> +  });
expect that it doesn't get called

2024-07-16 18:05 UTC, JacquiFreeElectron commented on server/__tests__/encryption.test.ts
> +const { rm: unmockedRm } = await import("fs/promises");
As says in their documentation, `vi.rstoreAllMocks`"Will call [.mockRestore()](https://v0.vitest.dev/api/mock#mockrestore) on all spies. This will clear mock history and reset its implementation to the original one." and there's a note under `mockRestore()` says:  "Note that restoring mock from vi.fn() will set implementation to an empty function that returns undefined."    and bc I used vi.fn() for the fs/promises module, I need to use doUnmock().   I'll change the import go in the `afterAll`

2024-07-17 06:49 UTC, closed without merging