Tsc 413 download chart as png pdf make dialog focus on mount
earthhistoryviz/tsconline pull request #175
Opened 2024-07-12 21:01 UTC by jay-jhk-lee

Download chart as pdf and png works
A few concerns are the time it takes to save a pdf and the resolution of the pdf
used webworker to asynchronously create the pdf since it is computationally intensive

https://github.com/user-attachments/assets/99b6f212-bfe2-4855-809d-b65f877ce34e
pdf
[test.pdf](https://github.com/user-attachments/files/16199248/test.pdf)
png
![test](https://github.com/user-attachments/assets/d4c0dae0-b8bf-454a-ab47-f371b7ea640f)

2024-07-15 02:53 UTC, paologum requested changes
how does it look on dark mode (loading button)

also since we webworker this, exiting the dialog should still download the chart with the webworker when they leave/press cancel right

2024-07-15 02:53 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +                FileSaver.saveAs(value, state.chartTab.downloadFilename + ".pdf");
technically all this code doesn't need to be in the `image.onload` function
the creation of the image is mainly just for the `url` so i think for better readability you can do something like
```

function svgToImageURI(svgString: (idk), width: number, height: number) {
  return new Promise((resolve, reject) => {
    const svgBlob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(svgBlob);

    const image = new Image();
    image.width = width;
    image.height = height;
    image.src = url;

    image.onload = function () {
      const canvas = document.createElement("canvas");
      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      const pixelRatio = 3;
      canvas.width = width * pixelRatio;
      canvas.height = height * pixelRatio;
      ctx.setTransform(pixelRatio, 0, 0, pixelRatio, 0, 0);
      ctx.drawImage(image, 0, 0);

      URL.revokeObjectURL(url);
      const imgURI = canvas.toDataURL();
      canvas.remove();
      resolve(imgURI);
    };

    image.onerror = reject;
  });
}
```

and then use the resolved value for the webworker

2024-07-15 02:53 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +            actions.setChartTabIsSavingChart(false);
should remove the `a` element

2024-07-15 02:53 UTC, paologum commented on app/src/ChartOptionsBar.tsx
> +                FileSaver.saveAs(value, state.chartTab.downloadFilename + ".pdf");
also let's say `ctx` returns, then we won't have an `imgUri` so you might/should want to `reject` and handle that properly with error pushing and the like

2024-07-15 23:52 UTC, jay-jhk-lee commented
Yes, I've realized that the text is misleading so I changed it

2024-07-16 16:53 UTC, paologum commented
the `.yarn` and `.pnp.cjs` were removed, so remove them from the commit

2024-07-16 16:55 UTC, paologum commented on app/src/ChartOptionsBar.tsx
it might be good, if they select pdf to have a tooltip that says they can leave and do other stuff since generating a pdf takes a while. up to you though

2024-07-16 20:50 UTC, paologum approved these changes

2024-07-16 21:05 UTC, merged