Tsc 446 event search new perspective
earthhistoryviz/tsconline pull request #181
Opened 2024-07-17 23:06 UTC by jay-jhk-lee

Reduced column count to 4
combined toggle column and column path

- column toggled on click of cell
- icon indicates if column is toggled (including its parents)

combined age and modify time interval

- icon indicates if age is within time interval

https://github.com/user-attachments/assets/c5f35ed2-f58b-4ad8-83d2-02fc0b84fead

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/3196455c-93f8-4b9f-85f5-c7f550e1b58f">

2024-07-18 16:35 UTC, paologum requested changes

2024-07-18 16:35 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +  }
hmm so it's considered out of the interval if it's only within 2 of the `chartBaseAge`?

2024-07-18 16:35 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +    </div>
i would wrap in a fragment if this doesn't affect styling

2024-07-18 16:35 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +        {info.age.topAge} - {info.age!.baseAge}
why does only `baseAge` have a `!`

2024-07-18 16:35 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +      );
for events that don't have ages, currently it displays it sort of as two error icons then?

was this one originally just like a line if it didn't exist?

2024-07-18 16:35 UTC, paologum commented on app/src/settings_tabs/Search.tsx
> +            Top Age: {state.settings.timeSettings[units].topStageAge}
just a comment but you can just do `bgcolor="secondaryBackground.main"` in the `Box` props so you don't have to like deconstruct a larger theme object

2024-07-18 16:35 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +            <Column info={info} />
is there any way to make the column cell as big as it can be, because rn it looks like it cuts column names off really early as opposed to the space it looks like it has to display the name

<img width="207" alt="Screenshot 2024-07-18 at 12 35 30 PM" src="https://github.com/user-attachments/assets/82a6bfdd-a8a9-4c4e-ab8d-3cbd95717cca">

2024-07-18 19:36 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +      );
No, it should only display the line since it checks if age exists on the parent component. It was supposed to be a backup check, but now that I think about it the check should only be in that component. I'll change it

2024-07-18 19:37 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +  }
Oops, I'll change that

2024-07-18 19:40 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +        {info.age.topAge} - {info.age!.baseAge}
Mistake, will remove

2024-07-18 21:18 UTC, jay-jhk-lee commented
<img width="698" alt="image" src="https://github.com/user-attachments/assets/7955e4d0-bfb6-4334-9705-ff671172aa97">

2024-07-19 00:12 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +  }, []);
instead of changing the width of the table cell, why can't you just make the `column` cell `flex-grow` and `flex-shrink`

2024-07-19 15:51 UTC, paologum commented
/deploy

2024-07-19 21:03 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +  }, []);
resolved in latest push

2024-07-19 21:36 UTC, paologum commented
i would still have the tooltips that say center or extend within a 3mya (i forget the unit) boundary

2024-07-19 21:57 UTC, jay-jhk-lee commented
I added a help icon for that before i read your comment since its a little bit different for each function and I couldn't find a concise way to word it, let me know if I should still add it to the tooltip

2024-07-19 22:09 UTC, jay-jhk-lee commented
I added a help icon for that before I read your comment, it's a bit more specific in case someone is confused from the tooltip. let me know if you think I should remove it or change it.

2024-07-19 22:29 UTC, paologum commented
hmm i don't think we want four icons, (Column off & age not in interval and Column on & age not in interval) both mean the same thing in the context of this display

both mean that the event won't be included, so it should just have 3 similar to the column page because that's what the team agreed on today

2024-07-19 22:40 UTC, paologum requested changes
and my comment above

2024-07-19 22:40 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +  return { topAge: topAge, baseAge: baseAge };
`baseAge += 3` can't be < 0 unless it's negative i'm assuming you mean the other way

also for readability you might wanna do like `min` and `max` so it's easier at a glance

2024-07-19 22:40 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +};
we truncate now? if this is a general thing why only results and not the whole app in the action?

2024-07-19 22:40 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +  return <div>{info.qualifier}</div>;
i forgot to mention but these should be in `Typography` no?

2024-07-19 22:43 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +};
there are also most likely in human events, Ma's that are very small and could go pretty far past like Lt. Pliest
so if events are like that, the top age and base age would get cut off?

2024-07-20 15:33 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +};
I see, I did this for the case where the float bugs out and has a bunch of zeros in the end (8.000000000..). I forgot about that case, I'll modify it

2024-07-20 15:35 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +  return { topAge: topAge, baseAge: baseAge };
yes, I was catching for the case where it could possibly be negative even though that is most likely not going to happen.

2024-07-20 15:48 UTC, jay-jhk-lee commented
Yes, both mean that the event won't be displayed on the chart. However, I think it's important to specify why it's not in the chart since we can both toggle the column and change the time interval. So I'll change the orange icon to be the same but change the tooltips to convey that information.

2024-07-20 20:23 UTC, paologum commented
yep i think that's a good idea with the tooltips
if you want a little distinction i think a different color might be a good idea too, probably not the same as the red x though but it's definitely something that might be helpful but i like this

2024-07-20 20:28 UTC, paologum commented on app/src/settings_tabs/Results.tsx
> +    min = 0;
why is it having large floating point decimals?

2024-07-20 20:28 UTC, paologum approved these changes
looks good, up to you if you wanna do color thing

2024-07-21 23:10 UTC, jay-jhk-lee commented on app/src/settings_tabs/Results.tsx
> +    min = 0;
I'm not sure, I think it's a problem with adding floats in general with javascript.

2024-07-21 23:11 UTC, merged