Tsc 311 functionality to add blank age column
earthhistoryviz/tsconline pull request #184
Opened 2024-07-21 15:49 UTC by JacquiFreeElectron

demo: 

https://github.com/user-attachments/assets/72372ccd-1d6d-45b6-8b80-ca935c3b0645

also I changed the default justification of Ma to "right" bc that's the default value in the jar. (and the default justification of any other age ruler is "left").

2024-07-22 16:18 UTC, paologum commented
for the buttons i would use `TSCButton` so they adhere to the theme

2024-07-22 16:48 UTC, paologum requested changes

2024-07-22 16:48 UTC, paologum commented on app/src/settings_tabs/column_menu/ColumnMenu.tsx
> +    if (!(column.columnDisplayType === "Ruler" && column.name.includes("Age"))) return "";
for easier readability i would just have `||` instead of inverting using DeMorgan's law to inverse it when you read

2024-07-22 16:48 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  const biggestExistedSerialNum = column.children.findLastIndex((child) => child.name.includes("Blank"));
grammar thing but it would make more sense for this to be called `largestExistingSerialNum`

2024-07-22 16:48 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    serialNumber = Number(column.children[biggestExistedSerialNum].name.charAt(6)) + 1;
you should future proof this for multiple digits

2024-07-22 16:48 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  }
here too, possibly just make a helper function since this is basically the same code

2024-07-22 16:48 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  const maWidth = state.settingsTabs.columnHashMap.get("Ma")?.width;
probably should hard code or something, unless this is how they do it in the java file since other units also exist as ruler types, or alternatively make a constant somewhere that applies to both the ruler we apply and the one here

2024-07-22 16:48 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    ...cloneDeep(column),
this age column will have the same `Subinfo`? it probably shouldn't
also applies to blank

2024-07-22 16:48 UTC, paologum commented on app/src/state/parse-settings.ts
> +        title = "Blank " + column[key].charAt(6);
multi digits

2024-07-22 16:48 UTC, paologum commented on shared/src/index.ts
> +  | "Data"
is this not just `Blank` in `ColumnInfoType`?

2024-07-22 17:08 UTC, JacquiFreeElectron commented on shared/src/index.ts
> +  | "Data"
Nope, it's data in the jar settings file, blank is another type of column

2024-07-22 17:08 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +    ...cloneDeep(column),
ok

2024-07-22 17:21 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +  const maWidth = state.settingsTabs.columnHashMap.get("Ma")?.width;
In the jar, they use 'auto' to make it the same as the Ma. So far, the width of Ma is always 44.6953125, but I'm not sure if it could be changed under some circumstances... I can make a constant if you want to

2024-07-22 17:36 UTC, JacquiFreeElectron commented on app/src/state/actions/column-actions.ts
> +  const maWidth = state.settingsTabs.columnHashMap.get("Ma")?.width;
and I just realized it works even if the ruler column doesn't have a defined width, the jar will set a width for it automatically. so I can probably just set `width `to `undefined`. Do you think this is good? (bc there isn't an explicitly defined width for Ma too)

2024-07-22 19:20 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  const maWidth = state.settingsTabs.columnHashMap.get("Ma")?.width;
yup that sounds good

2024-07-22 19:21 UTC, paologum commented
/deploy

2024-07-22 19:26 UTC, paologum requested changes

2024-07-22 19:26 UTC, paologum commented on app/src/settings_tabs/column_menu/AddBlankColumnButton.tsx
empty file

2024-07-22 19:26 UTC, paologum commented on app/src/util/util.ts
> +}
if either `first` or `second` are not found (i.e -1) then `return 0`

2024-07-22 19:26 UTC, paologum commented on app/src/util/util.ts
> +}
also have errors/returns for if `serialNumber` is `NaN`

2024-07-22 19:28 UTC, paologum commented
also the generated chart has negative `age`, is this normal?

2024-07-22 23:03 UTC, JacquiFreeElectron commented
> also the generated chart has negative `age`, is this normal?

yep, as least it's the same as the jar: 
<img width="783" alt="Screenshot 2024-07-22 at 7 02 23 PM" src="https://github.com/user-attachments/assets/3cfa748b-af3b-4177-a97a-e5fca45f35a4">

2024-07-22 23:03 UTC, JacquiFreeElectron commented on app/src/util/util.ts
> +}
ok

2024-07-22 23:04 UTC, JacquiFreeElectron commented on app/src/settings_tabs/column_menu/AddBlankColumnButton.tsx
will remove

2024-07-23 03:07 UTC, paologum requested changes

2024-07-23 03:44 UTC, JacquiFreeElectron commented on app/src/state/parse-settings.ts
> +      }
you mean just "Age 1" "Age 2" "Age 3"..?

2024-07-23 03:53 UTC, paologum commented on app/src/state/parse-settings.ts
> +      }
yup, is there a reason we need to have the for if we just change it here?

2024-07-23 04:06 UTC, JacquiFreeElectron commented on app/src/state/parse-settings.ts
> +      }
well at first, bc in the jar setting file the `_id` for age ruler is always "Age" (which means they are all the same), so I didn't think about using the id version and used 'for' bc the state name needs to be different. But then there was an issue that only one Age column was generated even if I added/selected two ages, so after encountering this issue I tried making the `_id` of each age column different and it worked. so I just left the implementation of 'for' in there. I can certainly change it if you want

2024-07-23 17:14 UTC, paologum commented on app/src/settings_tabs/column_menu/ColumnMenu.tsx
> +  const [ageSerialNum, setAgeSerialNum] = useState(1);
why did you revert back? this won't work because everytime this component reloads it resets at 1 ie
now both these ages are the same if i create, leave, and then come back and create another (they have the same id so they are both selected)

<img width="441" alt="Screenshot 2024-07-23 at 1 14 26 PM" src="https://github.com/user-attachments/assets/36fb517d-73eb-49b8-8523-93fcd9ad7363">

how you had it before was fine, it should just not take the `for ${name}` out when making id's if we don't need to. just so we can use the normal way so we don't have extra cases for no reason because the main intention for these serial numbers is for there to be unique ids right, so we shouldn't need to remove/append a for under certain cases

2024-07-23 17:16 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  console.log(ageColumnName);
log here

2024-07-23 17:17 UTC, paologum commented on app/src/state/parse-settings.ts
> +    }
like the age, is there a reason we need to remove the for the column part? does it still generate correctly?
if it does then we should just leave it instead of casing it

2024-07-23 19:49 UTC, JacquiFreeElectron commented on app/src/settings_tabs/column_menu/ColumnMenu.tsx
> +  const [ageSerialNum, setAgeSerialNum] = useState(1);
ok I get it now. sorry I misunderstood what you want me to do earlier. I’ll check if it’s going to work with the “for…” in the _id, if yes then I will keep it, if no then I will revert to what I have before

2024-07-23 20:46 UTC, JacquiFreeElectron commented
works fine with the "for..." in _id: 
<img width="925" alt="Screenshot 2024-07-23 at 4 44 50 PM" src="https://github.com/user-attachments/assets/5c669281-d63e-47ef-92db-9ea6cd29082d">

2024-07-23 22:49 UTC, paologum approved these changes
looks good!

2024-07-23 23:17 UTC, merged