Tsc 425 make chart generation errors print fatal
earthhistoryviz/tsconline pull request #188
Opened 2024-07-24 03:28 UTC by Changk820

https://youtu.be/RSfqLPk34vs

2024-07-24 15:52 UTC, paologum requested changes

2024-07-24 15:52 UTC, paologum commented on server/src/graph-error-handler.ts
probably call it chart instead of graph

2024-07-24 15:52 UTC, paologum commented on server/src/graph-error-handler.ts
> +    }
Are these the full lines or only partial parts of the line

2024-07-25 23:23 UTC, Changk820 commented
/deploy

2024-07-25 23:43 UTC, paologum commented on server/src/routes.ts
> +  let errorMessage = ""; // error message found during chart generation via java jar call
if `errorMessage` existence is what matters we don't need two variables, you can just check `errorMessage` since empty strings are falsy

2024-07-26 05:09 UTC, Changk820 commented
I optimized the code a bit, also I finally understand what you mean by partial/full messages, so I improved that part too.

Something to note: I added 1 line to java program to make it so if the java program can't make it to the finish line of generate chart, a print statement won't occur, thus we know for sure an error happened. But the issue is, I only added cases for if chart generation failed looking at the java program. See chart-error-handler.ts.

I also added some other errors cases that I know could potentially cause the program to crash/fail.

If we don't know the error, it will just be listed as unknown, but the chart generation will still stop as expected and we will tell the user.

One final note: We only know the actual issue if we have access to the server. The users will only see that chart generation failed, either because of bad database or settings. but they won't know which. I imagine this isn't very helpful to them?

If it's not, can we talk about how to do it Friday? I tried to get the actual message as a popup but had no success.

Otherwise, I'll just leave as it is.

2024-07-27 06:20 UTC, paologum commented on app/src/state/actions/generate-chart-actions.ts
> +    }
you should use `isServerResponseError` and also passin `ErrorMessages[ErrorCodes.INVALID_CHART_FROM_JAR]` instead of `answer.error`
it will log the server error to console instead, so that errors will properly stack for now until we actually have the status codes setup in a future pr

2024-07-27 16:50 UTC, paologum commented on app/src/state/actions/generate-chart-actions.ts
> +    }
for reference, this technically does work, but allocating all our error messages in one place, makes translation easier

2024-07-27 22:43 UTC, asivath commented
/deploy

2024-07-27 22:43 UTC, asivath commented
/confirm-deploy

2024-07-29 17:23 UTC, paologum approved these changes

2024-07-29 17:23 UTC, merged