Tsc 408 read settings must support data mining columns
earthhistoryviz/tsconline pull request #193
Opened 2024-07-25 03:20 UTC by jay-jhk-lee

Load settings now properly create datamining columns

https://github.com/user-attachments/assets/324e405f-6a42-4a45-8650-77cb081b34c5

2024-07-25 20:32 UTC, paologum requested changes

2024-07-25 20:32 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +}
instead of buckets, why can't we just track all datamining columns in reading in some cache `foundCache` or something (where `isDataminingColumn=true`) that holds the settings

and also create a hash map (`shouldCache` or something) for columns that "should" exist ie `<setting name="drawExtraColumn">FAD</setting>`. which holds the ref column ( if it is a nested data mining it holds null, then when we attempt to iterate over it, we add the check (`IF NULL AND DOESN'T EXIST IN STATE { continue } `)

Then you loop over `shouldCache` after sorting it by string length, find the ref column and construct the string of the setting that should exist `FAD for ...` then see if it exists in `foundCache`, add the column, then apply the settings from the cache.

the approach above also seems more straightforward and doesn't rely on the name format as a signifier of existence and goes from a bottom up iteration

additionally any column that has `for` in it's name could disrupt the distanceBucket
whereas this solution would compensate by building up

2024-07-25 20:32 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  state.settingsTabs.dataMiningColumnsCache = new Map<number, PointColumnInfoTSC[]>();
is there a reason this cache needs to be in `state`? it technically doesn't refresh any components. it might be better to just make this a local variable that gets reset everytime we call `readSettings`
it might be better to have it as a `parse-settings.ts` artifact

2024-07-25 20:32 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          if (isDataMiningPointDataType(dataMiningType)) addedColumnName = addDataMiningColumn(refCol, dataMiningType);
`Chron` although they share `Frequency` you should use the seperate functions for defining them to future proof this method

2024-07-25 20:32 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
should only add if `isDataMiningColumn`

2024-07-25 20:32 UTC, paologum commented on shared/src/settings-types.ts
> +  )
i'm thinking about this, and overlay should be it's own thing, in it's own tag because it functions different than a `dataMiningColumn`. This means that we'll have to change the java file but you can expect overlay to not be a part of the tag

you can keeep this here but add a todo to change it or you can remove it and just expect no overlay to be sent (although it technically can for a certain period, but we'll have tasks to remove it for the future)

2024-07-25 20:32 UTC, paologum commented on app/src/state/parse-settings.ts
> +          }
i feel like you should put this in the `processColumn`

2024-07-27 16:44 UTC, paologum requested changes

2024-07-27 16:44 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    currIdentifier: EventFrequency | DataMiningChronDataType | DataMiningPointDataType | null;
this variable name kinda confused me, i would name it `existingDataMiningType` and `loadedDataMiningType`

2024-07-27 16:44 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +        } else dataMiningRefCache.set(columnName, { currIdentifier: null, loadedIdentifier: settings.drawExtraColumn });
i feel like we don't need to log this difference and we can just do `if (column && column.columnDisplayType === "Point")`
that way we only set the cache once instead of twice with a return statement

2024-07-27 16:44 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +        } else dataMiningRefCache.set(columnName, { currIdentifier: null, loadedIdentifier: settings.drawExtraColumn });
additionally if they don't match i don't see why we should cache the column, at this point in the code or later when we add the column, the column still isn't gonna match so we are going to attempt to add a datamining column to a column that doesn't match. it should probably just skip

2024-07-27 16:44 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    const dmName = addDataMiningColumn(refCol, loadedIdentifier);
i would put this as a try catch because `loadedIdentifier` can be a bunch of different things and `refCol` can be a bunch of different things so there could be many errors if things get mismatched during a load
(just due to the combined assertion statements)

2024-07-29 18:09 UTC, jay-jhk-lee commented
Your suggestion for processColumn wouldn't work. The `column` variable is a placeholder variable (ColumnInfoTSC) that will be filled with the information from its child nodes. Once we enter the `processColumn` function for a particular column, we don't have access to its `isDataminingColumn` attribute since it is part of the column node itself. We either have to pass it through as a parameter, or set it like how I have it right now.

2024-07-29 18:25 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          });
can you give an example as to why we would want to keep it if the types are mismatched i'm still confused

2024-07-30 00:26 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +          });
hmm i'm still confused here do you have an example?
where the same column name exists and we would still want to store the null datamining column

2024-07-30 00:26 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +        }
i feel like we don't need to have a seperate log for if they have different types and the same name

it should really be up to the user to figure that out tbh because they loaded/created it wrong

this'll help clear complexity imo

2024-07-30 23:03 UTC, paologum approved these changes

2024-07-31 00:01 UTC, merged