Tsc 388 public datapack upload
earthhistoryviz/tsconline pull request #195
Opened 2024-07-25 21:46 UTC by rupp3

![image](https://github.com/user-attachments/assets/58540212-37ea-4b6b-b7ee-4373b540f7cf)
First screenshot shows what "username1" sees. The Malaysia datapack was uploaded publicly by "username" and nannos datapack was uploaded by "username1" 
![image](https://github.com/user-attachments/assets/42465b70-df1a-4fff-a617-132e908390f6)
Second screenshot shows "username" after uploading New Zealand datapack publicly

2024-07-25 22:06 UTC, rupp3 commented
just realized public datapacks dont load until a user uploads their own datapack. also no clue why there are 35 commits with this, there should only be the last two, but i will also fix that

2024-07-26 06:39 UTC, paologum requested changes

2024-07-26 06:39 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    console.log("data in fetchUserdatapack general actions", data);
console

2024-07-26 06:39 UTC, paologum commented on server/src/routes.ts
> +      publicFiles = JSON.parse(publicFilesData);
need to `assert` here because you're reading from the files and these `JSON` could be outdated and would then technically be migrated but that's a different problem, but they need to be validated as the correct type

2024-07-26 06:39 UTC, paologum commented on server/src/routes.ts
> +      publicMappacks[filename] = mapPackIndex[filename] as MapPack;
the above comment would remove the need for the casting

2024-07-26 06:39 UTC, paologum commented on server/src/routes.ts
> +      .catch(() => []);
need to `assert` here too

2024-07-26 06:39 UTC, paologum commented on server/src/routes.ts
> +  const publicDir = path.join(assetconfigs.uploadDirectory, "public");
you should just make this in `assetconfigs` as the public directory

2024-07-26 06:39 UTC, paologum commented on server/src/routes.ts
> +    }
this check needs to happen earlier, and it needs to cleanup and throw error if they attempted to make it public and it already exists

2024-07-26 06:40 UTC, paologum commented
additionally, these public datapacks should be added into the logic of when we fetch server datapacks, because right now noone can view these datapacks/ the logic for providing them to all users (logged in and not) is not there

2024-07-27 16:49 UTC, paologum commented on server/src/routes.ts
> +  }
one more thing instead of making `isPublic` be a `let` instead of `const`
to keep it in tune with the name and description you should
`const isPublic = fields.isPublic === "true"`

2024-08-15 04:49 UTC, closed without merging