datapack frontend page
earthhistoryviz/tsconline pull request #20
Opened 2024-02-19 18:49 UTC by rupp3

![TSC-131-datapack-picture](https://github.com/earthhistoryviz/tsconline/assets/54484966/d641d5eb-8366-4543-8d33-67d93b543f79)

2024-02-20 02:07 UTC, paologum requested changes

2024-02-20 02:07 UTC, paologum commented on app/src/Datapack.tsx
> +    setCheckedNotApplied(true);
i think the logic here should just take a `name: string` and you can just do the same logic but with `state.config.datapacks`. That variable is what we use to keep track of the datapacks used.

2024-02-20 02:07 UTC, paologum commented on app/src/Datapack.tsx
> +    setCheckedNotApplied(true);
otherwise deprecate `setSelectedDatapacks` and use `state.config.datapacks` instead

this will mean you need to make an action that does what you want since you can't change the state object outside of an action. See `GeneralActions.ts` for more info on that.

2024-02-20 02:07 UTC, paologum commented on app/src/Datapack.tsx
> +      <Typography style={{ fontSize: 18, marginTop: "1em", marginBottom: "3vh"}}>
move this style to css

for typography you will need to make a css class like so

`.MuiTypography-root.[class-name] {
....
}`

2024-02-20 02:07 UTC, paologum commented on app/src/Datapack.tsx
> +                  <div style = {{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
add this to css

2024-02-20 02:07 UTC, paologum commented on app/src/Datapack.tsx
> +  ];
just a comment but to see the actual forms the `datapack` see `DatapackParsingPack` in `shared`

might have to edit this to include descriptions but that's the object you'll be using for this page

2024-02-20 02:07 UTC, paologum commented on app/src/Datapack.tsx
> +  ];
that name could be wrong but it should be relatively called that

2024-02-24 18:52 UTC, paologum requested changes

2024-02-24 18:52 UTC, paologum commented on app/src/Datapack.tsx
> +  };
is this used? if not remove

2024-02-26 04:44 UTC, paologum approved these changes
looks good! but lmk how this looks on mobile/post in the description

2024-02-26 07:12 UTC, rupp3 commented
![image](https://github.com/earthhistoryviz/tsconline/assets/54484966/83eda471-7008-4380-94d8-2e503d85d058)

this is most recent change shown on mobile. i had to fix the table layout. nothing happens for the info icon so I will probably add a pop out for the info button if it is pressed on mobile (?)

2024-02-27 03:14 UTC, rupp3 commented
![image](https://github.com/earthhistoryviz/tsconline/assets/54484966/5f65228d-052e-453b-ba03-a32ac83aca56)
![image](https://github.com/earthhistoryviz/tsconline/assets/54484966/acb3029a-4a0b-419d-b475-10079e4bcc61)

most recent mobile view, added the background theme. when i click on a different tab and go back to the datapack tab the format changes to be centered but when i first go to the datapack tab it starts centered to the left. When i scroll over to the info tab the theme also does not carry to the rest of the box

2024-03-01 07:03 UTC, paologum approved these changes
looks good!

2024-03-01 07:03 UTC, paologum commented on app/src/Datapack.css
> +  width: 85%; /*this fixed the window scaling issue, changed from 100 */
hmmm ok i'm assuming this fixes the mobile issue where there's whitespace

2024-03-01 15:51 UTC, rupp3 commented on app/src/Datapack.css
> +  width: 85%; /*this fixed the window scaling issue, changed from 100 */
yeah, is that not allowed?

2024-03-01 16:57 UTC, rupp3 commented
![image](https://github.com/earthhistoryviz/tsconline/assets/54484966/0487a5d6-7f6a-4cee-b05b-4c7b2d31669a)

2024-03-02 01:12 UTC, tobyonyekwere1 reviewed
Code is properly written and easy to understand as well. Great work!

2024-03-03 15:53 UTC, JacquiFreeElectron approved these changes
looks great

2024-03-04 04:22 UTC, merged