Tsc 389 column menu scroll up on navigation bar
earthhistoryviz/tsconline pull request #201
Opened 2024-07-29 16:43 UTC by Changk820

![image](https://github.com/user-attachments/assets/a28adc27-1b24-47d1-b859-35a2d7eeb101)
That blue button only shows when scroll down a bit, roughly when 5 rows are scrolled pass it will show. 

I also tested to make sure if I expand the menu to be big and keep scrolling, the position of the button is always fixed.

There is a slight issue though, as you can see from the CSS, I had to do some weird hard coding of its position. I tried doing absolution position, but no matter what, the position is in relation to the full window of the site, not  the box the setting names are in, thus I ended up just using position: fixed and percentages to get it right inside the box.

If you have any ideas, lmk.

For now, I'm going to make pull request and deploy to see if it looks correct on 27 in.

2024-07-29 16:47 UTC, Changk820 commented
/deploy

2024-07-29 17:35 UTC, paologum commented
the arrow should be within the accordion box

![image](https://github.com/user-attachments/assets/3afc7a1d-b857-429f-8cc8-ed269233ad34)

2024-07-30 00:18 UTC, Changk820 commented
/deploy

2024-07-30 00:20 UTC, Changk820 commented
not done yet btw

2024-07-30 00:21 UTC, Changk820 commented
/confirm-deploy

2024-07-30 00:29 UTC, Changk820 commented
> the arrow should be within the accordion box
> 
> ![image](https://private-user-images.githubusercontent.com/89664317/353174104-3afc7a1d-b857-429f-8cc8-ed269233ad34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyOTk0MTEsIm5iZiI6MTcyMjI5OTExMSwicGF0aCI6Ii84OTY2NDMxNy8zNTMxNzQxMDQtM2FmYzdhMWQtYjg1Ny00MjlmLThjYzgtZWQyNjkyMzNhZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAwMjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOGU4NWY4NzUwM2Q1ZWI3NTFmOTExMTM3NzM4YmI0Y2I2YTU1YzljYjlmYzkzNzk0NTk1MDY2NWRkNDU0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JOx4G0a6ujU593aVXQ4CGzymd3GClTCA1VHvqBgb0s0)

How were you able to get that image?
I think it works now because I zoomed in a lot and it still stays in, same with using inspect to preview it. I couldn't get deploy to work

![image](https://github.com/user-attachments/assets/acd6466d-cce3-4930-b30b-d8d3e2cbc943)

![image](https://github.com/user-attachments/assets/29411b1f-ee0b-4b30-b639-6464c82a1ef1)

![image](https://github.com/user-attachments/assets/011e417e-ee44-4a44-b95f-45404f0f688c)

2024-07-31 07:16 UTC, Changk820 commented
I cant get it to fade in fade out, but the other changes you asked for are there

2024-07-31 15:45 UTC, paologum commented
to get it to fade in and out, look at transitions with css and change visibilities/display when it appears vs when it doesn't appear

2024-07-31 15:45 UTC, paologum commented
there is code for that again in the map points legend scroll to top button

2024-07-31 15:47 UTC, paologum commented
hmm wait looking at the code give me a second, bc you did use the map points legend thingie

2024-07-31 16:01 UTC, paologum requested changes

2024-08-01 17:35 UTC, Changk820 commented on app/src/settings_tabs/Column.tsx
> +                animationData={LightArrowUpIcon}
I thought the darkarrow was kind of ugly
![image](https://github.com/user-attachments/assets/f079ef8c-af30-422b-b422-e9f363d4b6fa)
![image](https://github.com/user-attachments/assets/bd70bfdb-0725-41f7-8be7-57562e9dc0eb)


Should it maybe be swapped?
![image](https://github.com/user-attachments/assets/bc430bd1-8038-4a47-8332-e0443839fb14)
![image](https://github.com/user-attachments/assets/044ac6e7-37e7-40ba-8aa7-976ef0527a69)

to match the check mark colors

2024-08-01 17:48 UTC, Changk820 commented on app/src/settings_tabs/Column.css
> +  color: #fff;
i applied the brightness thing in next step, without background you don't see it light up as well, but the button i guess is self explanatory anyways
![image](https://github.com/user-attachments/assets/e0ad7179-477b-42d3-a652-ea9cdbc17b6e)

2024-08-01 21:16 UTC, paologum approved these changes

2024-08-01 21:16 UTC, paologum commented on app/src/settings_tabs/Column.tsx
> +              // animationData={theme.palette.mode === "light" ? LightArrowUpIcon : DarkArrowUpIcon}
just remove this comment and you should be good

2024-08-02 01:15 UTC, Changk820 commented on app/src/settings_tabs/Column.tsx
> +              // animationData={theme.palette.mode === "light" ? LightArrowUpIcon : DarkArrowUpIcon}
I forgot to remove while testing appearance  lol.

2024-08-02 01:44 UTC, merged