Tsc 403 coverage report enforcement
earthhistoryviz/tsconline pull request #209
Opened 2024-08-01 01:24 UTC by asivath

You can see what the coverage comment looks like: https://github.com/earthhistoryviz/tsconline/pull/208

2024-08-01 21:27 UTC, paologum requested changes

2024-08-01 21:27 UTC, paologum commented on .github/workflows/merge-pipeline.yml
> +          yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
does `yarn coverage` not have an exit code we can use to verify it failed instead of greping

2024-08-01 21:27 UTC, paologum commented on vite.config.ts
> +
i was thinking about this, and since we have such a high test coverage on the files below, i think we should have it 90 so that anyone updating these files will make tests immediately, rather than maybe squeaking by since some are 90~100 and small functions or whatever can get by.

except `encryption.ts` because it has like three lines it doesn't account for but you can do your exception like you do for it already or add a test for it

2024-08-01 22:16 UTC, asivath commented on .github/workflows/merge-pipeline.yml
> +          yarn coverage:ci > test_output.log 2>&1 || (grep -q 'ERROR: Coverage' test_output.log && echo "coverage_failed=true" >> $GITHUB_OUTPUT) || echo "test_failed=true" >> $GITHUB_OUTPUT
vitest doesn't provide different error codes or a way to actually edit that so I don't know of another way to do this

2024-08-02 00:03 UTC, paologum approved these changes

2024-08-02 00:14 UTC, merged