deprecated updateSettings action and connected time to chart
earthhistoryviz/tsconline pull request #21
Opened 2024-02-19 19:47 UTC by jay-jhk-lee

https://github.com/earthhistoryviz/tsconline/assets/89719669/23a89a88-d870-4841-86d0-f74b06269889

2024-02-19 21:38 UTC, paologum requested changes
some changes/comments but looks good

2024-02-19 21:38 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +    //actions.updateSettings();
i'd say just remove this line and the whitespace above and below

2024-02-19 21:38 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +              //actions.updateSettings();
same

2024-02-19 21:38 UTC, paologum commented on app/src/state/actions/GeneralActions.ts
> +// export const updateSettings = action("updateSettings", () => {
is this something we're ever gonna come back to?
if it is you can leave it but if we don't need it anymore then just remove this

2024-02-19 21:38 UTC, paologum commented on app/src/state/state.ts
> +    doPopups: false,
can you set the name of this to MouseOverPopupsEnabled

popups seems too generic since we have other things in the website that technically 'popup' so it could be a little ambiguous

2024-02-19 21:38 UTC, paologum commented on app/src/state/parseSettings.ts
> +  chartSettings: any,
leaving this here, not for an immediate change but at some point change these to actual types of variables.
resolve this when you see it 👯

2024-02-19 21:38 UTC, paologum commented on app/src/state/parseSettings.ts
> +          if (chartSettings.baseStageAge === 0) {
good comment, we also have datapackSuggAge popup now on datapacks that require it so you can try looking into that as well when making a default datapack

2024-02-19 21:57 UTC, jay-jhk-lee commented on app/src/state/actions/GeneralActions.ts
> +// export const updateSettings = action("updateSettings", () => {
Now that I'm looking at it again I think Sejal changed it for her stuff? I'll leave it just in case

2024-02-20 02:37 UTC, paologum approved these changes

2024-02-20 02:39 UTC, merged