Tsc 452 webworker for setting columns datapack config
earthhistoryviz/tsconline pull request #212
Opened 2024-08-05 04:27 UTC by JacquiFreeElectron

I'll upload the demo tmr, for now please use `/deploy ` 😬

2024-08-05 16:04 UTC, paologum commented
//deploy

2024-08-05 16:05 UTC, paologum commented
/deploy

2024-08-05 20:24 UTC, paologum commented
there is a delay i put on clicking the plus icon on the `Datapacks` page so the loading ui starts up a little bit before the overhead of the big function call takes place. you should remove that so that it just clicks on now

2024-08-05 20:52 UTC, JacquiFreeElectron commented
demo: (haven't removed the loading delay yet)

https://github.com/user-attachments/assets/d61934e0-419a-466e-9e4f-b92b903ca871

2024-08-05 21:22 UTC, paologum requested changes
pretty confused overall
mainly the implementation should be like this

there should be a dialog in `App.tsx` that opens when `state.isProcessingDatapackConfig` is `true`

We should wrap the webworker work into a promise function that way we can just call it like `await setDatapackConfig` or ig like `await processDatapackConfig` and then set it using the setter function. This will reduce the amount of duplicated code a lot, because it essentially shouldn't be a "new" function. All the `onClick` or component handlers that we pass should really call one function and maybe have one or two other lines besides that

Another big point like i commented is that it shouldn't have cache because that was a temp fix and is not memory efficient

2024-08-05 21:22 UTC, paologum commented on app/src/state/initialize.ts
> +    };
you should create a function that wraps this into a function that returns a promise
resolve/reject on a message/error
accepting params of `datapacks:[]` and `chartSettings`

need an `onerror` which should `terminate` as well

2024-08-05 21:22 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  (datapacks: string[], chartSettings: ChartInfoTSC | null) => {
we need this function? we have a webworker now for it

2024-08-05 21:22 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +
this should either just be a setter that sets the `chartSettings` in `state` or actually fetches the `settingsPath` with a route and sets it. otherwise this function doesn't make sense

2024-08-05 21:22 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    chartSettings: ChartInfoTSC | null
you should just call this `setDatapackConfig` and the actual overhead function as `processDatapackConfig`

2024-08-05 21:22 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    chartSettings: ChartInfoTSC | null
this function also does not need to assert because we declare types

2024-08-05 21:22 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +              }
need to await if you're using actions

2024-08-05 21:22 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +  const [processing, setProcessing] = useState(false);
as said before, should be a `state` variable

2024-08-05 21:22 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +              }
explain?

2024-08-05 21:25 UTC, paologum commented on app/src/components/TSCConfirmSelectionChange.tsx
empty file

2024-08-05 21:26 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +              setProcessing(false);
this should also popup when someone clicks a preset configuration, because there is a case where a large datapack configuration is selected and if that isn't done configuring, the user can add more datapacks/queue more in the settings if we don't popup the loader

2024-08-05 21:53 UTC, JacquiFreeElectron commented
> pretty confused overall mainly the implementation should be like this
> 
> there should be a dialog in `App.tsx` that opens when `state.isProcessingDatapackConfig` is `true`
> 
> We should wrap the webworker work into a promise function that way we can just call it like `await setDatapackConfig` or ig like `await processDatapackConfig` and then set it using the setter function. This will reduce the amount of duplicated code a lot, because it essentially shouldn't be a "new" function. All the `onClick` or component handlers that we pass should really call one function and maybe have one or two other lines besides that
> 
> Another big point like i commented is that it shouldn't have cache because that was a temp fix and is not memory efficient

ok, so three major changes: shouldn't use `state.datapackCachedConfiguration` anymore, wrap the webworker work into a promise function, change the place of the processing datapacks dialog to `App.tsx`.

2024-08-05 21:55 UTC, paologum commented
> > pretty confused overall mainly the implementation should be like this
> > there should be a dialog in `App.tsx` that opens when `state.isProcessingDatapackConfig` is `true`
> > We should wrap the webworker work into a promise function that way we can just call it like `await setDatapackConfig` or ig like `await processDatapackConfig` and then set it using the setter function. This will reduce the amount of duplicated code a lot, because it essentially shouldn't be a "new" function. All the `onClick` or component handlers that we pass should really call one function and maybe have one or two other lines besides that
> > Another big point like i commented is that it shouldn't have cache because that was a temp fix and is not memory efficient
> 
> ok, so three major changes: shouldn't use `state.datapackCachedConfiguration` anymore, wrap the webworker work into a promise function, change the place of the processing datapacks dialog to `App.tsx`.

yes, also add logic for preset clicking and `await`ing the `processDatapackConfig`
and abstracting the configuration to just a `string[]` unless i'm misunderstanding the approach

2024-08-05 22:09 UTC, JacquiFreeElectron commented
> setDatapackConfig

by "abstracting the configuration to just a string[]" you mean which configuration? The `state.config`?

2024-08-05 22:10 UTC, JacquiFreeElectron commented
> > > pretty confused overall mainly the implementation should be like this
> > > there should be a dialog in `App.tsx` that opens when `state.isProcessingDatapackConfig` is `true`
> > > We should wrap the webworker work into a promise function that way we can just call it like `await setDatapackConfig` or ig like `await processDatapackConfig` and then set it using the setter function. This will reduce the amount of duplicated code a lot, because it essentially shouldn't be a "new" function. All the `onClick` or component handlers that we pass should really call one function and maybe have one or two other lines besides that
> > > Another big point like i commented is that it shouldn't have cache because that was a temp fix and is not memory efficient
> > 
> > 
> > ok, so three major changes: shouldn't use `state.datapackCachedConfiguration` anymore, wrap the webworker work into a promise function, change the place of the processing datapacks dialog to `App.tsx`.
> 
> yes, also add logic for preset clicking and `await`ing the `processDatapackConfig` and abstracting the configuration to just a `string[]` unless i'm misunderstanding the approach

by "abstracting the configuration to just a string[]" you mean which configuration? The state.config?

2024-08-05 22:11 UTC, JacquiFreeElectron commented on app/src/state/state.ts
> +  }
I probably overcomplicate this, I will check if only a `selectedDatapacks` list is needed

2024-08-05 22:16 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
> +  (datapacks: string[], chartSettings: ChartInfoTSC | null) => {
this is for the datapack selection I think. I can try if after refactoring the webworker will be more efficient/stable when selecting multiple datapacks, if yes then I will remove this.

2024-08-05 22:24 UTC, JacquiFreeElectron commented on app/src/settings_tabs/Datapack.tsx
> +              setProcessing(false);
![Screenshot 2024-08-05 at 6 22 19 PM](https://github.com/user-attachments/assets/e68fd1f9-252f-4697-b453-8523b13ff840)
Is this the thing you're talking about

2024-08-05 23:19 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +              setProcessing(false);
i mean the generate button, when it is clicked it sets the datapack config first and then generates the chart

2024-08-05 23:22 UTC, JacquiFreeElectron commented on app/src/settings_tabs/Datapack.tsx
> +              setProcessing(false);
yeah actually I just checked the logic is needed for this add button as well, otherwise the datapack config won't update. I will add logic for this whole unit

2024-08-05 23:25 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +              setProcessing(false);
it technically was never there to begin with but if you want to add it in feel free to 👍

2024-08-07 21:31 UTC, JacquiFreeElectron commented
/deploy

2024-08-08 00:57 UTC, JacquiFreeElectron commented
new demo: 

https://github.com/user-attachments/assets/aaf930b3-4798-4333-8447-3c84987040e5

2024-08-08 15:34 UTC, paologum requested changes

2024-08-08 15:34 UTC, paologum commented on app/src/NavBar.tsx
> +  };
i don't think you should go about opening the popup here, there are too many spread out parts of this functionality compared to the way we do the age popup
use a `state` variable more aptly named like `showConfirmDatapackSelectionPopup` and set this when `initiateChartGeneration` is called when `state.datapackSelection.selectedDatapacks !== state.config.datapacks`

it would have it's own condition before the age popup part of that function `initiateChartGeneration`

then you would just have that variable for opening in the `TSCDialog` here where the `onYes` `onNo` `onClose` all set it properly

2024-08-08 15:34 UTC, paologum commented on app/src/NavBar.tsx
> +  };
although from a user perspective, if they selected it, then pressed the generate button they probably want to keep that selection. and they're probably ready for a loading process as well knowing that. so you instead of having a popup for this, you should just set it for them (which would put up the loading screen) and then generate normally. (disregard previous comment then)

2024-08-08 15:34 UTC, paologum commented on app/src/NavBar.tsx
> +          message="You have unsaved change on datapack selection. Do you want to save the change?"
try
`You have unsaved changes! If you leave now, your changes will not be saved.`

2024-08-08 15:34 UTC, paologum commented on app/src/Settings.tsx
> +  };
this is a boolean rather than a function

2024-08-08 15:34 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +              await processDatapackConfig([]);
same thing here with combining the two so it's easier

2024-08-08 15:34 UTC, paologum commented on app/src/state/state.ts
> +    selectedDatapacks: []
from previous comment you won't need `regenerateChart` but i would change `selectedDatapacks` to `unsavedDatapackConfig` to remove any confusion between the two

2024-08-08 15:34 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +    stateCopyObj = JSON.parse(stateCopy);
i would create an asserts specifically that `assertsState` for at the bare minimum the fields you need
beecause otherwise, we are "hoping" that the `stateCopy` is of the right type 

this will catch errors for `JSON` parsing but will not catch whether `stateCopy` is of the right type

2024-08-08 15:34 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +      //await new Promise((resolve) => setTimeout(resolve, 0));
remove

2024-08-08 15:34 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +      //await new Promise((resolve) => setTimeout(resolve, 0));
remove

2024-08-08 15:34 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +      }
you call `SetDatapackConfig()` three times also change it to camel case (`setDatapackConfig`)
then you can do `const result = await Promise...` and use the result to set the value

2024-08-08 15:34 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +    stateCopyObj = JSON.parse(stateCopy);
but i mean if you sent the actual state object and inferred it with `SetDatapackConfigMessage`, then it wouldn't need an `asserts` so could you explain why it needs to be a string

2024-08-08 15:34 UTC, paologum commented on app/src/process-datapack-config.ts
> +  } else {
if we return, we don't need an else

2024-08-08 15:34 UTC, paologum commented on app/src/process-datapack-config.ts
> +  }
this needs to be wrapped in a `Promise` where a successful message `resolve()` and an error `reject()`

2024-08-08 15:34 UTC, paologum commented on app/src/process-datapack-config.ts
> +          value.chartSettings
we set the `datapacks` here, so you shouldn't need to set it before you call this function like the other times. if your thought process was that they should see the change, they probably shouldn't bc if it fails it would be misleading

2024-08-08 15:39 UTC, paologum commented on app/src/process-datapack-config.ts
> +  }
this is needed because otherwise this function returns before the webworker is done, making the function operate oddly since we don't necessarily know from the function finishing whether there was an error or not which is misleading. after the webworker promise we create, you should call `actions.setIsProcessDatapacks(false)` after it (since it needs to be called after an error/success

2024-08-08 15:41 UTC, paologum commented on app/src/process-datapack-config.ts
> +  }
just to make sure it makes sense, rn the execution is 

call function -> start webworker -> finish function -> finish webworker -> see changes

whereas we want

call function -> start webworker -> finish webworker -> finish function -> see changes

this might look like it disregards the new thread that the webworker makes but if we wrap it in a promise it acts as just another async function with the added benefit of no extra thread blockage (we just return to it every cycle to check if it is done)

2024-08-08 16:44 UTC, JacquiFreeElectron commented on app/src/Home.tsx
> +                        { navigate: navigate, path: "/home" }
Use string copy because webworker can’t access to state object copy

2024-08-08 18:14 UTC, JacquiFreeElectron commented on app/src/state/state.ts
> +    selectedDatapacks: []
I think we should do selectedDatapacks because when user click generate the selectedDatapacks will get updated and it’s kinda untrue to call it unsaved

2024-08-08 18:22 UTC, JacquiFreeElectron commented on app/src/process-datapack-config.ts
> +          value.chartSettings
you mean I should set/update the `selectedDatapacks[]` in here? sorry I kinda lost

2024-08-08 18:29 UTC, JacquiFreeElectron commented on app/src/state/state.ts
> +    selectedDatapacks: []
Or maybe call it something like "datapackSelectionBuffer"? to indicate that this is different from `datapack.config.datapacks[]` and save&generate&select can all change it

2024-08-08 18:30 UTC, JacquiFreeElectron commented on app/src/process-datapack-config.ts
> +  }
got it. thanks

2024-08-08 19:14 UTC, paologum commented on app/src/Home.tsx
> +                        { navigate: navigate, path: "/home" }
ok if that's the case you'll want to assert the necessary fields

2024-08-08 19:24 UTC, paologum commented on app/src/NavBar.tsx
> +          message="You have unsaved change on datapack selection. Do you want to save the change?"
the two options should probably be `Leave Without Changes` and `Cancel` where `Leave` is the primary button

It should also probably be in `App.tsx` as well since we want to have this condition to open the popup
```
location !== /settings && state.settingsTabs.selected != "datapacks" && datapacks != unSavedConfig
```

2024-08-08 19:27 UTC, JacquiFreeElectron commented on app/src/NavBar.tsx
> +          message="You have unsaved change on datapack selection. Do you want to save the change?"
okok ty

2024-08-08 19:32 UTC, paologum commented on app/src/state/state.ts
> +    selectedDatapacks: []
well in naming this variable we have to distinctly seperate anyone from thinking that this might hold a meaningful state that contributes towards the actual datapack configuration that the state is based on. So in the var name there should be some dissonance that reflects that this variable is not something that should be the main focus, so in this case i think `unsavedDatapackConfig` would reflect that. If we were to call it buffer it would still be ambiguous to the point where they would have to read code more to get a better understanding.

technically all of the buttons can change this, but that doesn't change the fact that if it differs from the `config.datapacks` it is not reflected in state. once they are the same, then it's easily understandable this version is `saved` 
if you don't like `saved` i can see `draftDatapackConfig` as well



> I think we should do selectedDatapacks because when user click generate the selectedDatapacks will get updated and it’s kinda untrue to call it unsaved

this technically will always be the case with any "temporary" variable but if you don't call it a "temp" variable because it aligns with the main config, you lose some readability

2024-08-08 19:38 UTC, JacquiFreeElectron commented on app/src/state/state.ts
> +    selectedDatapacks: []
ok then I'll do unsavedDatapackConfig

2024-08-08 23:05 UTC, paologum commented on app/src/process-datapack-config.ts
> +          value.chartSettings
yeah sorry, you should set it in this function, because whenever we call this, they should be the same anyways

i didn't realize they were diff strings when i made the comment earlier but either way they should be set in this function when it finishes

2024-08-08 23:15 UTC, JacquiFreeElectron commented on app/src/process-datapack-config.ts
> +          value.chartSettings
gotcha

2024-08-10 04:17 UTC, JacquiFreeElectron commented
https://github.com/user-attachments/assets/277583ae-8058-41b3-8be7-c6e9c6be83df

2024-08-12 15:32 UTC, paologum requested changes

2024-08-12 15:32 UTC, paologum commented on app/src/App.tsx
> +            customYes="Leave Without Changes "></TSCPopupDialog>
you can just make this a single tag that closes itself (no need for `</TSCPopupDialog>` if there is an empty body

2024-08-12 15:32 UTC, paologum commented on app/src/Home.tsx
> +            actions.setIsProcessingDatapacks(false);
`setIsProcessingDatapacks` should be included in `processDatapackConfig`

2024-08-12 15:32 UTC, paologum commented on app/src/Home.tsx
> +                      actions.setIsProcessingDatapacks(false);
same here

2024-08-12 15:32 UTC, paologum commented on app/src/NavBar.tsx
> +  }; */
remove

2024-08-12 15:32 UTC, paologum commented on app/src/process-datapack-config.ts
> +import { actions, state } from "./state";
if you are using actions and state, `processDatapackConfig` should be an action.
remember we should never import state or actions unless this is an action or we use a context

2024-08-12 15:32 UTC, paologum commented on app/src/components/TSCPopupDialog.tsx
> +          {yes}
for easier readability i would have here instead of up above
`customYes ?? "Yes"`

2024-08-12 15:32 UTC, paologum commented on app/src/NavBar.tsx
> +          }}>
i think this should just be 
```
await processDatapackConfig(...)
actions.initiateChartGeneration
```

like before `processDatapackConfig` should be a contexted actions method
also `processDatapackConfig` should have the functionality that
``` 
if (JSON.stringify(state.unsavedDatapackConfig) == JSON.stringify(state.config.datapacks)) return
```

2024-08-12 15:32 UTC, paologum commented on app/src/process-datapack-config.ts
> +    fetchSettings().then((chartSettings) => {
you should just `const chartSettings = await fetchSettings()`
that way we are not unecessarily indenting a large function

2024-08-12 15:32 UTC, paologum commented on app/src/process-datapack-config.ts
> +  return new Promise((resolve, reject) => {
the promise only needs to wrap the worker.
the rest can throw errors or however
if you throw errors here, just make sure everywhere this gets used catches and pushes errors properly

2024-08-12 15:32 UTC, paologum commented on app/src/process-datapack-config.ts
> +      };
if you do the other comment's fix then you won't need this

2024-08-12 15:32 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    console.log(datapacks.length);
log

2024-08-12 15:32 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      delete state.settings.timeSettings["Ma"];
this will delete `Ma` for every datapack

2024-08-12 15:32 UTC, paologum commented on server/assets/file_metadata.json
don't commit this

2024-08-13 21:56 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
> +      delete state.settings.timeSettings["Ma"];
I think this is fine because the later code add back `Ma` if that datapack has the unit Ma: 
```typescript
if (chartSettings !== null) {
      assertChartInfoTSC(chartSettings);
      await applySettings(chartSettings);
    } else {
      // set any new units in the time
      for (const chart of columnRoot.children) {
        if (!state.settings.timeSettings[chart.units]) {
          state.settings.timeSettings[chart.units] = JSON.parse(JSON.stringify(defaultTimeSettings));
        }
      }
    }
```
I tried with TSC internal datapack & human evolution & human culture and it worked fine  (First I selected them all, the unit changed to `MA` and `KA`; then I unselected TSC internal datapack & human evolution, the unit changed to just `KA`. Then I unselected human culture as well, the unit changed back to just `Ma`; At last, I selected TSC internal datapack again, the unit remained `MA`)

2024-08-13 22:09 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      delete state.settings.timeSettings["Ma"];
ok then it should be fine, thanks for letting me know. i'll double check with `/deploy` when you finish as well

2024-08-13 22:39 UTC, JacquiFreeElectron commented on app/src/process-datapack-config.ts
> +  return new Promise((resolve, reject) => {
can I pushError in here or should I pushError where it's used

2024-08-13 22:54 UTC, JacquiFreeElectron commented on app/src/process-datapack-config.ts
> +  return new Promise((resolve, reject) => {
I now only wrap the worker in the promise, use a try-catch block to wrap that promise, and pushError when catching any error thrown by the promise, it this ok?

2024-08-14 02:24 UTC, paologum commented
/confirm-deploy

2024-08-14 02:26 UTC, paologum commented on app/src/process-datapack-config.ts
> +  return new Promise((resolve, reject) => {
yeah that works

2024-08-14 03:05 UTC, paologum requested changes

2024-08-14 03:05 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +  const { datapacks, chartSettings, stateCopy } = e.data;
you don't actually use the `chartSettings` in this function, so you should probably not send it

2024-08-14 03:05 UTC, paologum commented on app/src/state/initialize.ts
> +  actions.setIsProcessingDatapacks(false);
should remove `actions.setIsProcessingDatapacks(false);`

2024-08-14 03:05 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +  }
this needs to throw an error or set a status or value or else it will never terminate right?

2024-08-14 03:05 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +          {
you should set a timer for this webworker because otherwise this could stall forever if someone miswrites something

2024-08-14 03:24 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
>    setChartContent("");
that part is done by calling `actions.processDatapackConfig([])` when click remove cache button. bc I saw the comments said that `Resets state Only implementation is used when we remove cache` I removed the `setDatapackConfig` in here(since `setDatapackConfig()` is already called once inside `processDatapackConfig()`

2024-08-14 03:26 UTC, JacquiFreeElectron commented on app/src/state/initialize.ts
> +  actions.setIsProcessingDatapacks(false);
my bad, forgot again

2024-08-14 03:28 UTC, paologum commented on app/src/state/actions/general-actions.ts
>    setChartContent("");
yeah but if we ever wanted to call it somewhere else, you should have `processDatapackConfig` in here is what i meant instead of seperate
encapsulating as much as we can into one method is what we want for one functionality

2024-08-14 03:28 UTC, JacquiFreeElectron commented on app/src/util/workers/set-datapack-config.ts
> +  }
after I change to use `toJS` probably I don't need this part anymore. I'll check

2024-08-14 03:31 UTC, JacquiFreeElectron commented on app/src/util/workers/set-datapack-config.ts
> +  }
yeah by using` toJS` everything works fine and I can directly declare the type of `stateCopy `of `SetDatapackConfigMessage` to be `State`. So I assume we don't need assertion here anymore?

2024-08-14 03:33 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
> +          {
I think I have a timer inside the worker (in the file `set-datapack-config.ts`, a 2min timeout promise)  Isn't that already a timer?

2024-08-14 16:31 UTC, paologum requested changes
some minor things

2024-08-14 16:31 UTC, paologum commented on app/src/Home.tsx
>              actions.resetState();
this should just be in `resetState`

2024-08-14 16:31 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +  };
for easier readability can you take this out of the `onmessage` event and put it at the bottom of the file

2024-08-14 16:31 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +          {
i forgot that your fetch settings are now outside so the timer should be ok now

2024-08-14 16:31 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    )
there's a use case where if we call `processDatapackConfig([])` we don't need a loading screen because this will take no time to set variables to `[]`

so if the `datapacks.length === 0` then set the fields to what they should be on an empty config (make a different function and call it, then return)

also you should align `datapacks === state.config.datapacks` not `unsavedDatapackConfig === state.config.datapacks` here (as long as you're epassing in `unsavedDatapackConfig`

2024-08-14 16:32 UTC, paologum commented
/deploy

2024-08-14 19:47 UTC, paologum requested changes
just some really minor things but the overall code looks really good :D

2024-08-14 19:47 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +  const columnRoot: ColumnInfo = defaultColumnRoot;
`cloneDeep` otherwise the obj changes

2024-08-14 19:47 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  const columnRoot: ColumnInfo = defaultColumnRoot;
same here

2024-08-14 19:47 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    }
we want to have `setEmptyDatapackConfig` before the equality check, just for the case that even if `datapacks === state.config.datapacks` doesn't have a correct configuration of everything that `setEmptyDatapackConfig` sets we confirm reset it regardless. hopefully that makes sense
also so we can have less lines `451` and `452` should prolly be merged

2024-08-14 19:47 UTC, paologum commented on app/src/types.ts
> +} */
comment

2024-08-14 20:18 UTC, paologum commented on app/src/util/workers/set-datapack-config.ts
> +  }
nope we should be good

2024-08-15 03:54 UTC, paologum approved these changes
nice, looks great!

2024-08-15 04:42 UTC, merged