Tsc 485 event search minor changes
earthhistoryviz/tsconline pull request #227
Opened 2024-08-10 20:23 UTC by jay-jhk-lee

Changed label of "status" column to "column on?"
changed label of "qualifier" to "type"
changed time display to a table for line up

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/28a13e33-97bb-4f30-983f-1c8671bfad28">

2024-08-12 16:28 UTC, paologum commented
/deploy

2024-08-12 16:29 UTC, paologum commented
/confirm-deploy

2024-08-14 20:05 UTC, paologum commented
/confirm-deploy

2024-08-14 20:13 UTC, paologum commented
it probably would make more sense to align text to the left
## `text-align: left`

<img width="232" alt="Screenshot 2024-08-14 at 4 12 37 PM" src="https://github.com/user-attachments/assets/8794ff7e-5e4b-4170-9178-08c8aa123f3a">

## `text-align: right`
<img width="241" alt="Screenshot 2024-08-14 at 4 12 51 PM" src="https://github.com/user-attachments/assets/c79b0d77-f453-4930-9711-19408810bab6">

2024-08-14 20:15 UTC, paologum commented
probably atp we might just want to have two cells for `Top` and `Base` and potentially put it on the left or right but we can do that/reconvene on that later

2024-08-16 15:56 UTC, paologum commented
/confirm-deploy

2024-08-21 02:12 UTC, jay-jhk-lee commented
changed alignment of times
<img width="220" alt="image" src="https://github.com/user-attachments/assets/7a01cfbb-dc8f-4b13-9962-feb9842c084f">

2024-08-22 01:12 UTC, paologum requested changes

2024-08-22 01:12 UTC, paologum commented on app/src/settings_tabs/Search.css
> +  resize: both;
you should add a `max-height` and `max-width` so that they can't expand it to the whole page

2024-08-22 15:07 UTC, paologum approved these changes

2024-08-23 00:13 UTC, merged