Update server.md to include decrypter info
earthhistoryviz/tsconline pull request #228
Opened 2024-08-12 09:36 UTC by Changk820

2024-08-12 16:26 UTC, paologum requested changes

2024-08-12 16:26 UTC, paologum commented on server.md
> +To ensure the server starts correctly, this JAR file must be placed in the `tsconline/server/assets/jars` directory alongside the active server JAR file. Additionally, the JAR file and its input argu
this is not true it's labeled in a .gitignored `admin-config.json` file

2024-08-12 16:26 UTC, paologum commented on server.md
> +To create the decryption JAR file, use Maven.
add a note or whatever here that this is within the bitbucket repo since they could think this is seperate from above or something. just to clarify

2024-08-14 16:00 UTC, Changk820 commented on server.md
> +To ensure the server starts correctly, this JAR file must be placed in the `tsconline/server/assets/jars` directory alongside the active server JAR file. Additionally, the JAR file and its input argu
I think other places might still say config.json instead of admin-config.json. I changed mine, but I'm not sure if other areas should also be changed since we have two sites.

Is this readme supposed to be for future VIP students or the deepearth people?

2024-08-14 16:15 UTC, paologum commented on server.md
> +To ensure the server starts correctly, this JAR file must be placed in the `tsconline/server/assets/jars` directory alongside the active server JAR file. Additionally, the JAR file and its input argu
anyone really, it's just meant as a documentation for anyone who wants to run/dev on this code

2024-08-14 16:16 UTC, paologum approved these changes

2024-08-14 20:16 UTC, merged