Tsc 503 create workshops
earthhistoryviz/tsconline pull request #245
Opened 2024-08-31 23:55 UTC by asivath

https://github.com/user-attachments/assets/4bde97f5-42ba-4349-9937-2cdcd3e478f1

2024-09-01 03:22 UTC, paologum commented
/confirm-deploy

2024-09-01 12:01 UTC, paologum requested changes
some small things

2024-09-01 12:17 UTC, paologum commented
## Front end comments

- The font colors at least on dark mode are contrasting, so idk if there is a dark theme like there is for `aggrid` but those have to be contrasted because i can't see the days

<img width="846" alt="Screenshot 2024-09-01 at 9 08 59 PM" src="https://github.com/user-attachments/assets/c2354662-9def-43be-8dd7-45aec30685cb">

- can you also add workshop id to the display of users

2024-09-01 13:54 UTC, asivath commented on server/db/migrations/2024.08.25-18.18.31-add-workshop-changes.ts
> +    .addColumn("title", "text", (col) => col.notNull().unique())
rn workshops gets deleted when the end date passes, so he could reuse titles after the end. do we want to allow the same titles for active workshops? or do we actually want to delete past workshops?

2024-09-02 11:15 UTC, paologum commented on server/db/migrations/2024.08.25-18.18.31-add-workshop-changes.ts
> +    .addColumn("title", "text", (col) => col.notNull().unique())
ideally we probably would want to keep a history of workshops to maybe keep track of statistics or the like or for users to see a history of previous workshops and how others did or the like

you could make it so that the main workshops table is active workshops and then another table for history where title isn't unique. idk if it's better or worse separating the two, but they are both possibilites

2024-09-03 01:02 UTC, asivath commented on server/db/migrations/2024.08.25-18.18.31-add-workshop-changes.ts
> +    .addColumn("title", "text", (col) => col.notNull().unique())
will be added in another PR

2024-09-03 01:05 UTC, asivath commented
![image](https://github.com/user-attachments/assets/7281d1f3-188e-478c-8621-7b68369f76c2)

2024-09-03 13:29 UTC, paologum commented
probably should have a local host bypass for these

<img width="1274" alt="Screenshot 2024-09-03 at 10 29 07 PM" src="https://github.com/user-attachments/assets/1393b90c-e193-4863-88e6-aef1f551f7a7">

2024-09-06 16:02 UTC, Changk820 commented
/confirm-deploy

2024-09-10 06:51 UTC, paologum requested changes

2024-09-10 06:51 UTC, paologum commented on .github/workflows/deploy-release.yml
> +            echo 'AES_IV="${{ secrets.AES_IV }}"' >> ./server/.env
remove

2024-09-10 06:51 UTC, paologum commented on .github/workflows/deploy-dev.yml
> +            echo 'AES_IV="${{ secrets.AES_IV }}"' >> ./server/.env
remove (unless something else uses it but i don't think so)

2024-09-11 04:01 UTC, merged