Added additional info to database profile
earthhistoryviz/tsconline pull request #246
Opened 2024-09-01 15:16 UTC by lbostre

![08ef30e6458e1d121e5c346b748ff8a8](https://github.com/user-attachments/assets/b833e10a-67db-4933-8946-49b527f61b8c)
![7a67e6dfac948034be59a30fc5719b83](https://github.com/user-attachments/assets/a985fad4-763d-4e9f-9dda-6c2d91adbdd6)

Added additional data pack information including contact, notes, and column type count.

2024-09-02 11:26 UTC, paologum commented
for the piechart can you change the title to be `Number of Columns` and also make it so the slices have little slivers/borders between them. also can you add either a table or some sort of display so that someone can see the exact numbers (not percents but you could do both thought idk if that would look good). you could additionally add it as a subtitle of the slice label
 (like below) example is mainly for the gap and the extra label not really emphasizing the pie vs donut both look good

<img width="341" alt="Screenshot 2024-09-02 at 8 25 33 PM" src="https://github.com/user-attachments/assets/2c1759a0-f4fb-4c20-a329-e2acaf2dc106">

2024-09-02 11:31 UTC, paologum commented
/confirm-deploy

2024-09-02 12:04 UTC, paologum commented
on my local, the only display is one point as well

<img width="611" alt="Screenshot 2024-09-02 at 9 03 48 PM" src="https://github.com/user-attachments/assets/df3735d9-2973-494c-a801-347e738d100f">

2024-09-02 12:28 UTC, paologum requested changes
some comments

2024-09-02 12:28 UTC, paologum commented on app/src/DatapackProfile.tsx
> +      })
is this a hard coded coordinate to where the graph sits on the whole page? if that's the case it would be a little annoying to change if we decided to move the graph somewhere else or use this chart somewhere else with different data. unless this is representative of the svg's width and height then it should be fine

2024-09-02 12:28 UTC, paologum commented on app/src/DatapackProfile.tsx
> +      tooltip.remove();
you probably want to clean up (remove all of the svg) on unmount too

2024-09-02 12:28 UTC, paologum commented on app/src/DatapackProfile.tsx
> +      })
you should also probably add some pictures at different window/screen sizes

2024-09-02 12:28 UTC, paologum commented on app/src/DatapackProfile.tsx
> +      .attr("class", "tooltip")
this is a class that is pretty generic and could get accidentally affected by other class names in the repo so you might want to make this more specific. unless i'm understanding incorrectly and this is an inherent class in d3

2024-09-02 13:14 UTC, lbostre commented on app/src/DatapackProfile.tsx
> +      })
those values are hard-coding the offset of the tooltip from the cursor whenever the user hovers over the chart

2024-09-02 13:17 UTC, paologum commented on app/src/DatapackProfile.tsx
> +      })
ok as long as the tooltip works on different screen sizes this is fine

2024-09-02 13:17 UTC, lbostre commented
> on my local, the only display is one point as well (checked for each datapack and it's the same) it does work on `pr-preview.geolex.org` but on local it's weird for me i'm not sure if you have input on the below
> <img alt="Screenshot 2024-09-02 at 9 03 48 PM" width="611" src="https://private-user-images.githubusercontent.com/89664317/363681483-df3735d9-2973-494c-a801-347e738d100f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODA5MDgsIm5iZiI6MTcyNTI4MDYwOCwicGF0aCI6Ii84OTY2NDMxNy8zNjM2ODE0ODMtZGYzNzM1ZDktMjk3My00OTRjLWE4MDEtMzQ3ZTczOGQxMDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNWMzNTE1Y2Q3ZTFhYjFiYmMwZDAzMTVjYTJlYzhjM2RjZGRmM2EwNzk2NTcwNDYyMGQxM2VmMzFjMTY1MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.325WlQ1wn8vSsuDMhfCz2zddei36VkCH1ml7ke5dpLo">
> Screen.Recording.2024-09-02.at.9.07.42.PM.mov

Ya I'm not sure why this could be happening. What I have found on my local is that every chart has these same values, which is also odd.
![cc780be793eb7f88f575118e5e0cddb3](https://github.com/user-attachments/assets/e7a4ee23-c242-438a-baca-8ed1245436c3)

2024-09-10 06:47 UTC, paologum approved these changes
looks good!

2024-09-13 15:37 UTC, merged