Tsc 502 workshop priority during workshop
earthhistoryviz/tsconline pull request #258
Opened 2024-09-13 13:44 UTC by asivath

Besides priority I did a little refactoring and also added the workshopTItle on session check which I forgot to add in last PR

2024-09-17 14:13 UTC, paologum commented on server/src/routes/login-routes.ts
> +    }
what if instead of actually deleting the workshop, we keep all workshops in the same table and just have a field marked `status`  with flags `expired` and `active`
whenever you add, you just enforce that `active` workshops have unique titles and that way whenever you get from the `workshop` table for users you don't have the additional overhead of removing it from the `workshop` table and adding it to the `workshop history` table

2024-09-17 19:08 UTC, asivath commented on server/src/routes/login-routes.ts
> +    }
i forgot about this but aaron said that workshop titles shouldn't be unique, so I got rid of that now. I added the status column with an extra flag `inactive`

2024-09-17 19:18 UTC, asivath commented on server/src/routes/login-routes.ts
> +    }
also what is our process for updating things that have been translated, or adding new things that need translation

2024-09-18 16:24 UTC, paologum requested changes

2024-09-18 16:24 UTC, paologum commented on server/db/migrations/2024.05.08-17.59.45-adjust-columns-in-verification-table.ts
>    if (oldData.length != 0) await db.insertInto("verification_new").values(oldData).execute();
ok now i see what you should do, so shouldn't you change this to that?

2024-09-18 16:24 UTC, paologum commented on server/db/migrations/2024.09.17-10.58.43-drop-unique-constraint-for-workshop-title.ts
> +    for (const workshop of nonUniqueWorkshops) {
wouldn't you want the up to use this if it has a workshop backup?

2024-09-18 16:24 UTC, paologum commented on shared/src/index.ts
> +  active: boolean;
is there a reason that this isn't just the text status?
what if we want to specifically edit the status itself? i assume you did this for easier readability but if we edit workshops and we want to make a workshop inactive by editing it in the future route you will make won't this make it really difficult to discern if the `SharedWorkshop` itself doesn't have the status, so you will have to grab the workshop and have extra logic?

2024-09-18 16:24 UTC, paologum commented on server/src/database.ts
> +  - status (string): Non-nullable, default is 'expired', indicates if the workshop is status or not. Possible values are 'status' and 'expired'.
change title to not have must be unique

2024-09-18 16:24 UTC, paologum commented on server/src/database.ts
> +    .returning("workshopId")
is it normal to update statuses on get requests to a table?
will this make overhead on those requests bigger than they need to be?

2024-09-18 16:31 UTC, paologum commented on server/src/routes/login-routes.ts
> +    }
i uploaded an excel file for new translations, we can add the other ones, but you can add new ones you make there and we can add the translations there so that we know things are done

2024-09-19 14:12 UTC, asivath commented on server/db/migrations/2024.05.08-17.59.45-adjust-columns-in-verification-table.ts
>    if (oldData.length != 0) await db.insertInto("verification_new").values(oldData).execute();
previous migrations are not supposed to be changed. it doesn't really matter anyway since all migrations are past this point

2024-09-19 14:35 UTC, asivath commented on shared/src/index.ts
> +  active: boolean;
i don't see a reason to let them edit the status from the frontend. the only real things someone should be able to edit are it's names and start/end time. it would make it easier to sort the workshops into categories on the frontend though so I'll add it.

2024-09-19 14:52 UTC, paologum commented on shared/src/index.ts
> +  active: boolean;
i mean isn't the point of making it inactive but not expired to archive it until you decide on the exact time/ are undecided about items in the workshop, or maybe some other reason? not necessarily that you wanna delete it persay

2024-09-19 14:54 UTC, asivath commented on server/src/database.ts
> +    .returning("workshopId")
the alternative is doing two database calls instead of one which would involve more overhead. I don't think overhead is a concern anyway since this is not something a normal user would use and we're not going to be having tons of workshops. also this is likely to change in Jacqui's PR since the reason this is needed is to update users, but that won't be a thing in her PR.

2024-09-19 14:57 UTC, paologum commented on server/src/database.ts
> +    .returning("workshopId")
how do we connect the user to a workshop in that pr again?

2024-09-19 15:12 UTC, asivath commented on server/src/database.ts
> +    .returning("workshopId")
we would instead store user id's in the workshop table and if we wanted to know if a user was in a workshop we would perform a join

2024-09-19 15:14 UTC, paologum commented on server/src/database.ts
> +    .returning("workshopId")
ok i guess that's okay then since jacqui's pr will take it out, and i'm assuming then the only updates to the status would be in crons?

2024-09-19 15:16 UTC, asivath commented on shared/src/index.ts
> +  active: boolean;
inactive is meant for before the workshop has started, active is during the workshop, and expired is after the workshop. if you wanted to archive it or just keep it there, then you would just set a time far in the future., which you would have to do anyway to create the workshop

2024-09-19 15:25 UTC, asivath commented on server/src/database.ts
> +    .returning("workshopId")
if we did it with crons it would get kind of complicated. we would need to avoid redundant cron jobs, edit cron jobs when workshop times get edited, hard to detect failures. i think updates should be done whenever we try to fetch the data

2024-09-19 15:31 UTC, paologum commented on server/src/database.ts
> +    .returning("workshopId")
hmm okay have you asked aaron about this?
this means every time any user wants to see what workshop they might be signed up to (in the future) we would check all the workshops? doesn't that seem like a ton of checks if we have users see their status?
for example with like 50 users and 10 workshops and with potential refreshing during a workshop, couldn't workshops cause the server to go crazy if they are all accessing and checking workshops?

2024-09-19 15:44 UTC, asivath commented on server/src/database.ts
> +    .returning("workshopId")
i haven't talked to aaron about this but i don't think 50 users and 10 workshops is a crazy amount. better-sqlite3 is supposed to be able to handle thousands of queries per second, so the database itself wouldn't be the bottleneck

2024-09-19 15:46 UTC, asivath commented on server/src/database.ts
> +    .returning("workshopId")
we could of course test this though with the stress test script and edit it to just keep trying to log in and get data.

2024-09-20 04:26 UTC, paologum commented on shared/src/index.ts
> +  active: boolean;
hmm i feel like we should be more specific still about these statuses for clear usage when they happen
active -> during time frame
inactive -> not during time frame but not expired
archived -> show up in history or when you get all workshops but has the content decided but not the date/time ( this would not be shown to users for signing up, only for admins)
expired -> finished workshop

there is a use case i see where professor ogg might know the content and has datapacks planned but is not yet sure on when due to availability of himself or others if that makes sense. that use case would best fit into inactive but it depends on you picking a far fetched date and remembering that it's not actually scheduled for then at the same time

2024-09-23 16:40 UTC, paologum commented on shared/src/index.ts
> +  active: boolean;
is there a reason for this since aaron said this is duplicate information?
since i'm assuming we could check active from `start` and `end`

2024-09-24 01:11 UTC, asivath commented on shared/src/index.ts
> +  active: boolean;
aaron was talking about duplicate information in the db that would lead to needing to make updates in the db on fetches but i think sending this information to the frontend is fine since it makes it easier. the dates sent to the frontend are not normal date strings so they would have to be parsed into a different format than compared.

2024-09-24 01:55 UTC, paologum approved these changes

2024-09-24 01:55 UTC, merged