Tsc 528 edit workshop
earthhistoryviz/tsconline pull request #267
Opened 2024-10-01 23:50 UTC by asivath

https://github.com/user-attachments/assets/f836c215-0398-4cd3-8f1f-711d0af996cf

2024-10-02 13:48 UTC, paologum commented
/confirm-deploy

2024-10-02 16:44 UTC, asivath commented
/confirm-deploy

2024-10-03 11:06 UTC, paologum requested changes

2024-10-03 11:06 UTC, paologum commented on server/src/admin/admin-routes.ts
> +    }
so now we are allowing identical titles ?

2024-10-03 11:06 UTC, paologum commented on server/src/admin/admin-routes.ts
> +      if (isNaN(endDate.getTime()) || startDate.getTime() > endDate.getTime()) {
this should probably also not allow `start` and `end` to be the same time right

2024-10-03 13:35 UTC, asivath commented on server/src/admin/admin-routes.ts
> +    }
i can move it below the start check, but the end check needs the db query incase they don't give a start date

2024-10-03 16:28 UTC, paologum commented on server/src/admin/admin-routes.ts
> +    }
so now we can basically have the same workshop as long as one of the fields is different

2024-10-03 16:30 UTC, paologum approved these changes

2024-10-03 16:57 UTC, merged