Tsc 537 dual column comparison backend
earthhistoryviz/tsconline pull request #268
Opened 2024-10-03 19:31 UTC by jay-jhk-lee

Added properties to event and point column for dual column comparison
Loading settings with DCC column works
Modified parsing to accommodate new properties

bug: overlaying event onto point seems to not work, will have to modify jar file

2024-10-27 14:26 UTC, paologum requested changes
i'm trying to get the pr-preview up for this but these are my comments

2024-10-27 14:26 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  const dualColCompColumnName = "Overlay for " + column.editName;
everytime you use the structure `Overlay for` can you abstract it to a constant somewhere and additionally call a function instead of constructing your self so like `const dualColCompColumnName = getDualColCompColumnName(column.editName)`
this makes it easier to change in the future if it presents problems

2024-10-27 14:26 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +    console.log("WARNING: ", column.name, "not found in parent's children when attempting to add data mining column");
can you make these warnings instead of logs

2024-10-27 14:26 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +const dualColCompRefCache = new Map<string, string>();
can you add that the found cache is found in the raw settings xml and the ref is a reference with a different column in the comments because other than me or you it might be confusing

2024-10-27 14:26 UTC, paologum commented on app/src/state/parse-settings.ts
> +      if (typeof keyValue !== "string") continue;
you can just put :688 into :687

2024-11-11 16:30 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +      if (typeof keyValue !== "string") continue;
if i combine the two conditions, then if keyValue is null it will move to the final else statement where it will print the wrong thing.

2024-11-20 05:06 UTC, paologum requested changes
can you upload a demo, also is dual comp  the same/similar to overlay? if it is you need to remove it from `drawExtraColumn`

2024-12-30 23:23 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +      }
We can't nest them since they won't always be true for a specific column. The `isDualColCompColumn` is a property of a column like `isDataMiningColumn` and `drawDualColCompColumn` is the equivalent of `drawExtraColumn` except with the column id. So usually a column with `isDualColCompColumn` won't have `drawDualColCompColumn` and vice versa unless it goes deeper.

2024-12-30 23:23 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +    //remove any access dual col comp column (a column can only have one)
yeah

2024-12-30 23:53 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +    });
You're right, I changed the string comparison and changed the remove logic

2024-12-31 14:46 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
but hypothetically we could make one right if we dual col comped with a dual col comp?

2024-12-31 17:14 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +      }
yeah

2024-12-31 18:26 UTC, paologum commented
/confirm-deploy

2024-12-31 18:51 UTC, jay-jhk-lee commented
https://github.com/user-attachments/assets/7c33ac9a-422a-4b98-96c7-5051c62c9018

2024-12-31 20:03 UTC, paologum requested changes

2024-12-31 20:03 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +        continue;
ok i see you fixed the positive issue but the other questions i still want to know

2024-12-31 21:50 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +        continue;
The first compare is to prevent removing the correct dcc. Since the `add dcc` function inserts it right below the ref col, we know that one is correct and can skip it. Adding two will prevent it from comparing and removing the correct dcc in the second comparison. The second compare is to remove any dcc that was there before loading the settings.

2024-12-31 21:52 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +        continue;
the refcol.name could be a dcc column, but it isn't the dcc column that is created in this context.

2025-01-02 14:31 UTC, paologum requested changes

2025-01-02 14:31 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +      }
i feel like instead of assuming, we also check the dcc's existence after the ref column to be robust.

2025-01-03 01:43 UTC, jay-jhk-lee commented on app/src/state/actions/column-actions.ts
> +      }
yep I changed the logic again, should be better now

2025-01-03 03:23 UTC, paologum approved these changes

2025-01-03 03:40 UTC, merged