Tsc 487 datapack tab between chart and settings
earthhistoryviz/tsconline pull request #270
Opened 2024-10-04 04:24 UTC by Michael-Knaack

Added a Datapack tab between the home icon and chart tab on the navbar.  Works in both languages.

2024-10-05 04:41 UTC, paologum commented
/deploy

2024-10-05 04:48 UTC, paologum requested changes
i think it should be before charts not after it

also make sure you upload images of what you changed on the front end whenever you make a pr

<img width="641" alt="Screenshot 2024-10-05 at 1 48 00 PM" src="https://github.com/user-attachments/assets/2f0881e8-6260-40d7-8380-cf47ed4f4eb9">

2024-10-11 05:18 UTC, Michael-Knaack commented
![Screenshot 2024-10-11 011453](https://github.com/user-attachments/assets/3dec5da7-9c83-4154-a983-b996a816d291)
Swapped the location of datapacks on navbar

2024-10-13 11:02 UTC, paologum commented
i'll add the comment here but the meeting saw some bugs when selecting from the settings hover submenu and when generating a chart, the tab selected was incorrect, so you'll probably need to fix those things before you merge

2024-10-14 16:14 UTC, paologum commented
/deploy

2024-10-14 17:03 UTC, paologum commented
/deploy

2024-10-15 06:16 UTC, paologum commented
there's another small bug

https://github.com/user-attachments/assets/66e1c911-e1ea-442b-a8dd-6d4e45e79f2b

we monitor changes in settings that differ from the generated chart and push a snackbar that reflects that in the video above. since the tab changed, you'll also need to change the monitored tab that pushes the snackbar
i would suggest looking up that string to see where it is located in the repo

2024-10-15 06:20 UTC, paologum commented
one more thing is, and this might be slightly complicated but because we have a new "route" for datapacks, we need to show the discard,save changes on route changes so changing from `/datapack` to `/chart` or any difference in settings tab

for more context on this you can visit `DatapackProfile.tsx`

and look at this code
```
  useBlocker(
    ({ currentLocation, nextLocation }) =>
      isMountedRef &&
      state.datapackProfilePage.unsavedChanges &&
      currentLocation.pathname !== nextLocation.pathname &&
      !window.confirm(t("dialogs.confirm-changes.message"))
  );
  // for when user tries to leave page with unsaved changes
  useEffect(() => {
    const handleBeforeUnload = (event: BeforeUnloadEvent) => {
      if (state.datapackProfilePage.unsavedChanges) {
        event.preventDefault();
        event.returnValue = "";
      }
    };
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, [state.datapackProfilePage.unsavedChanges]);
```
you may want to ask me, aditya, or jacqui if you have trouble with this or want more context

https://github.com/user-attachments/assets/eef594ca-c64c-4769-99c0-2a9ad92ecac6

2024-10-25 13:56 UTC, paologum commented
/confirm-deploy

2024-11-05 10:35 UTC, paologum commented
/confirm-deploy

2024-11-05 10:42 UTC, paologum commented
in this video, you can see a slight popup of the confirm changes when you generate a chart using a preset

https://github.com/user-attachments/assets/168ba37c-da47-4327-92b7-71fd1c6840b6

2024-11-05 10:47 UTC, paologum commented on app/src/App.tsx
> +      return true;
there is an `isProcessDatapacks` boolean you can access that will not have that popup if it is currently configuring the new configuration

2024-11-08 04:51 UTC, paologum commented
/confirm-deploy

2024-11-08 06:10 UTC, paologum approved these changes

2024-11-08 06:10 UTC, merged