Tsc 538 allow user to be in multiple workshops
earthhistoryviz/tsconline pull request #272
Opened 2024-10-07 05:17 UTC by JacquiFreeElectron

### What's done: 

- created a joint table `usersWorkshops` to support many-to-many relationships between users and workshops
- dropped `workshopId` column from `users` table 
- implemented the frontend of edit and display user info / user-workshop relationships
- ~~instead of updating user, the handling ended workshops function now updates the `workshopHasEnded` in the `usersWorkshops` table~~

### What's not done:

- backend routes of edit user info
- need to add some test cases for add/delete user-workshop relationships

2024-10-07 15:10 UTC, paologum commented
add some demos

2024-10-07 15:50 UTC, paologum requested changes

2024-10-07 15:50 UTC, paologum commented on app/src/admin/AdminEditUserForm.tsx
> +  const [openConfirmDialog, setOpenConfirmDialog] = useState(false);
can you make a seperate hook for all the state and handlers? then export it similar to `datapack-upload-form-hook.ts`

2024-10-07 15:50 UTC, paologum commented on app/src/admin/AdminEditUserForm.tsx
> +    setIsEditing(false); // Quit edit mode
these handlers should also go there, i'm looking at this from an out perspective but i think it should be easily doable? you might need to pass in a few things, then you can return like `handlers, setters, state`

below too

2024-10-07 15:50 UTC, paologum commented on server/src/admin/admin-routes.ts
> +      // workshopId: 0
comment

2024-10-07 15:50 UTC, paologum commented on server/src/admin/admin-routes.ts
> +          }
for robustness just make it an else

2024-10-07 15:50 UTC, paologum commented on server/src/admin/admin-routes.ts
> +          createUsersWorkshops({ userId: userId, workshopId: workshopId, workshopHasEnded: 0 });
you don't need an await here?

2024-10-07 15:50 UTC, paologum commented on server/db/migrations/2024.09.22-14.19.29-add-users-workshops-join-table.ts
> +    .addColumn("workshopHasEnded", "integer", (col) => col.notNull().defaultTo(0))
i don't think this would be a good idea, because if we do this then everytime we edit the workshop (if we bring a past workshop to the front, we will have to check all of the users that have that workshop and edit them)
this could be something we want though but i feel like we can just check on the front end with all the workshops
aditya also might have thoughts on this

2024-10-07 15:50 UTC, paologum commented on server/src/admin/admin-routes.ts
> +            }
what do you think about splitting up workshops and users into two different routes
you can't actually see workshops until you open the form, so maybe it would be a good idea to not send workshop data until we need it. i'm not sure if the difference is negligible enough for us to just have it here though so let me know what you think.

2024-10-07 15:50 UTC, paologum commented on server/src/routes/login-routes.ts
> +      // workshopId: 0
comment

2024-10-07 15:50 UTC, paologum commented on server/src/routes/login-routes.ts
> +      //workshopId: 0
comment

2024-10-07 15:50 UTC, paologum commented on server/src/types.ts
> +  //workshopId: number;
comment

2024-10-07 15:50 UTC, paologum commented on shared/src/index.ts
> +  workshopTitle?: string[];
i would rename this `workshopsEnrolled`
for better understanding

2024-10-07 15:50 UTC, paologum commented on server/src/database.ts
> +
remove `workshopId` from these comments

2024-10-12 21:39 UTC, JacquiFreeElectron commented
https://github.com/user-attachments/assets/dadee106-77d2-417d-b106-5884a4927d33

2024-10-13 16:47 UTC, paologum requested changes
the "graduation icon" should be before registered workshops, not before each workshop entry

2024-10-13 16:47 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +      const updatedWorkshops = currentWorkshops.filter((workshop) => workshop !== selectedWorkshop);
workshops can have the same name,
but they have to be unique in terms of end/start date AND name so this will not filter correctly for workshops of the same name

2024-10-13 16:47 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  };
you should show me a demo of the profile pic uploading
additionally if they upload pro pic, it shouldn't preview after save changes, it should be previewed immediately after upload

2024-10-13 16:47 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  };
to make this type safe, i would make a type on the front end that is like `EditableUserProperties` then set the type of the state of `UserInfo` and make sure that key `e.target.name` exists  in that type then set it

for dev robustness

2024-10-13 16:47 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  };
shouldn't save changes also set original user info

2024-10-13 16:47 UTC, paologum commented on shared/src/index.ts
> +  workshopEnrolled?: string[];
small thing but this needs to be `workshopsEnrolled` because it's multiple workshops

2024-10-13 16:47 UTC, paologum commented on shared/src/index.ts
> +  workshopEnrolled?: string[];
because titles are not unique as well, you might have to include more for uniqueness

2024-10-13 16:49 UTC, paologum commented on server/src/admin/admin-routes.ts
> +            createUsersWorkshops({ userId: userId, workshopId: workshopId });
await?

2024-10-18 00:45 UTC, JacquiFreeElectron commented
https://github.com/user-attachments/assets/cf644984-7df9-4484-b1e0-cbbf9f5532d2

2024-10-18 08:12 UTC, paologum commented
/confirm-deploy

2024-10-18 09:17 UTC, paologum requested changes
there is something i might bring up in the meeting,
if we just remember which workshops that the admin deletes and DON'T put up a dialog until they press save changes or go through the unsaved changes dialog
that way they won't have to continuously press buttons for multiple deletions

2024-10-18 09:17 UTC, paologum commented on server/src/admin/admin-routes.ts
> +            return;
do you need to throw an error if the user is already in the workshop? i don't think you need to, you could just continue because they already are a part of the workshop? @asivath

2024-10-18 09:17 UTC, paologum commented on server/src/admin/admin-routes.ts
> +            return;
also if you added test remove the TODO, if you haven't yet, then write the test

2024-10-18 09:17 UTC, paologum commented on server/__tests__/admin-routes.test.ts
> +          ] //
// at the end

2024-10-18 09:17 UTC, paologum commented on server/__tests__/admin-routes.test.ts
>    it("should return 200 if successful and update old users", async () => {
add test for when `checkWorkshopHasUser` (mentioned above) here is already in the junction table

2024-10-18 09:17 UTC, paologum commented on server/__tests__/admin-routes.test.ts
>    it("should return user with workshopTitle and one without", async () => {
change this test title to reflect the test

2024-10-18 09:17 UTC, paologum commented on server/src/admin/admin-routes.ts
> +            if (workshop[0]?.title) {
add these into the same if statement

2024-10-18 09:17 UTC, paologum commented on server/__tests__/admin-routes.test.ts
>    it("should return 200 if successful and update old users", async () => {
additionally you should add your expect checks to adding new users, not just updating old ones. (the test above) `should return 200 if successful and add new users`

2024-10-18 09:17 UTC, paologum commented on server/__tests__/admin-routes.test.ts
also need tests for 
```
 if (newRelationship.length !== 1) {
              reply.status(500).send({ error: "Error adding user to workshop", invalidEmails: email });
              return;
            }
```
when a new user is added and the other case when updating a user

2024-10-18 09:17 UTC, paologum commented on server/src/admin/admin-routes.ts
> +              reply.status(500).send({ error: "Error adding user to workshop", invalidEmails: email });
also @asivath if the first email is invalid for this reason, do we want to return all unadded emails or just the bad email and don't tell them the ones not added by not adding them to `invalidEmails`
i think we talked about this but i forgot what you had said

2024-10-18 09:17 UTC, paologum commented on server/db/migrations/2024.09.22-14.19.29-add-users-workshops-join-table.ts
i can't bring up the pr preview because this migration is behind main since leyton pushed his migration which means this migration doesn't come next chronologically, it comes after leytons. so can you recreate this migration file to today's date so it comes after leyton since leyton is `CANON` now

2024-10-18 09:21 UTC, paologum commented on server/src/routes/login-routes.ts
> +        workshopsEnrolled.push(workshopEnrolled);
going to ask this in the meeting but i'll record my idea here for the time being, but i'm not sure if we need to have `WorkshopsEnrolled` on general users data.
We might just want to attach workshop ids then combine the two on the frontend because we will probably have to store all public workshops on the front end anyway

2024-10-23 01:45 UTC, JacquiFreeElectron commented
https://github.com/user-attachments/assets/2fd41330-c304-40a9-9b45-77df49732423

2024-10-23 14:07 UTC, paologum commented
/confirm-deploy

2024-10-23 15:33 UTC, paologum requested changes
<img width="887" alt="Screenshot 2024-10-23 at 11 51 19 PM" src="https://github.com/user-attachments/assets/babf29f8-90f3-4ac3-81a7-58433cc89107">

dark mode should toggle like the others

<img width="876" alt="Screenshot 2024-10-23 at 11 55 27 PM" src="https://github.com/user-attachments/assets/d5cdd718-5575-4d03-8ba1-0a9da2891e36">

should change when you change the theme, but here is a person with a workshop in dark mode

2024-10-23 15:33 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +    }
this method seems slightly confusing to me with how it's named and with the discard confirmed term used

i think you should just split this method into two methods, one that executes a discard changes action and just call it `discardChanges` and then the other case is not very clear so you might need to explain it for me

and also maybe could you explain why you chose this approach vs splitting into more defined functions

2024-10-23 15:33 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +      }
instead of having to remember to each `closeDialog` time with a variable that refreshes state, you should just add `setShowAdditionalUserInfoFormOpen` to `false` in each `handler` function that needs it.

2024-10-23 15:33 UTC, paologum commented on shared/src/index.ts
> +  workshopsId?: number[];
`workshopIds`

otherwise `workshopsId` represents one workhop's id so it conveys a different meaning

2024-10-23 16:34 UTC, asivath commented on server/src/admin/admin-routes.ts
> +          const existingRelationship = await checkWorkshopHasUser(userId, workshopId);
the variable `user` should always be only one user since email has to be unique, so this loop isn't needed

2024-10-23 16:34 UTC, asivath commented on server/src/admin/admin-routes.ts
> +              reply.status(500).send({ error: "Error adding user to workshop", invalidEmails: email });
currently, before even starting to add/edit users in the database, we check for any invalid emails and just send invalid emails without adding any. this is slightly different since this could happen halfway through adding to the db. I think it would make more sense to continue with the batch update rather than stopping, and then send the invalidEmails at the end

2024-10-23 16:34 UTC, asivath commented on server/src/admin/admin-routes.ts
> +        }
same comment about the loop

2024-10-23 16:34 UTC, asivath commented on server/src/types.ts
> +export type newUsersWorkshops = Insertable<UsersWorkshopsTable>;
capitalize this. also @paologum do you think we would ever need to update this table, or just deleting/creating?

2024-10-23 16:34 UTC, asivath commented on server/src/database.ts
> +}
same

2024-10-23 16:34 UTC, asivath commented on server/src/database.ts
> +}
you can combine these

2024-10-24 23:42 UTC, JacquiFreeElectron commented on app/src/components/edit-user-stats-hook.ts
> +    }
I built upon the existing code, as there was initially only one function managing whether the "Are you sure" dialog should open or not. I can split this into two parts for sure—one part to showing the dialog (one function) and the other part to handle the discard process. And as you suggested below I’ll create separate handler functions for each type of discard request (since each discard has a different effect depending on where it was triggered) instead of using a single function for all discards. But I think I still need to pass in some kind of boolean value to the `showDialog` handler so that it knows which ` discardChange` handler to call. Lmk if I’ve misunderstood anything or you have any better idea

2024-10-24 23:49 UTC, JacquiFreeElectron commented on server/src/admin/admin-routes.ts
> +        }
So this is what I should do:
1. Process the users and add/edit them in the database, if some emails are invalid, skip it and continue the loop.
2. Keep track of the invalid emails while process the users.
3. Once all users have been processed, return a response that includes the invalid emails (if any).
Is this correct?

2024-10-25 14:15 UTC, asivath commented on server/src/admin/admin-routes.ts
> +        }
yes

2024-10-27 02:12 UTC, JacquiFreeElectron commented on app/src/components/edit-user-stats-hook.ts
> +    }
After further consideration, I ended up with two "are you sure" dialogs (with the same content). I couldn't find a way to pass the correct handler function for different situations without using a state variable to keep track of closeDialog (now renamed to closeForm, since it actually closes the entire form). The issue arises because both clicking the close button of the form and clicking the discard button trigger showDiscardDialog, making it difficult to identify which action opened the dialog. Using a boolean or state variable felt similar to the previous approach, so I decided that a better solution would be to use two separate components, allowing me to assign different handlers to onYes. However, I still need a state variable to determine which dialog should be displayed—one dialog uses open={editState.showDiscardDialog}, while the other uses open={editState.showDiscardDialogAndCloseTheForm}. Overall, I find this approach to be more readable. what you think of this approach

2024-10-27 02:23 UTC, JacquiFreeElectron commented on app/src/components/edit-user-stats-hook.ts
> +    }
it looks like this now: 
```
<TSCYesNoPopup   //open when the close icon is clicked or on backdrop click
        open={editState.showDiscardDialogAndCloseForm} 
        title="You have unsaved changes. Are you sure you want to discard them?"
        onYes={() => handlers.handleDiscardChangesAndCloseTheForm}
        onNo={handlers.handleCloseDiscardDialog}
        onClose={handlers.handleCloseDiscardDialog}
      />
<TSCYesNoPopup //open when the Discard button is clicked
        open={editState.showDiscardDialog}
        title="You have unsaved changes. Are you sure you want to discard them?"
        onYes={() => handlers.handleDiscardChanges}
        onNo={handlers.handleCloseDiscardDialog}
        onClose={handlers.handleCloseDiscardDialog}
      />
```

2024-10-27 14:06 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +    }
yeah i think this is good, separating the two into two separate popups for two separate actions

2024-10-27 14:06 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +    }
yeah i think this is good, separating the two into two separate popups for two separate actions good work ! ty for explaining as well

2024-10-28 15:12 UTC, paologum commented on server/src/types.ts
> +export type newUsersWorkshops = Insertable<UsersWorkshopsTable>;
hmm i don't think we would need to change this imo

2024-10-29 11:54 UTC, paologum commented
this is still not dark mode toggled (use `ag-grid`) style switch like the others

<img width="764" alt="Screenshot 2024-10-29 at 8 54 16 PM" src="https://github.com/user-attachments/assets/233315c0-49a9-4865-8696-77e0de60ccfc">

2024-10-29 11:56 UTC, paologum commented
these should be the same for consistency 

<img width="124" alt="Screenshot 2024-10-29 at 8 55 33 PM" src="https://github.com/user-attachments/assets/af2708ec-8de0-4f98-a416-0b121e0ee2ea">

<img width="207" alt="Screenshot 2024-10-29 at 8 55 47 PM" src="https://github.com/user-attachments/assets/5e9b55dc-1b56-495f-b71e-f7c0e2ecfb30">

2024-10-29 12:11 UTC, paologum requested changes

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  const [showDiscardDialogAndCloseForm, setshowDiscardDialogAndCloseForm] = useState(false);
change to `setShowDiscardDialogAndCloseForm`

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  const [isEditing, setIsEditing] = useState(false);
for consistency across forms change this to `editMode` and `setEditMode`

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  const [currentWorkshops, setCurrentWorkshops] = useState<number[] | undefined>(workshops);
when is `currentWorkshops` ever `undefined`

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  };
with the amount of dialogs i would rename `handleOpenConfirmDialog` to specifically reference the workshops like `handleOpenConfirmRemovalOfUserFromWorkshop`

additionally change the `setOpenConfirmRemovalOfUserFromWorkshopDialog`

it is long but because its ambiguity is gone it's easier to understand

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +
same here

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  };
for all three of these methods I would change the name to aptly describe them

2024-10-29 12:11 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  };
comments and also be more specific about which form for all 3 of these methods as well

2024-10-29 12:11 UTC, paologum commented on server/src/admin/admin-routes.ts
> +        }
i don't think we want to send errors on `duplicatedEmails`unless someone else said so
@asivath can you confirm?

2024-10-29 12:11 UTC, paologum commented on shared/src/index.ts
> +  if (o.workshopIds != null) {
`workshopIds` isn't able to be `null` it can only be `undefined`

2024-10-29 12:17 UTC, paologum commented on app/src/admin/AdminShowAdditionalUserInfo.tsx
> +  };
because this is a format kept consistent in two areas, i would make a function in `non-action-util.ts` that accepts either a string or a `dayjs` object and formats it according to this (for a string) and the other way (for a dayjs) object

2024-10-29 15:56 UTC, paologum commented
/confirm-deploy

2024-10-31 02:45 UTC, asivath commented on server/src/admin/admin-routes.ts
> +        }
yep don't send

2024-11-02 00:38 UTC, JacquiFreeElectron commented on app/src/components/edit-user-stats-hook.ts
> +  const [currentWorkshops, setCurrentWorkshops] = useState<number[] | undefined>(workshops);
when a user is not enrolled in any workshop

2024-11-02 02:15 UTC, JacquiFreeElectron commented
> handleDiscardChangesAndCloseTheForm
Used `backgroundColor: theme.palette.mode === "dark" ? "rgba(26, 34, 45, 0.7)" : "rgba(255, 255, 255, 0.7)"` instead cause ag-grid style switch doesn't work on `TableContainer`, the effect is satisfying imo: 
![Screenshot 2024-11-01 at 10 14 42 PM](https://github.com/user-attachments/assets/5f14f2a4-8985-4287-838a-fdbe74136263)
![Screenshot 2024-11-01 at 10 15 01 PM](https://github.com/user-attachments/assets/56af7428-afba-4f48-be23-e9ef3e6adf5f)

2024-11-02 02:31 UTC, JacquiFreeElectron commented
dark mode:
![Screenshot 2024-11-01 at 10 30 00 PM](https://github.com/user-attachments/assets/d121665a-34fc-4ebe-a52b-e6633209c900)
Other things stay the same as the last demo.
Tried my best to rename handlers/setters lmk if some of them don't make sense :)

2024-11-02 10:10 UTC, paologum commented
/confirm-deploy

2024-11-02 10:17 UTC, paologum commented
> > this is still not dark mode toggled (use `ag-grid`) style switch like the others
> 
> > 
> 
> > <img alt="Screenshot 2024-10-29 at 8 54 16 PM" width="764" src="https://private-user-images.githubusercontent.com/89664317/381111408-233315c0-49a9-4865-8696-77e0de60ccfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzU1NDUsIm5iZiI6MTczMDQ3NTI0NSwicGF0aCI6Ii84OTY2NDMxNy8zODExMTE0MDgtMjMzMzE1YzAtNDlhOS00ODY1LTg2OTYtNzdlMGRlNjBjY2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE1MzQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMzIxNTQyMzZhMmM1Y2UwZjI3MjRiYzUyYzAzZDgzZjRiNmZlZTBkMGRlMzEzZmIwNmM5MGNiOGJkZmI3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BJDq6437HZPeyNSCP_w-PXFXW3QKIsM9jJpdwtbdXSE">
> 
> 
> 
> 
> 
> Used `backgroundColor: theme.palette.mode === "dark" ? "rgba(26, 34, 45, 0.7)" : "rgba(255, 255, 255, 0.7)"` instead cause ag-grid style switch doesn't work on `TableContainer`, the effect is satisfying imo: 
> 
> ![Screenshot 2024-11-01 at 10 14 42 PM](https://github.com/user-attachments/assets/5f14f2a4-8985-4287-838a-fdbe74136263)
> 
> ![Screenshot 2024-11-01 at 10 15 01 PM](https://github.com/user-attachments/assets/56af7428-afba-4f48-be23-e9ef3e6adf5f)
> 
> 

i sent you a slack message about figuring out if we can apply the theme here/how you initially tried it
but if we decide that we can't then you would need to put those colors in the actual palette (as two different colors i think)

2024-11-02 17:00 UTC, paologum requested changes
some last cleanups, looks good!

2024-11-02 17:00 UTC, paologum commented on server/__tests__/admin-routes.test.ts
> +  it("should return 500 if unable to update old user", async () => {
same as above

2024-11-02 23:00 UTC, JacquiFreeElectron commented on app/src/state/non-action-util.ts
> +export function formatDate(input: string | dayjs.Dayjs): string {
not yet. he uses `valueFormatter: (params) => dayjs(params.value).format("MMMM D, YYYY [at] h:mm A")`, I'm unsure how to call the function I created instead. Do i just do `valueFormatter: (params) =>formatDate(params.value)`?

2024-11-03 02:27 UTC, paologum commented on app/src/state/non-action-util.ts
> +export function formatDate(input: string | dayjs.Dayjs): string {
i believe it's a string unless i'm wrong so i think that's good
just verify it's the same and you should be chilling!

2024-11-06 03:52 UTC, paologum requested changes
two minor name changes, then i will approve!

2024-11-06 03:52 UTC, paologum commented on server/src/admin/admin-routes.ts
> +    const addedNewUserWorkshopRelationship = async (userId: number, workshopId: number, email: string) => {
i would change this to `addNewUserWorkshopRelationship`

2024-11-06 03:52 UTC, paologum commented on app/src/components/edit-user-stats-hook.ts
> +  const handleisConfirmDiscardUserInfoChangeOpen = () => {
you should still capitalize the i to `handleIs...`

2024-11-06 04:06 UTC, paologum approved these changes
i wanna make sure, but when a workshop

2024-11-06 06:02 UTC, merged