Tsc 520 changes to account menus
earthhistoryviz/tsconline pull request #273
Opened 2024-10-11 00:29 UTC by sbal15

<img width="440" alt="pic1" src="https://github.com/user-attachments/assets/a71122d4-3802-4f76-9e2c-e5541a015a43">
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/5374d0a0-96d2-4473-812a-7cbff8129f11">

removed dark/light mode & language from profile
added preferences tab

2024-10-11 15:22 UTC, paologum commented
because language and dark mode are not directly correlated, i would probably move towards a hover menu button labeled `Language` that opens a second dropdown to the side that has the languages

2024-10-15 06:22 UTC, paologum commented
/confirm-deploy

2024-10-18 20:57 UTC, sbal15 commented
![image](https://github.com/user-attachments/assets/7eb83c84-d447-465c-82f8-ccf476ff4fb5)

2024-10-20 20:16 UTC, sbal15 commented
<img width="196" alt="image" src="https://github.com/user-attachments/assets/f87d9ea5-6958-46a3-ba3a-7141f4e56520">

2024-10-21 14:23 UTC, paologum commented
/confirm-deploy

2024-10-23 14:03 UTC, paologum requested changes

2024-10-23 14:03 UTC, paologum commented on app/src/NavBar.tsx
> +                <Typography>{t(``)}</Typography>
if there is not translation just remove the `Typography`

2024-10-23 14:03 UTC, paologum commented on app/src/NavBar.tsx
> +                  <Typography>{t(``)}</Typography>
same here, also the above `onClick is empty so remove it

2024-10-23 14:03 UTC, paologum commented on app/src/NavBar.tsx
> +        <PopupState variant="popover" popupId="demo-popup-menu">
remove the `demo-popup-menu`

2024-10-23 14:03 UTC, paologum commented on app/src/NavBar.tsx
> +                  }}
move the `sx` to the `css` file

2024-11-01 14:36 UTC, sbal15 commented on app/src/NavBar.tsx
> +                  <Typography>{t(``)}</Typography>
when i try to remove the onclick, it throws an error, would you know why?

2024-11-01 14:42 UTC, paologum commented on app/src/NavBar.tsx
> +                  <Typography>{t(``)}</Typography>
does this menu item have any use if it is empty with an empty onClick function? what is the use of this

2024-11-08 16:25 UTC, paologum requested changes

2024-11-08 16:25 UTC, paologum commented on app/src/NavBar.tsx
> +                    ref={dropRef}
does this ref have a function? it just is being declared but never used

2024-11-08 17:06 UTC, sbal15 commented on app/src/NavBar.tsx
> +                    ref={dropRef}
oops sorry, forgot to take it out, i was experimenting with the drop down menu

2024-11-17 06:03 UTC, paologum commented
/confirm-deploy

2024-11-17 06:15 UTC, paologum commented
tab selection seems to be buggy on the pr preview, there is probably a bug in this branch related to this because on local and dev sites this is not the case

https://github.com/user-attachments/assets/00f5389d-aa3e-4c0f-ac13-d7b6cfbab098

2024-12-19 07:41 UTC, paologum commented
/confirm-deploy

2024-12-19 07:47 UTC, paologum requested changes
looks like you removed the mobile functionality from the pr, you will need to add that back

2024-12-19 07:47 UTC, paologum commented on scripts/json-to-excel.ts
don't commit this

2024-12-19 07:47 UTC, paologum commented on app/src/NavBar.tsx
> +              <Tab value={3} disableRipple label={t("navBar.help")} to="/help" component={Link} />
same tab value makes selection of tabs off

2024-12-30 09:22 UTC, paologum commented
/confirm-deploy

2024-12-30 10:38 UTC, paologum approved these changes

2024-12-30 10:38 UTC, merged