added route to service mappoints directly
earthhistoryviz/tsconline pull request #275
Opened 2024-10-18 05:06 UTC by Changk820

2024-10-18 06:20 UTC, Changk820 commented on server/src/index.ts
Aditya said to incase you were wondering why I did this.

2024-10-18 06:21 UTC, Changk820 commented on server/src/index.ts
For removing a route serving aboutImages

2024-10-18 06:29 UTC, Changk820 commented
I changed the tests because I removed imagesDirectory throughout the repo. Can you take a look at the tests to make sure I didn't do something sus?

The way my code is getting the new map.img path is by taking a previously existing string I found and regexing that, then appending the image name.

Also some things I noticed:
It seems if public and private have the same map point images, only one will show up.

I'm not sure how to create my own map images. I just took a public data pack and uploaded as a private for now to test the map points functionality.

I'm pretty sure this new folder structure has broken the version checking mechanism. On server start up, my images folders keeps getting overwritten. I'm pretty sure originally, it was supposed to make a single version.info file, now every pack has a version.info file, but I feel like this shouldn't break the version checking. Might need to make a new issue for this. Maybe I'm going crazy though.

2024-10-18 08:09 UTC, paologum requested changes

2024-10-18 08:09 UTC, paologum commented on docs/server.md
this file isn't connected to the actual  docs, so you should change the docs branch itself instead of this, you can remove these changes. if you want you can get rid of this docs folder

2024-10-18 08:09 UTC, paologum commented on server/src/index.ts
> +  decorateReply: false
this doesn't exist anymore `assets/decrypted` is not something we support anymore

2024-10-18 08:09 UTC, paologum commented on server/src/index.ts
> +});
i wouldn't service the whole uploads folder using static, if you're gonna do this you have to make it specific. we don't want to make peoples files available to everyone

2024-10-18 08:11 UTC, paologum commented
between public and private, there should only ever be one datapack with a unique title. each datapack has public and uuid to make it easily understandable where the datapack is in the file system. you still need to create a route that SPECIFICALLY fetches the image. not a general route that gives the user the options to select from a large amount of files

2024-10-24 04:48 UTC, Changk820 commented on server/src/index.ts
> +});
Is  the new change what you meant?

2024-10-24 16:12 UTC, paologum commented on server/src/index.ts
> +  decorateReply: false,
this needs to be specific again. this needs to ONLY service the map pack images in the decrypted folder if they exist

2024-10-28 16:25 UTC, paologum commented on server/src/index.ts
> +  const mapImagesIndex = pathSegments.indexOf("MapImages");
check that the second to last directory is `MapImages`

2024-10-28 16:25 UTC, paologum commented on server/src/index.ts
> +      const fullPath = path.join(_root, pathName);
verify

2024-10-29 11:48 UTC, paologum commented on server/src/index.ts
> +    prefix: `/assets/uploads/${type}`,
tbh i would probably lean towards not requiring a prefix of `/assets/uploads/` so others don't know our filesystem pathing. i would instead prefix like `${type}/${imageName}` or however, then construct it in your method
that way they don't actually need to know the path and we can just change the path if we change our filesystem
this ends up basically being a regular route but i think this would make the most sense
lmk if that makes sense

2024-10-29 11:50 UTC, paologum commented on server/src/index.ts
> +    prefix: `/assets/uploads/${type}`,
i'm mostly saying this because how you're checking how the file is constructed is basically making the path itself, so given an image name and a type then you can service it by constructing the path
sorry my directions for this task were ambiguous that's my bad

2024-11-01 05:39 UTC, paologum commented on server/src/index.ts
> +      return isAllowed && fs.existsSync(fullPath);
not sync

2024-11-01 05:39 UTC, paologum commented on server/src/index.ts
> +      const isVerified = verifyFilepathSync(fullPath);
not sync

2024-11-01 05:39 UTC, paologum commented on server/src/util.ts
> +
we shouldn't need this

2024-11-01 11:18 UTC, Changk820 commented on server/src/util.ts
> +
The original one was async. Would it not cause problems if I attempt to use it synchronously?

VS code complained at me, doing this

`
    allowedPath : async (pathName, _root, req: Request) => {
      const fullPath = path.join(_root, pathName);
      // Verify the full path to prevent path traversal.
      const isVerified = await verifyFilepath(fullPath);
      if (!isVerified) {
        return false;
      }
      // Validate path based on route type | Private: Check UUID and path | Public: Only check path
      const isAllowed = type === "private" ? isAllowedPrivatePath({ pathName, req }) : isValidMapImagePath(pathName);
      return isAllowed && fs.existsSync(fullPath);
    }
  }); 
`

allowed path says
`No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyStaticOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '(pathName: string, _root: string, req: Request) => Promise<boolean>' is not assignable to type '(pathName: string, root: string, request: FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>) => boolean'.
      Type 'Promise<boolean>' is not assignable to type 'boolean'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyStaticOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '(pathName: string, _root: string, req: Request) => Promise<boolean>' is not assignable to type '(pathName: string, root: string, request: FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>) => boolean'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifyStaticOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '(pathName: string, _root: string, req: Request) => Promise<boolean>' is not assignable to type '(pathName: string, root: string, request: FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>) => boolean'.ts(2769)`

2024-11-01 11:19 UTC, Changk820 commented on server/src/index.ts
> +      return isAllowed && fs.existsSync(fullPath);
The signature '(path: PathLike, callback: (exists: boolean) => void): void' of 'fs.exists' is deprecated.ts(6387)

2024-11-01 14:40 UTC, paologum commented on server/src/util.ts
> +
if you can't do async, it would probably be better to make your own route and then make the method async

2024-11-03 02:43 UTC, paologum commented on server/src/index.ts
> +      return isAllowed && fs.existsSync(fullPath);
we already have a file util function that is asynchronous so use that
also existsSync only has a synchronous you have to use `realpath` or `access` if you wanted to do your own checking but that's not enough so just use our handler

2024-11-03 02:44 UTC, paologum requested changes

2024-11-03 02:44 UTC, paologum commented on app/src/settings_tabs/map_points/MapViewer.tsx
> +                    src={devSafeUrl(mapData.img.replace("/assets/uploads", "/getMapImages"))}
just store the file image name here and then instead of reconstructing it just construct it here
there is no reason to store the filepath in `img` if we don't need ut

2024-11-03 02:48 UTC, paologum commented on server/src/index.ts
> +    prefix: `/getMapImages/${type}`,
routes shouldn't have get in them because the request already defines that in the type of request (`GET`, `POST`, and `PATCH`)
so just name this `/map-images/${uuid}/${datapack}/${image}`
and use these to service the image

2025-01-06 17:30 UTC, Changk820 commented on app/src/settings_tabs/map_points/MapViewer.tsx
> +                    src={devSafeUrl(mapData.img.replace("/assets/uploads", "/getMapImages"))}
How would I know where the image is stored with only the name of the map?

I don't know how to get the exact datapack an image is in

2025-01-19 00:02 UTC, paologum requested changes
just a couple changes!

2025-01-19 00:02 UTC, paologum commented on server/src/routes/routes.ts
> +const isAllowedPrivatePath = ({ pathName, req }: { pathName: string; req: Request }): boolean => {
you should be able to just use `FastifyRequest` to type out `Request` and don't need to declare a new interface

2025-01-19 00:02 UTC, paologum commented on server/src/routes/routes.ts
> +    const pathName = `/assets/uploads/${type}/${rawPath}`;
`/assets/uploads` should be changed to `assetconfigs.uploadDirectory`

2025-01-24 02:44 UTC, Changk820 commented on server/src/parse-map-packs.ts
> +      map.img = `/${trimmedPath}/MapImages/${String(info[2])}`;
I can't do:
      // const trimmedPath = path.dirname(path.dirname(map_info));
This is what caused the tests to fail.

It expected
      "img": "/server/__tests__/__data__/parse-map-packs-test-1.txt/MapImages/AfricaBight.png"

Using this commented out code, I give
       "img": "/server/__tests__/MapImages/AfricaBight.png"

I think what happened was the path name got duplicated, so what I was doing was removing that duplicated part, then tacking the "MapImages/AfricaBight.png" back on at the end.

Or I could just change the tests, going back twice in the directory seems to still work, just tests fail

2025-01-24 02:47 UTC, paologum commented on server/src/parse-map-packs.ts
> +      map.img = `/${trimmedPath}/MapImages/${String(info[2])}`;
the tests are just intended to be the correct version, if that's what you expect then you should change the expected to be what it should be

2025-02-27 17:06 UTC, Changk820 commented
/deploy

2025-02-27 20:33 UTC, closed without merging