Tsc 508 adding datapacks to workshops
earthhistoryviz/tsconline pull request #289
Opened 2024-11-16 04:12 UTC by asivath

https://github.com/user-attachments/assets/df63bccd-3d73-453a-9fa9-5417042981c8

most of the ui is temporary and will change in the pr that overhauls the workshop ui. lots of the diff on the app side is just refactoring and moving code around

2024-11-19 15:46 UTC, paologum commented
/confirm-deploy

2024-11-19 17:00 UTC, paologum commented on server/src/routes/routes.ts
> +        uuidFolder = datapack.uuid;
comment from before about refactoring for abstraction

2024-11-19 17:00 UTC, paologum commented on server/src/routes/user-routes.ts
> +      fetchAllUsersDatapacks(`workshop-${workshop.workshopId}`)
here too

2024-11-19 17:06 UTC, paologum requested changes

2024-11-19 17:06 UTC, paologum commented on app/src/admin/AdminWorkshopComponents.tsx
> +            </Box>
there is a general loader in my edit datapack task so whichever one gets merged first, this should change to that one so that they are consistent

2024-11-22 15:05 UTC, asivath commented on server/src/admin/admin-routes.ts
> +    const workshop = await getWorkshopIfNotEnded(workshopId);
you shouldn't be able to edit old workshops in general so I added something quick on the frontend

2024-11-23 02:54 UTC, asivath commented on server/src/admin/admin-routes.ts
> +    if (await doesDatapackFolderExistInAllUUIDDirectories(datapackMetadata.uuid, datapackMetadata.title)) {
datapacks are stored in `public/workshop-${workshopId}/datapackname/datapack`. there is no workshop folder containing all workshops and each workshop folder is on the same level as official.

2024-11-23 03:33 UTC, asivath commented on server/src/admin/admin-routes.ts
> +    });
it was initially something for testing but I fixed the issue so I can remove it

2024-11-23 03:50 UTC, asivath commented on server/src/database.ts
> +}
yea I used the wrong function

2024-11-23 03:53 UTC, asivath commented
> i'm assuming the overload in the workshop ui will include a ui to view all added datapacks to a workshop without the workshop currently ongoing and being a user in it? because i can only see them under those conditions atm so i'm assuming

that's right

2024-11-26 10:08 UTC, paologum commented
/confirm-deploy

2024-11-26 15:04 UTC, paologum commented
https://github.com/user-attachments/assets/fe5c7937-e67d-40af-945a-d75fbc71e918

i should be able to add users while it's still active right

2024-11-26 21:10 UTC, asivath commented
> it feels weird having it unaligned like this but you said this would change so it should be fine. but it should probably be two buttons? a ... button and a delete button? or just a ... where you delete in that form
> 
> which do you think
i prefer ... and a delete icon

2024-11-27 01:29 UTC, paologum commented
ok i merged the branch, if you want to add the new loader

2024-11-27 01:39 UTC, paologum commented on shared/src/index.ts
> +  uuid: string;
looking at your pr made me remember that you should change the `assertWorkshopDatapack` to accoutn for this

2024-11-29 01:52 UTC, paologum commented
/confirm-deploy

2024-11-29 02:04 UTC, paologum requested changes
you need to change `migrate-cached-datapacks.ts`
with the uuid changes for workshops then run the migration on the docker

2024-12-01 06:09 UTC, paologum commented
/confirm-deploy

2024-12-12 18:18 UTC, asivath commented
that makes sense, i doubt we are going to have public workshops

2024-12-13 14:50 UTC, paologum commented
/confirm-deploy

2024-12-13 16:04 UTC, paologum commented on app/src/settings_tabs/Datapack.tsx
> +        {state.user.workshopIds && (
doesn't this always exist? check if empty would be better no?

2024-12-16 16:55 UTC, paologum commented
/confirm-deploy

2024-12-16 17:01 UTC, paologum approved these changes

2024-12-16 17:01 UTC, merged