Tsc 539 frontend for showing user is in a workshop
earthhistoryviz/tsconline pull request #292
Opened 2024-11-27 00:56 UTC by JacquiFreeElectron

https://github.com/user-attachments/assets/a611000e-8d41-41db-a44a-d6867e6805d7

## What's Done

1. Frontend for displaying workshops (used dummy workshops for display).

## What's Not Done

- Backend route for fetching workshops and their associated files.

## Note

Aaron mentioned that we can include a workshop datapack module on the details page to show the datapacks. However, I'm unclear about the intended functionality. Should we allow users to add datapacks there, or should we only display the datapacks that will be used in the workshop? 

If I recall correctly, the goal is just to display the datapacks. Based on my review of the workshop provided by Prof. Ogg, the user is expected to follow the instructions and add the datapacks under the 'Datapack' tab. 

Because of this, it feels a bit odd to have a module here similar to the one in the 'Datapack' tab for this purpose. Or perhaps I misunderstood something or forgot some details. If not, I think simply showing the titles of the datapacks would be sufficient.

2024-11-27 01:47 UTC, paologum commented
/confirm-deploy

2024-11-27 01:56 UTC, paologum commented
For consistency, these are very similar. the general layout should therefore be the same
i think the font weights should be the same and the positioning of the boxes and the divider on top should be the exact same. additionally the font weight/size of the title. and the width of the box.
the general content (minus the sub headers) are fine, you should make the sub headers the same font weight/size and use the same dividers inside the box. the description items or like the sub content beneath the headers is fine though, they differ from the datapack so they should be fine as it is

displaying this written is kind of difficult so let me know if you're confused. my general consensus is the similar parts between the two are the sane.

before pushing comment a pic here below so i can verify!


<img width="1438" alt="Screenshot 2024-11-27 at 10 50 41 AM" src="https://github.com/user-attachments/assets/ef7b8839-6e43-4085-a70a-7646d96d7f86">

<img width="1431" alt="Screenshot 2024-11-27 at 10 50 56 AM" src="https://github.com/user-attachments/assets/de64db82-9df5-44cf-9b1b-25dbcbfa7a12">

2024-12-05 04:26 UTC, JacquiFreeElectron commented
![Screenshot 2024-12-04 at 11 26 05 PM](https://github.com/user-attachments/assets/00174c96-cc69-4459-bc3d-00b97e192ef4)
Does this look good?

2024-12-06 01:55 UTC, paologum commented
/confirm-deploy

2024-12-06 06:03 UTC, paologum commented
from what i saw, the workshop cards are not `cursor: pointer` so it doesn't seem like they can be clicked

2024-12-06 06:04 UTC, paologum commented
from what i can see, the cards don't feel like they can be clicked because `cursor: pointer` isn't on

2024-12-06 06:12 UTC, paologum requested changes

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +              <Typography>Upcoming Workshops</Typography>
translation

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +              {renderWorkshopsCategory(upcomingWorkshops, "No upcoming workshops at the moment.")}
translation

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +              {renderWorkshopsCategory(expiredWorkshops, "No passed workshops at the moment.")}
translation

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +          You are not logged in. Please sign in to view your workshops.
translation also can you move to class

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +            }}>
move to class

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +};
every workshop should have it's own image property

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +                  overflow: "hidden" // Prevents any content overflow
can you move this to class except for secondaryBackground

2024-12-06 06:12 UTC, paologum commented on app/src/Workshops.tsx
> +        />
this is probably fine but I might lean towards an actual route that will point to a workshop so people can share it and/or bookmark it and see if it still exists really easily. the way you have it, they all live on `https://pr-preview.geolex.org/workshops` instead of on their page. This would be similar to the datapacks profile routes. i would ask ogg or aditya today at the meeting. I'm not sure I can make it :(

2024-12-06 06:12 UTC, paologum commented on app/src/WorkshopDetails.tsx
translation in this file. i probably didn't do it in the DatapackProfilePage but we should still do it here

2024-12-17 03:02 UTC, JacquiFreeElectron commented
I implemented some workarounds related to the backend routes, such as returning dummy data. Prof. Ogg wants us to create a real workshop based on the one he provided as a reference. I can continue working on this story after this frontend pr is merged. The next step is to figure out how to transform and store the files he provided (since they're specifically tailored for Java), such as determining which parts of the original files should be stored on the server for downloads, and which should be displayed on the frontend. Once we've got that sorted, I can start on the backend. So, for now, this PR is still focusing on the frontend.

2024-12-19 07:13 UTC, paologum commented
/confirm-deploy

2024-12-19 07:32 UTC, paologum requested changes

2024-12-19 07:32 UTC, paologum commented on app/src/Workshops.tsx
> +  const expiredWorkshops = dummyWorkshops.filter((workshop) => new Date(workshop.end) < now);
i feel like these could be useful potentially for other components (maybe for the admin page as well)
so can you add this to `non-action-util.ts` it would just accept a workshop array.
i've done the same in the file already with datapacks

2024-12-19 07:32 UTC, paologum commented on app/src/WorkshopDetails.tsx
> +  if (!workshop || !id) return <PageNotFound />;
you should probably add the you are not logged in please sign in to view your workshops here as well (if not logged in)
if that's not already it's own component you should make it one since it'll be used in two places

2024-12-19 07:32 UTC, paologum commented on app/src/Workshops.tsx
> +  const renderWorkshopsCategory = (workshops: Workshop[], noDataMessage: string) => (
instead of a function can you make this a component so it reads better

2024-12-19 07:32 UTC, paologum commented on app/src/Workshops.tsx
> +  }
right now this indefinitely adds workshops to an array so instead for this dummy case just set the `workshop` array instead of pushing at the beginning of the lifecycle of the workshop component. additionally rename `setSelectedWorkshop` to `pushWorkshopToWorkshopsArray` or something more clear because `setSelectedWorkshop` pushing to an array is very ambiguous

2024-12-19 07:32 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +});
above

2024-12-19 07:32 UTC, paologum commented on app/translation/en.json
> +                "datapacks": "DataPacks",
in consistency, `Datapacks`

2024-12-19 07:32 UTC, paologum commented on app/translation/zh.json
> +            "workshops": "工作坊"
just confirming but for both chinese and english you added to the dropbox translation doc?

2024-12-19 07:35 UTC, paologum commented
overall looks great just some minor things :D

2024-12-19 23:35 UTC, JacquiFreeElectron commented on app/translation/zh.json
> +            "workshops": "工作坊"
oops not yet

2024-12-20 01:14 UTC, JacquiFreeElectron commented on app/translation/zh.json
> +            "workshops": "工作坊"
translation key is now updated

2024-12-20 06:40 UTC, paologum commented
/confirm-deploy

2024-12-20 06:43 UTC, paologum requested changes

2024-12-20 06:43 UTC, paologum commented on app/src/Workshops.tsx
> +  }, []);
slight thing that won't be in production ever, but everytime you visit this page it pushes the same workshops everytime, so instead you should set it

2024-12-20 06:43 UTC, paologum commented on app/src/Workshops.tsx
> +  const renderWorkshopsCategory = (workshops: Workshop[], noDataMessage: string) => (
this still needs to change (not its own file necessarily but a component instead of a function)

2024-12-20 06:44 UTC, paologum requested changes

2024-12-20 06:44 UTC, paologum commented on app/src/NavBar.tsx
> +    { label: "Workshops", path: "/workshops", icon: <School /> },
ope this still needs a translation

2024-12-20 06:44 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +});
oh okay wait i was wrong before, if this is setting it should be `setWorkshopsArray`
if you want to push it should be the other way
sorry if that was confusing

2024-12-20 07:37 UTC, paologum commented on app/src/NavBar.tsx
> +    { label: t("nacBar.workshops"), path: "/workshops", icon: <School /> },
misspelling

2024-12-20 07:43 UTC, JacquiFreeElectron commented on app/src/NavBar.tsx
> +    { label: t("nacBar.workshops"), path: "/workshops", icon: <School /> },
ooops

2024-12-20 08:04 UTC, paologum approved these changes

2024-12-20 08:04 UTC, merged