Tsc 437 make settings upload and download into a file tab
earthhistoryviz/tsconline pull request #295
Opened 2024-12-06 05:43 UTC by Michael-Knaack

Added the preference tab and moves the load and save setting button.
![image](https://github.com/user-attachments/assets/9c027187-be23-4e4d-90b0-4f65f12219b7)

2024-12-12 17:53 UTC, asivath requested changes
remember the theme thing for coloring, that will allow the color to change based on light mode and dark mode. also try making the time and preferences boxes the same size and try putting the buttons outside of the box. this is unrelated to your pr but I noticed that clicking in the dropdown when you hover over settings doesn't change the navbar underline when clicking any of them. in Navbar.tsx in the onclick for the settingsMenu can you change the actions.setTab from 3 to 2. that should fix it

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/Preferences.css
> +  background-color: #252e3c;
shouldn't be hardcoded, use theme

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/Preferences.css
> +}
this css is not used in your code. this is one example but there's probably more you can try removing

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/SaveSettings.css
> +  background-color: #5e9ad3;
hardcoding color shouldn't be needed, theme should be enough

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/SaveSettings.css
> +  background-color: #457ec4;
i don't think you need to set a hover

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/SaveSettings.tsx
> +        </Button>
this adds on to my previous comments about colors. the reason it isn't setting it for you is because you are using the default Button component. you should be using our custom TSCButton component (located in the components folder) instead, which will set the colors for you and you can get rid of the css

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/SaveSettings.tsx
>          </DialogActions>
this TSCButton component is the one you should be using. you should replace this button and the one above with TSCButton

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/LoadSettings.tsx
> -    actions.setLoadSaveFilename(file.name.substring(0, file.name.length - 4)); //remove extension
can you put this comment back

2024-12-12 17:53 UTC, asivath commented on app/src/settings_tabs/Time.css
> +  flex: 1; /* Make children grow to fill the container */
remove comments that don't add information

2024-12-12 17:53 UTC, asivath commented on app/src/state/actions/general-actions.ts
> +      return 6;
numbering is wrong here, you're missing search

2024-12-13 17:20 UTC, paologum commented
/confirm-deploy

2024-12-30 10:38 UTC, paologum commented
/confirm-deploy

2024-12-31 01:07 UTC, paologum approved these changes

2024-12-31 16:45 UTC, merged