Tsc 567 treatise linking
earthhistoryviz/tsconline pull request #297
Opened 2024-12-20 09:18 UTC by Changk820

2024-12-20 11:23 UTC, Changk820 commented
https://purdue-edu.zoom.us/rec/share/13ENlJ5_ubsICu3Ng5thzS7rPFOPsON8qacv5GwjZbe3RoUA1PRCoz69j2YjW-SR.cbjS7vPVDlLW6403 
Passcode: 18y8bv9*

https://github.com/user-attachments/assets/1c4696c0-4a28-4652-b204-09413d834f03

2024-12-23 14:49 UTC, paologum submitted a review, later dismissed

2024-12-23 14:49 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +            console.log("Error: Unable to fetch datapack");
might even want to push an error

2024-12-23 14:49 UTC, paologum commented on server/src/routes/user-routes.ts
> +export const uploadTreatiseDatapack = async function uploadTreatiseDatapack(
testing all aspects of this code would be pretty difficult, the testing for the code already exists in other areas so refactoring may be easier than testing each part

2025-01-24 07:14 UTC, Changk820 commented on app/src/GenerateExternalChart.tsx
> +  };
thats not a thing

2025-01-24 07:20 UTC, Changk820 commented on app/src/GenerateExternalChart.tsx
> +
Aditya say no

2025-01-24 07:21 UTC, Changk820 commented on app/src/GenerateExternalChart.tsx
> +
what other units do we support? treatise only supports Ma

2025-01-24 07:22 UTC, Changk820 commented on app/src/GenerateExternalChart.tsx
> +
it doesnt look like tsc online can switch from ma either in the time settings

2025-01-24 14:08 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +  };
![image](https://github.com/user-attachments/assets/f3050a44-be7a-4107-8ef4-01932806e27c)

maybe u shud look

2025-01-24 14:18 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +  };
grab with the hash map and call this function with columninfo

2025-01-24 14:19 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +
ask ogg

add human culture and u can see multiple units

2025-02-18 20:12 UTC, Changk820 commented on app/src/GenerateExternalChart.tsx
> +  };
change original function to accept both a name or a column, then jsut call the function

2025-03-11 18:28 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +        <Typography variant="h3">Error: Unable to Generate Chart</Typography>
translation

2025-03-14 00:14 UTC, Changk820 commented
/deploy

2025-03-14 01:58 UTC, paologum commented
/deploy

2025-03-14 02:12 UTC, paologum commented
<img width="791" alt="Screenshot 2025-03-13 at 10 11 27 PM" src="https://github.com/user-attachments/assets/39798c98-ba04-474c-a678-59226e638505" />

if we have the treatise datapack, shouldn't it be visible here as a public datapack so they can remove it? you said it acts the same as a public user datapack

2025-03-14 02:12 UTC, paologum commented
because right now, it looks like i only have the internal selected which isn't true, and if they wanted to not have the treatise on, they would be confused as to how to do that

2025-03-14 15:59 UTC, paologum commented
/deploy

2025-03-16 20:56 UTC, Changk820 commented
/deploy

2025-03-17 03:59 UTC, Changk820 commented
/deploy

2025-03-18 22:56 UTC, paologum reviewed
he wants to turn off reconstructions right?
also the below video, it should stop doing the load after it fails to fetch the user datapacks, i'm not sure why it's continuing and then displaying two errors

https://github.com/user-attachments/assets/5da01fbc-90c5-4b02-a670-4073a85cbb27

2025-03-18 23:00 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +        }
i think here, you don't need to `pushError` here because the `fetchDatapack` methods already handle the snackbar error pushes. you should also check after each fetch instead of after both of them to see if they return a datapack.

2025-03-27 01:59 UTC, Changk820 commented
/deploy

2025-03-27 03:02 UTC, Changk820 commented
/deploy

2025-03-27 18:05 UTC, paologum commented
is there a cleaner way to have the titles for the treatise datapacks, because i'm not sure anyone will understand what treatise datapacks are if they were to see those datapacks on their screen

2025-03-27 18:08 UTC, paologum requested changes

2025-03-27 18:08 UTC, paologum commented on app/src/state/state.ts
> +    treatiseDatapackLoading: true
if you add to this, add to `isMetadataLoading` function

2025-03-27 18:08 UTC, paologum commented on shared/translations/en.json
> +            "NO_MODELS": "No models available. Please add a model by clicking the chart in the main view.",
this shouldn't be changed

2025-03-28 01:24 UTC, paologum commented
/deploy

2025-03-28 01:40 UTC, paologum requested changes

2025-03-28 01:40 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +        }
won't all treatise datapacks have the phylum name?

2025-03-28 01:40 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +          console.log("Parts:", parts);
remove logs

2025-03-28 01:40 UTC, paologum commented on server/src/types.ts
> +  phylum?: string;
i don't think it's a good idea to put such a specific use case on such a general type, this probably should go somewhere else as in send the two objects side by side and/or separate

2025-03-28 01:40 UTC, paologum commented on app/src/GenerateExternalChart.tsx
> +        }
wait i'm dumb nvm

2025-03-28 02:37 UTC, Changk820 commented
/deploy

2025-03-28 16:24 UTC, asivath commented
/deploy

2025-03-31 16:45 UTC, paologum commented
/deploy

2025-03-31 18:32 UTC, Changk820 commented on server/src/index.ts
> +server.post("/external-chart", moderateRateLimit, uploadTreatiseDatapack);
its on treatise side that calls this route to upload

2025-03-31 18:54 UTC, paologum commented on server/src/index.ts
> +server.post("/external-chart", moderateRateLimit, uploadTreatiseDatapack);
it gets called when a user presses the button?

2025-04-01 00:11 UTC, Changk820 commented on server/src/index.ts
> +server.post("/external-chart", moderateRateLimit, uploadTreatiseDatapack);
Yes

2025-04-01 00:14 UTC, Changk820 commented on server/src/index.ts
> +server.post("/external-chart", moderateRateLimit, uploadTreatiseDatapack);
![image](https://github.com/user-attachments/assets/351a38f3-8f3f-49dc-be31-616f5d1f60b3)

2025-04-01 00:17 UTC, Changk820 commented on server/src/index.ts
> +server.post("/external-chart", moderateRateLimit, uploadTreatiseDatapack);
That php file will then make a call to that link

2025-04-01 02:10 UTC, Changk820 commented
/deploy

2025-04-01 02:19 UTC, Changk820 commented on server/src/index.ts
> +server.post("/external-chart", moderateRateLimit, uploadTreatiseDatapack);
In the php code I make the call via cURL requests, which doesn't show because the request is made from the treatise server to https://pr-preview.geolex.org/external-chart, not from our browser.

The browser's Network tab can't capture that.

2025-04-01 02:31 UTC, paologum approved these changes

2025-04-01 02:31 UTC, merged