Tsc 578 help rework
earthhistoryviz/tsconline pull request #298
Opened 2024-12-29 05:11 UTC by JacquiFreeElectron

I took out `Contributor` because I think that's the same as the `About` page. we can move `About` in the help page if Prof. Ogg wants.

For the Quick Start Guide, I've placed a beacon before the guide starts, while for other tours, I've disabled this feature. Let me know which style you prefer, and I'll make sure they're consistent across all sections.

https://github.com/user-attachments/assets/dbe84e38-24b1-49ff-8156-57140497994d

2024-12-30 08:08 UTC, paologum commented
/confirm-deploy

2024-12-30 08:10 UTC, paologum commented
i think that the last step should be `finish tour` and not `last`
additionally, i'm going to assume that ogg/aaron would want these not to be hidden in the help tab because these are VERY useful so i would assume there would be a help or tour button of each (datapacks, settings, etc) in each tab that would start the tour, but i think for right now it's ok here. just in the future or on friday i wanna assume they would want that

2024-12-30 08:15 UTC, paologum commented
last front end thing, 
![image](https://github.com/user-attachments/assets/f0279db7-e78c-495c-a95b-cec5b6ee07ad)

this should be capitalized and probably named more appropriately to `View file format info`

2024-12-30 08:23 UTC, paologum requested changes
looks really good i really think this is super beneficial!

2024-12-30 08:23 UTC, paologum commented on app/src/App.tsx
> +                primaryColor: "#6693C9",
for `primaryColor` are you able to use the theme?  we would prefer that so that the theme stays consistent with different palettes

2024-12-30 08:23 UTC, paologum commented on app/src/FileFormatInfo.tsx
> +import transect_template from "./file_format_guide_images/transect_template.png";
to prevent long build times and the like, we should store these on the server then service them from the app

2024-12-30 08:23 UTC, paologum commented on app/src/Help.tsx
> +              functions of each tab on the Nav bar. Click the &apos;Start QSG&apos; button to begin.
tours should also be multilingual so this should be a translation (since they are really important)

2024-12-30 08:23 UTC, paologum commented on app/src/Help.tsx
> +            </TSCButton>
same

2024-12-30 08:23 UTC, paologum commented on app/src/state/state.ts
> +  isWorkshopsTourOpen: boolean;
can you make this all in one object in state like
```
guides: {
...
}

```

2024-12-30 08:23 UTC, paologum commented on app/src/tours.ts
this'll be crazy but these will probably need translation (you don't need to do the translation for chinese yourself but just the english ones and connect/put them in the `en.json`

2024-12-30 17:13 UTC, JacquiFreeElectron commented on app/src/tours.ts
np, I can do the translation for Chinese too

2025-01-02 22:32 UTC, JacquiFreeElectron commented
![Screenshot 2025-01-02 at 5 31 20 PM](https://github.com/user-attachments/assets/edd97508-4f7c-49f9-b4ef-c1d67781300e)![Screenshot 2025-01-02 at 5 31 29 PM](https://github.com/user-attachments/assets/6fdb3e70-6ac1-4c31-9f27-cf3215b0a5a2)

2025-01-03 03:24 UTC, paologum commented
/confirm-deploy

2025-01-03 03:39 UTC, paologum requested changes
dark mode should have a secondary background color palette for the guide tooltips

additionally, switching tabs (when you click settings or datapacks tours) do not change the tab you are on. it still says you are on help when on settings tab for instance.

<img width="779" alt="Screenshot 2025-01-03 at 12 35 14 PM" src="https://github.com/user-attachments/assets/495ec582-dd16-42da-a6f6-40cb269af94f" />

2025-01-03 03:39 UTC, paologum commented on app/src/FileFormatInfo.tsx
> +const serverURL = `${import.meta.env.VITE_SERVER_URL ?? "http://localhost:3000"}/public/file_format_guide_images`;
you should use `devSafeUrl` here, also on the pr preview the images do not load

2025-01-03 16:59 UTC, paologum commented
/confirm-deploy

2025-01-04 04:54 UTC, JacquiFreeElectron commented
/confirm-deploy

2025-01-04 04:57 UTC, JacquiFreeElectron commented
the images load on pr preview now: <img width="1292" alt="Screenshot 2025-01-03 at 11 55 05 PM" src="https://github.com/user-attachments/assets/9e29466f-2daa-43ba-b782-84af584817ee" />
dark mode: 
<img width="491" alt="Screenshot 2025-01-03 at 11 56 43 PM" src="https://github.com/user-attachments/assets/0e9d9b84-b5db-4d6f-96f2-cad647be29dc" />
Tab bug is fixed now: 
<img width="1369" alt="Screenshot 2025-01-03 at 11 57 22 PM" src="https://github.com/user-attachments/assets/5e086238-ea54-4781-b25b-5c61e937865c" />

2025-01-06 20:39 UTC, paologum approved these changes

2025-01-06 20:39 UTC, merged