Tsc 214 column info remove disable checkbox and change color specifically for blocks
earthhistoryviz/tsconline pull request #32
Opened 2024-02-24 23:00 UTC by JacquiFreeElectron

2024-02-25 00:08 UTC, paologum requested changes
some comments

2024-02-25 00:08 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +      return checkbox("column-leaf", disable);
remove disable

2024-02-25 00:08 UTC, paologum commented on app/src/util/util.ts
> +    }
hmm why do you have this check here? i don't believe this is true. if `minDatAge` equals the `userTopAge` but `maxDataAge < userBaseAge` it is enabled. Isn't this already caught by the former if statement on line 23

2024-02-25 00:08 UTC, paologum commented on app/src/util/util.ts
> +        return false
isn't this already caught by the `if` statement on line 23 as well?

2024-02-25 00:08 UTC, paologum commented on shared/src/index.ts
>    info: string,
this changed to `popup` no?

2024-02-25 00:08 UTC, paologum commented on shared/src/index.ts
>    if (typeof o.info !== "string")
`popup`

2024-02-25 00:09 UTC, JacquiFreeElectron commented
https://github.com/earthhistoryviz/tsconline/assets/104879321/3f2aeb7f-8757-451d-861c-5c8c35fafef2

2024-02-25 02:31 UTC, paologum requested changes
tooltip and error icon

2024-02-25 02:31 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
>        }
reduce this to just `let disableCheckbBOx = !dataInRange || details.name === "MA" || details.name === "Root"`

2024-02-25 02:31 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +                }}
you should conditionally load this to have either a checkbox or an error icon with a tooltip attached

2024-02-25 05:23 UTC, JacquiFreeElectron commented
![Screenshot 2024-02-25 at 12 18 12 AM](https://github.com/earthhistoryviz/tsconline/assets/104879321/9417def4-14e0-4c01-913f-b4bc42a18236)

2024-02-25 05:33 UTC, paologum requested changes

2024-02-25 05:33 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +                //disabled={disableCheckBox}
remove this

2024-02-25 05:33 UTC, paologum commented on app/src/util/util.ts
> +    }
just a comment here but once we finish datapack parsing we should not have any at 99999 and -99999

2024-02-25 05:33 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +      if (generateErrorIcon) {
you can shorten this to just have `!dataInrange && !(details.name === "Ma" || details.name === "Root")` in the if statement unless you use it somewhere else

2024-02-25 23:54 UTC, JacquiFreeElectron commented
![Screenshot 2024-02-25 at 6 25 19 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/0dc38929-66df-463b-a96e-89205e32e598)

2024-02-26 04:40 UTC, paologum requested changes

2024-02-26 04:40 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +            </ColumnContainer >
you're condition are only changing `Tooltip` or `TSCCheckbox` so it should conditionally load those not the whole `ColumnContainer`

2024-02-26 04:40 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +                          offset: [0, -20],
can you explain why we need the offset? also can you add arrow to Tooltip

2024-02-26 04:40 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +                      paddingLeft: 9, paddingTop: 7, paddingRight: 9
move to css

2024-02-26 04:40 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +                      paddingLeft: 9, paddingTop: 7, paddingRight: 9
also move fontSize to css too

2024-02-26 04:41 UTC, paologum commented on app/src/SettingsTabs/Column.tsx
> +                          offset: [0, -20],
specifically why it's needed in popper -> modifiers -> offset

2024-02-27 00:34 UTC, paologum approved these changes
looks great!

2024-02-27 00:36 UTC, JacquiFreeElectron commented
Final look: ![Screenshot 2024-02-26 at 7 11 33 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/504c6a0d-3fcd-46a0-aab0-23a9a027b6b0)

2024-02-27 00:36 UTC, merged