Tsc 242 fix time range and column on off
earthhistoryviz/tsconline pull request #33
Opened 2024-02-25 00:02 UTC by jay-jhk-lee

2024-02-25 07:46 UTC, paologum requested changes
looks good, put on backlog to change the params of the xmlToJson to not be `any`

2024-02-25 07:46 UTC, paologum commented on app/src/state/parseSettings.ts
> +          three: `${indent}    `,
rename these to be more representative of what they represent

2024-02-25 07:46 UTC, paologum commented on app/src/state/parseSettings.ts
> +        //TODO: right now it can only do age, implement stage later
on the app side we keep track of the age specifically so you shouldn't need to implement stage at all

2024-02-25 20:33 UTC, paologum requested changes

2024-02-25 20:33 UTC, paologum commented on app/src/state/parseSettings.ts
>            colName !== "Chart Root" &&
i forgot to mention that the root name for the charts is now `Root` not `Chart Root`

2024-02-25 20:33 UTC, paologum commented on app/src/state/parseSettings.ts
> +        xml += generateColumnXml(params.jsonColumn, params.stateColumn, params.indent);
hmmm do you need a `params` object or can you just apply them directly here

2024-02-25 20:59 UTC, jay-jhk-lee commented on app/src/state/parseSettings.ts
> +        xml += generateColumnXml(params.jsonColumn, params.stateColumn, params.indent);
Good idea

2024-02-25 21:00 UTC, jay-jhk-lee commented on app/src/state/parseSettings.ts
>            colName !== "Chart Root" &&
This should still be Chart Root, it's checking the names for the default settings object not the columnInfo object

2024-02-26 04:51 UTC, paologum requested changes
one thing

2024-02-26 04:51 UTC, paologum commented on server/src/routes.ts
> +    const settingsXml = contents;
ok two comments
1. probably just remove `contents` since it's not used for anything and just go straight to `const settingsXml =  await readFile(${decodeURIComponent(settingFile))).toString();`
2. more of a comment but this could go bad with large settings file so at some point try a very large one to test (since we're reading it all in at once with readFile)

2024-02-26 20:19 UTC, paologum requested changes

2024-02-26 20:19 UTC, paologum commented on app/src/state/parseSettings.ts
> +  console.log(stateColumn);
remove

2024-02-26 20:19 UTC, paologum commented on app/src/state/parseSettings.ts
> +        //use preset value for event columns, remove later when event columns are covered
make this a `TODO` comment

2024-02-26 20:19 UTC, paologum commented on app/src/state/parseSettings.ts
> +              useNamed: useNamedValue ? useNamedValue : undefined,
is there a reason you can't just set this to `useNamedVlaue` and `standardizedValue`? Both `undefined` and `null` are falsy so they'll pass any if statements.

2024-02-27 01:08 UTC, paologum approved these changes
at some point the one console log should either be taken out or formatted to a nicer string but overall good

2024-02-27 01:25 UTC, merged