TSC-146-Read-Excel-Sheet-and-Send-to-App
earthhistoryviz/tsconline pull request #35
Opened 2024-02-25 06:16 UTC by SejalKumar03

Changed useEffect to useContext and fixed dropdown connection with text

2024-02-25 07:39 UTC, paologum requested changes
almost done!!

2024-02-25 07:39 UTC, paologum commented on server/assets/datapacks/AfricaBight.map
remove this file

2024-02-25 07:39 UTC, paologum commented on server/assets/datapacks/AfricaBight.map
and the directory `assets/datapacks`

2024-02-25 07:39 UTC, paologum commented on server/assets/datapacks/Hominids_wImages_GTS2020_Encrypted.dpk
same

2024-02-25 07:39 UTC, paologum commented on server/assets/datapacks/TimeTree_of_Life_GTS2020_ENCRYPTED_23Jan2020.dpk
same

2024-02-25 07:39 UTC, paologum commented on server/src/index.ts
> +server.post('/charts', async (request, reply) => {
this should be the `routes.fetchChart` method we talked about

2024-02-25 07:39 UTC, paologum commented on server/src/routes.ts
> +function readExcelFile(filePath: string) {
can you put this method in a file called `parse-excel-file` and rename to `parseExcelFile`

2024-02-25 07:39 UTC, paologum commented on app/src/state/state.ts
> +    geologicalBaseStageAges: TimescaleItem[];
we should only have two arrays `geologicalTopStageAges` and `geologicalBaseStageAges` and they should be located where `GeologicalTopStageAges` and `GeologicalBaseStageAges` are currently so just those two and make them camel case

2024-02-25 07:39 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +              actions.setSelectedTopStage(age.toString());
set it to N/A instead of `age.toString()` since the `age` probably won't correspond to a key

2024-02-25 07:39 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +              actions.setSelectedBaseStage(age.toString());
same

2024-02-25 08:16 UTC, SejalKumar03 commented on server/assets/datapacks/AfricaBight.map
You want me to delete the entire server/assets/datapacks? But there's other things in there. Should I move things outside the directory?

2024-02-25 08:31 UTC, paologum commented on server/assets/datapacks/AfricaBight.map
you should just delete them with `git rm --cached` because the datapacks shouldb't be on the remote repo. they should just be available on your local machine. normally they should be .gitignored automatically. you can do `git rm -r --cached server/assets/datapacks`

2024-02-25 20:27 UTC, paologum requested changes
just some code styling/refactoring but the functionality looks great!

2024-02-25 20:27 UTC, paologum commented on server/src/parse-excel-file.ts
> +    const dataWithoutFirstRow = jsonData.slice(1);
can you rename this `dataWithoutHeader` so anyone reading this understands why you sliced

2024-02-25 20:27 UTC, paologum commented on server/src/parse-excel-file.ts
> +    }
if this is empty you should throw an error that says no timescale data to parse

2024-02-25 20:27 UTC, paologum commented on server/src/parse-excel-file.ts
> +    }
also can i ask why you `slice` here?

2024-02-25 20:27 UTC, paologum commented on server/src/routes.ts
> +    const filePath = '../default_timescale.xlsx';
since this is an asset can you move `default_timescale.xlsx` into the `server/assets` folder and make a new field in the `server/assets/config.json` that specifices this filepath.

you'll have to change the `AssetConfig` type and `asserts` in the `server/src/types.ts` file to account for your new change.

Once you do you can just use `assetconfigs.timescaleFilepath` or whatever you name the field in the `config.json` file.

2024-02-25 20:27 UTC, paologum commented on server/src/routes.ts
> +    const filePath = '../default_timescale.xlsx';
let me know if you have any questions about this

2024-02-27 02:07 UTC, SejalKumar03 commented on server/src/parse-excel-file.ts
> +    }
Because I am getting rid of the first 3 columns since they are just black in the excel sheet

2024-03-09 23:21 UTC, paologum requested changes

2024-03-09 23:21 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    // geologicalBaseStageAges: [],
remove

2024-03-09 23:21 UTC, paologum commented on app/src/state/state.ts
> +    // geologicalBaseStageAges: TimescaleItem[];
remove

2024-03-09 23:21 UTC, paologum commented on app/src/state/state.ts
> +    // geologicalBaseStageAges: [],
remove

2024-03-09 23:21 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +              if (selectedAgeNumber >= 0 && selectedAgeNumber <= state.settings.baseStageAge) {
hmm there isn't a reason to turn the value to a string and then parse the float since it is already a number so just change it to use `const selectedAgeItem = .... || 0` and check on that

2024-03-09 23:21 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +              if (selectedAgeNumber >= 0 && selectedAgeNumber >= state.settings.topStageAge) {
same as above

2024-03-09 23:21 UTC, paologum commented on server/src/parse-excel-file.ts
> +  // }
remove

2024-03-09 23:21 UTC, paologum commented on server/src/parse-excel-file.ts
> +  }
since you make a check if `length == 0` you don't need to check that one index exists, so you can just slice the 3 without the `if`

2024-03-09 23:21 UTC, paologum commented on shared/src/index.ts
> +
can you move this to the top, so all of the types are grouped together

2024-03-09 23:21 UTC, paologum commented on shared/src/index.ts
> +    throw new Error(`Timescale object must have 'key' of type string and 'value' of type number`);
can you use the new `throwError` method

2024-03-09 23:21 UTC, paologum commented on shared/src/index.ts
> +}
i don't think this method is very useful in regards to it being refactored and in shared. can you just make this `if` statement where it's being used? i'll add another comment there too

2024-03-09 23:21 UTC, paologum commented on server/src/parse-excel-file.ts
> +  }
hmmm this is where you would change it but that return will never get hit because that `assert` method throws an error if it's empty and if it reaches this point, it will always be empty. you probably should just throw an error then and not return and deprecate `assertTimescaleDataWithoutHeader`

2024-03-09 23:21 UTC, paologum commented on package.json
> +    "xlsx": "^0.18.5"
can you remove xlsx from the `root` packages, it should only be needed in the `server` dir

2024-03-09 23:22 UTC, paologum commented on package.json
> +    "xlsx": "^0.18.5"
you can just do `yarn remove xlsx` in `tsconline`

2024-03-10 05:12 UTC, paologum requested changes
ok last thing 😭

2024-03-10 05:12 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
> +    navigate("/chart");
oops i forgot to mention this is supposed to be `actions.fetchChartFromServer(navigate)` and `actions.setTab(1)`
and get rid of everything else 

after you do this just verify it works one more time just to make sure

2024-03-10 05:15 UTC, paologum commented on app/src/SettingsTabs/Time.tsx
okok and one more thing don't import `actions` from `state`, the only thing you should import from `state` is `context`

instead to access actions do `const { state, actions } = useContext(context)`  on line 18 and get rid of the import on line 3

2024-03-10 18:20 UTC, paologum approved these changes
great!

2024-03-10 19:18 UTC, asivath commented on app/src/SettingsTabs/Time.tsx
> +              }
having an error message that pops up when stage is invalid would be user friendly. easiest way would be to use the TSCError component and the pushError action. same for any other user input

2024-03-11 04:53 UTC, SejalKumar03 commented
https://github.com/earthhistoryviz/tsconline/assets/119654886/3e6227e0-99c1-4b08-9a14-9732180095f4

2024-03-11 22:13 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      console.error("Server responds with:", response.status);
i forgot to mention this but can you call `displayError` with the appropriate parameters here
i believe `displayError(null, response, "{message you want}")` would work

2024-03-11 22:15 UTC, paologum requested changes

2024-03-11 22:15 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    console.error("Error fetching timescale data:", error);
same here you can either call it with `displayError(null, null, message)` or `pushError(message)`

2024-03-11 22:19 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      console.error("Server responds with:", response.status);
except you want the response json since we need to access the error message so you need `await response.json()`

2024-03-11 22:24 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      console.log("Time Scale Data Loaded");
multiple warning also occur when you edit `state.geologicalBaseStageAges` and `state.geologicalTopStageAges` in place so instead just use a temporary variable called `geologicalBaseStageAges` and `state.geologicalTopStageAges` and then set them as you do on 122 instead of doing it on `state`

2024-03-12 18:58 UTC, asivath approved these changes

2024-03-12 22:47 UTC, paologum approved these changes

2024-03-12 22:49 UTC, merged