Tsc 244 reformat add block columns to reflect documentation
earthhistoryviz/tsconline pull request #43
Opened 2024-03-02 02:13 UTC by JacquiFreeElectron

2024-03-02 03:00 UTC, paologum requested changes
some changes

2024-03-02 03:01 UTC, paologum commented on server/src/parse-datapacks.ts
> +          block.color.b = Number(rgb[2]!);
you probably could just check it with `assertRGB` and not with an `isNaN` here

2024-03-02 03:02 UTC, paologum commented on server/src/parse-datapacks.ts
>        i = i - 1;
instead of nested if statements, they're each their own one `if` statement

2024-03-07 02:15 UTC, paologum requested changes
some changes but overall great

2024-03-07 02:15 UTC, paologum commented on shared/dist/tempCodeRunnerFile.ts
what is this file? you should probably delete this if you don't know

2024-03-07 02:15 UTC, paologum commented on server/src/parse-datapacks.ts
> +      }
you should put the `isNaN` inside the first if statement after `block.width` gets set since you'd be making unnecessary checks on widths that don't exist.

2024-03-07 02:15 UTC, paologum commented on server/src/parse-datapacks.ts
> +      const subBlockInfo = processBlock(line, parameterRGB);
you can just do `const subBlockInfo = processBlock(line, {...block.rgb});`
which is an inline shallow copy of what you're doing

2024-03-07 02:15 UTC, paologum commented on server/src/parse-datapacks.ts
> +        block.popup = tabSeperated[6];
hmm there might be some popups might not have "" surrounding them so you can just have "if it exists at index 6" it is guranteed to be a popup.

unless you think otherwise

2024-03-07 02:15 UTC, paologum commented on server/src/parse-datapacks.ts
> +      }
move the `try` also into the above `if` statement on line 266 because we should only check if we actually change the value

2024-03-07 02:16 UTC, paologum commented on server/__tests__/parse-datapacks.test.ts
> +    const defaultColor = { r: 255, g: 255, b: 255 };
this will also mean removing the declaration at all the other tests for `color` but i won't spam you and make all those comments 💀

2024-03-13 02:50 UTC, paologum commented on server/src/parse-datapacks.ts
> +        block.width = Number(tabSeperated[2]);
this is something i'm doing for event headers but since this is getting kind of big, can you refactor this to a function called `setBlockHeaders(block, tabSeperated)`

2024-03-13 23:56 UTC, paologum approved these changes
looks good!

2024-03-14 01:46 UTC, asivath approved these changes

2024-03-14 01:47 UTC, merged