Tsc 246 create type for default settings
earthhistoryviz/tsconline pull request #52
Opened 2024-03-09 04:12 UTC by jay-jhk-lee

created types ending in TSC, which are types directly mirroring the xml settings files. Modified parsing to accommodate using the new types. Added asserts.

2024-03-11 03:04 UTC, paologum requested changes

2024-03-14 18:35 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  }
added check

2024-03-14 19:48 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
>    return fonts;
This doesn't disable changing fonts because processFonts is used for the xmlToJson function. The changing of the fonts is done in jsonToXml. Right now I have the initial fonts set to defaultFontsInfo.

2024-03-14 19:49 UTC, jay-jhk-lee commented on shared/src/index.ts
> +  lineType: string;
mb i changed it back

2024-03-14 23:15 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  }
Sounds good, added checks and added assert at the end of parsing

2024-03-14 23:28 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
>  function processSettings(settingsNode: any): any {
I'm not planning on it. This variable, which is a DOM node, comes from the DOM parser which isn't controlled by me. The most I could do is create asserts to check if it has certain elements, but it's not necessary since the xmlToJson function iterates through all the elements in the node and checks them anyways.

2024-03-14 23:28 UTC, jay-jhk-lee commented on app/src/state/actions/general-actions.ts
> +export const setSettingsColumns = action((temp: ColumnInfo | undefined) => {
changed

2024-03-14 23:28 UTC, jay-jhk-lee commented on app/src/state/actions/general-actions.ts
> +  //state.settingsJSON["settingsTabs"] = state.settingsTabs;
deleted

2024-03-14 23:28 UTC, jay-jhk-lee commented on app/src/state/actions/general-actions.ts
> +// });
deleted

2024-03-15 14:09 UTC, paologum requested changes

2024-03-15 14:09 UTC, paologum commented on shared/src/settings-types.ts
> +  //TODO add fonts info assert here
this exists i'm pretty sure on `index.ts`

2024-03-15 14:09 UTC, paologum commented on app/src/state/parse-settings.ts
> +function processSettings(settingsNode: any): ChartSettingsInfoTSC {
wait i'm confused because shouldn't this be of type `ChartSettingsInfoTSC`? Like the settings file we receive and the settings file we return should basically be the same type

2024-03-15 14:09 UTC, paologum commented on app/src/state/parse-settings.ts
> +      //updateColumn(attribute.name, attribute.value);
take this out?

2024-03-15 14:09 UTC, paologum commented on app/src/state/parse-settings.ts
> +    pointType: undefined,
you can just not define these. if you don't define them, the keys are auto undefined. you probably should just take them out for readability purpose

2024-03-15 14:09 UTC, paologum commented on app/src/state/parse-settings.ts
> +function processColumn(node: any, id: string): ColumnInfoTSC {
same here, can't the type be `ColumnInfoTSC`?

2024-03-15 14:09 UTC, paologum commented on app/src/state/parse-settings.ts
> +        //
delete

2024-03-15 14:09 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +        console.log(e);
can you console.error this instead

2024-03-17 02:48 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
got it

2024-03-17 03:57 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +function processSettings(settingsNode: any): ChartSettingsInfoTSC {
Short answer: No. 
Long answer:
settingsNode can't be changed to ChartSettingsInfoTSC because it is of type Element (I'll change it from any). It comes from a XML DOM. 
settingsNode looks like this:
<img width="476" alt="image" src="https://github.com/earthhistoryviz/tsconline/assets/89719669/44eafc11-70e2-4113-9c92-d2c7933e44bb">
What the parser is doing is converting the Element to a JSON object of type ChartSettingsInfoTSC. This is true for all the process functions in xmlToJson. Lmk if you have any more questions. I'll change the function parameters to have type Element.

2024-03-17 04:10 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +    pointType: undefined,
I've tried it without defining them but the updateColumn function throws an error if the settingName isn't already defined in the object.

2024-03-17 04:10 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +function processColumn(node: any, id: string): ColumnInfoTSC {
read above

2024-03-17 04:12 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +  //TODO add fonts info assert here
I looked at it and it doesn't seem completed. It's not updated from leyton's pr. I'll add it after it's merged.

2024-03-17 04:13 UTC, jay-jhk-lee commented on app/src/state/actions/general-actions.ts
> +        console.log(e);
yep

2024-03-17 04:19 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +    pointType: undefined,
The problem is I'm checking if the settingName is in the column object. If it doesn't exist, then it throws an error. I've tried making a function that checks if the string is in ChartSettingsInfoTSC, but that didn't work either.

2024-03-20 18:55 UTC, paologum commented on shared/dist/index.d.ts
this is new based on the most updated version of main but after you rebase or resovle conflicts with `origin/main` get rid of all files in `dist` and `dist` itself. `dist` should be ignored and stored locally only now

2024-03-29 00:46 UTC, paologum requested changes

2024-03-29 00:46 UTC, paologum commented on shared/src/settings-types.ts
> +export function assertZoneColumnInfo(o: any) {
shouldn't this `assertZoneColumnInfo`?

2024-03-29 00:46 UTC, paologum commented on shared/src/settings-types.ts
> +export function assertRulerColumnInfo(o: any) {
same

2024-03-29 00:46 UTC, paologum commented on shared/src/settings-types.ts
> +export function assertPointColumnInfo(o: any) {
whoops same here too

2024-03-29 00:46 UTC, paologum commented on shared/src/settings-types.ts
> +  if (typeof o.pad !== "number") throwError("ColumnInfoTSC", "pad", "number", o.pad);
you probably should make another `assertColumnBasicInfo` for easier readability of this

2024-03-29 00:46 UTC, paologum commented on app/src/state/parse-settings.ts
>    return fonts;
can this be of type element and also i forget but are you getting rid of all the changes to font?

2024-03-29 00:46 UTC, paologum commented on app/src/state/parse-settings.ts
> +function processColumn(node: any, id: string): ColumnInfoTSC {
can't node be of type `Element`

2024-03-29 00:46 UTC, paologum commented on app/src/state/parse-settings.ts
> +  chartSettings: any,
you can make a type for this since we handle this in `state`

2024-03-29 02:52 UTC, jay-jhk-lee commented on app/src/state/actions/general-actions.ts
> +        settingsXml = await res.text();
I moved it to the beginning so that if it fails then it returns without changing the state

2024-03-29 02:52 UTC, jay-jhk-lee commented on app/src/state/actions/general-actions.ts
> +      }
same

2024-03-29 02:52 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  return column as ColumnInfoTSC;
got it

2024-03-29 02:55 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
>    return fonts;
This doesn't remove the changes. All this is doing is setting the defaultFontsInfo to all of the fonts in settingsTSC. The changes to fonts that are done on the website are reflected when parsing from json to xml.

2024-03-29 02:55 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
>    return fonts;
and yeah i can change the type

2024-03-29 02:57 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  chartSettings: any,
got it

2024-03-29 03:01 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +export function assertZoneColumnInfo(o: any) {
I think no because of the way I set it up. ZoneColumnInfo is a type that has the properties that only shows up in ZoneColumns. the object passed into assertZoneColumnInfo is the entire column object with other properties too, i.e. ColumnInfoTSC. So this shouldn't be `assert as ZoneColumnInfo` because the object passed should be ColumnInfoTSC.

2024-03-29 03:01 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +export function assertRulerColumnInfo(o: any) {
same

2024-03-29 03:01 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +  if (typeof o.pad !== "number") throwError("ColumnInfoTSC", "pad", "number", o.pad);
ok

2024-03-29 03:04 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +export function assertPointColumnInfo(o: any) {
same

2024-03-29 05:48 UTC, paologum requested changes

2024-03-29 14:33 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +export function assertColumnBasicInfo(o: any) {
got it

2024-03-29 22:54 UTC, paologum requested changes

2024-03-29 22:54 UTC, paologum commented on app/src/state/parse-settings.ts
> +    let settingValue: any = "";
same or if this is a string or number it should be declared as such

2024-03-29 22:54 UTC, paologum commented on shared/src/settings-types.ts
> +export function assertZoneColumnInfo(o: any) {
the way it works it'll still be asserted as the parent if you call `assertColumnInfoTSC` as the outer asserts, you should still assert zone and all the others

2024-03-29 22:54 UTC, paologum commented on app/src/state/parse-settings.ts
> +  const column: any = {};
same should have a default, not using any

2024-03-30 00:23 UTC, jay-jhk-lee commented on shared/src/settings-types.ts
> +export function assertZoneColumnInfo(o: any) {
what do you mean by the parent? assertColumnInfoTSC doesn't check parent or children relationship

2024-03-31 23:27 UTC, paologum commented on shared/src/settings-types.ts
> +export function assertZoneColumnInfo(o: any) {
basically just change the asserts to assert the correct object and see if that works because i'm like 99% sure it should work

i do the same for `ColumnHeaderProps`

2024-04-01 00:03 UTC, paologum requested changes

2024-04-01 21:08 UTC, paologum requested changes
just one change

2024-04-01 21:08 UTC, paologum commented on app/src/state/parse-settings.ts
>  function generateFontsXml(fonts: any, colName: string, stateColumn: any, indent: string): string {
this needs to be changed with leyton's pr
maybe not necessarily in this pr but fonts in leyton's pr should be of type `FontsInfo` and `stateColumn` is also definitely defined

2024-04-01 21:08 UTC, paologum commented on shared/src/settings-types.ts
> +    }
shouldn't the text check be outside this if

2024-04-02 00:52 UTC, paologum approved these changes
looks good just verify everything works on the website before you push (that deals with generating charts with settings files)

2024-04-02 01:09 UTC, merged