General Color Picker
earthhistoryviz/tsconline pull request #59
Opened 2024-03-20 22:17 UTC by rohnach29

<img width="219" alt="Screenshot 2024-03-20 at 6 16 11 PM" src="https://github.com/earthhistoryviz/tsconline/assets/112187753/814787e4-32d7-4b43-b1d8-bc22ef3105d3">

2024-03-21 01:44 UTC, paologum requested changes
Three things, your implementation or the front end doesn't show a way of saving the colors. From how I see things those colors are just for visuals and are always constant. Second, what does the black box in the top left of your screenshot symbolize. Third, this pr should include the implementation/integration of the picker into the required spaces.

2024-03-21 01:44 UTC, paologum commented on app/package.json
> +    "react-color": "2.17.1",
if you're just using `react-color`, get rid of `mui-color-input` in `app`

2024-03-21 01:44 UTC, paologum commented on app/src/components/TSCColorPicker.tsx
> +          <SketchPicker color={selectedColor} onChange={handleColorChange} />
why are we expecting error here? we should probably fix this

2024-03-21 01:44 UTC, paologum commented on package.json
> +    "canvas": "^2.11.2",
i don't think canvas needs to be on the monorepo

2024-03-29 01:23 UTC, paologum requested changes

2024-03-29 01:23 UTC, paologum commented on app/src/components/TSCColorPicker.tsx
> +const colorStore = new ColorStore();
`presetColors` should be defined in the state, not here as a class. `updatePresetColors` should be an action that updates `presetColors`

2024-03-29 01:23 UTC, paologum commented on app/src/components/TSCColorPicker.tsx
> +
should be in `state`

2024-03-29 01:23 UTC, paologum commented on app/src/components/TSCColorPicker.tsx
> +        <div style={{ position: "absolute", zIndex: 2 }}>
move this to css

2024-04-02 02:24 UTC, paologum requested changes
you might as well just add to this pr since you will be connecting `FontMenu` to also connect your previous background color task since it shouldn't be more than the work you've had here

2024-04-02 02:24 UTC, paologum commented on app/src/state/state.ts
> +
put this in a file called `constant.ts` in `util`

2024-04-12 07:38 UTC, paologum requested changes

2024-04-12 07:38 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +import TSCColorPicker from "../components/TSCColorPicker";
two of the same imports?

2024-04-12 07:38 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +    fontOpts.color = color;
you should still use the action, just change the parameters to what works with your variables

2024-04-12 07:38 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +export const ChangeColor: React.FC = observer(() => {
this should be named something more specific like ChangeBackgroundColor

2024-04-12 07:38 UTC, paologum commented on app/src/SettingsTabs/ColumnMenu.tsx
> +            <ChangeColor />
change color should be above font, maybeee above edit name field but at least for now put it above font
also add a new demo

2024-04-12 07:38 UTC, paologum commented on app/src/components/TSCColorPicker.tsx
> +      )}
this should probably close on any click outside of the box

2024-04-12 07:40 UTC, paologum requested changes

2024-04-12 07:40 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +  const [selectedColor, setSelectedColor] = useState("#000"); // State to keep track of selected color
also this isn't connected to background color, you should connect it as part of the pr as well

2024-04-12 07:40 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +  );
no unneeded div use <>

2024-04-20 05:52 UTC, paologum requested changes

2024-04-20 05:52 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +      </div>
react fragment instead of divs

2024-04-20 05:52 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +      </div>
same

2024-04-20 05:52 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +          <Typography className="not-avail" style={{ display: "inline" }}>
if you already have a className just add the `style={{ display: "inline" }}>` there

2024-04-20 05:52 UTC, paologum commented on app/src/SettingsTabs/BackgroundColor.tsx
> +import { setRGB } from "../state/actions";
you should be using `useContext` to access any `action`

2024-04-20 05:52 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +import { convertHexToRGB } from "../state/actions/util-actions";
same

2024-04-20 05:52 UTC, paologum commented on app/src/SettingsTabs/FontMenu.tsx
> +          <TSCColorPicker color={fontOpts.color} onColorChange={handleColor} disabled={!fontOpts.on} />
this needs a key as well

2024-04-20 05:52 UTC, paologum commented on app/src/state/actions/util-actions.ts
> +}
these aren't actions so they should just go in `util.ts` and also why do you have three total exported functions?

2024-04-20 05:52 UTC, paologum commented on app/src/state/parse-settings.ts
> +            }
remove log

2024-04-20 05:52 UTC, paologum commented on app/src/state/parse-settings.ts
> +          }
this should be inserting it on the tag `backgroundColor` not `useNamed`
` <setting name="backgroundColor" useNamed="false">rgb(255,204,204)</setting>`

2024-04-23 18:32 UTC, rohnach29 commented on app/src/state/actions/util-actions.ts
> +}
I need the two functions for type overloading, otherwise typescript is getting confused about the type that is returned and i get yarn build errors

2024-04-24 22:11 UTC, paologum requested changes
one thing :D

2024-04-24 22:11 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${xmlKey}" useNamed="false">rgb(${stateColumn?.rgb.r},${stateColumn?.rgb.g},${stateColumn?.rgb.b})</setting>\n`;
is there a reason it's `stateColumn?` ? `stateColumn` can never be null or undefined if i'm reading correctly

2024-04-24 22:15 UTC, rohnach29 commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${xmlKey}" useNamed="false">rgb(${stateColumn?.rgb.r},${stateColumn?.rgb.g},${stateColumn?.rgb.b})</setting>\n`;
Oh I think it autocorrected to that, I'll change that

2024-04-25 00:53 UTC, paologum approved these changes
looks good :D

2024-04-25 01:35 UTC, merged