Tsc 229 style popup and show popup
earthhistoryviz/tsconline pull request #63
Opened 2024-03-27 16:27 UTC by asivath

Added popups and also allowed panning/zooming on the SVG. The reason the SVG needs to be embedded into the DOM rather than within an object tag is because of the CORS policies. If it's in an object tag and because the chart comes from a different source than the app, the policy will block a lot of its interactivity. Directly embedding is a bit unsafe so I verify where the SVG comes from and also sanitize the SVG.

https://github.com/earthhistoryviz/tsconline/assets/94872897/a081dd55-a9cb-47ed-850d-0bcd2af9c813

https://github.com/earthhistoryviz/tsconline/assets/94872897/e993dd9f-20d4-4cf8-aa81-9239c72b5aaa

2024-03-27 21:19 UTC, paologum requested changes
some comments

2024-03-27 21:19 UTC, paologum commented on app/src/components/TSCSvgComponent.tsx
> +    if (!state.settings.mouseOverPopupsEnabled) return;
does this still have the weird functionality where it has to be clicked twice to turn on between calls

2024-03-27 21:19 UTC, paologum commented on app/src/components/TSCSvgComponent.tsx
> +    fetch(path)
change the error as well to a general error code for invalid paths

2024-03-27 21:19 UTC, paologum commented on app/src/components/TSCPopupManager.tsx
> +    return <div>Invalid SVG Path. Please check the path and try again.</div>;
make this `Typography`

2024-03-27 21:19 UTC, paologum commented on app/src/components/TSCSvgComponent.tsx
> +    return <div>Invalid SVG Path. Please check the path and try again.</div>;
same as above

2024-03-28 20:21 UTC, asivath commented on app/src/components/TSCSvgComponent.tsx
> +    if (!state.settings.mouseOverPopupsEnabled) return;
ya nothing resets them between calls

2024-03-28 20:53 UTC, paologum commented on app/src/components/TSCSvgComponent.tsx
> +    if (!state.settings.mouseOverPopupsEnabled) return;
can you fully describe what's happening or should happen because i'm a little confused. a video of you doing it would also be helpful. i think i might know but i'm not sure

2024-03-28 21:19 UTC, asivath commented on app/src/components/TSCSvgComponent.tsx
> +    if (!state.settings.mouseOverPopupsEnabled) return;
https://github.com/earthhistoryviz/tsconline/assets/94872897/c090c18f-209f-4ee5-9337-c653d8af86e2

if you want to turn the popups back off you need to click twice

2024-03-29 01:02 UTC, asivath commented
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/2dd3ca4e-7226-40f8-853a-6a448bf1c4af)

2024-03-29 01:28 UTC, paologum commented on app/src/components/TSCSvgComponent.tsx
> +    if (!state.settings.mouseOverPopupsEnabled) return;
can you add in the pr line 140 in `Time.tsx` to add `checked={state....mouseOverPopup}` in `TSCCheckbox`

2024-03-29 01:42 UTC, paologum requested changes

2024-03-29 01:42 UTC, paologum commented on server/src/routes.ts
> +    }
in the future, you will also have to check the user images in their respective `upload` directory.
you don't have to do that until the framework is fully setup with login (comment only)

2024-03-29 01:42 UTC, paologum commented on server/src/routes.ts
> +  const imagePath = `${assetconfigs.decryptionDirectory}/${request.params.datapackName}/datapack-images/${request.params.imageName}`;
you should use `path.join` here just in case

2024-03-29 01:42 UTC, paologum commented on app/src/components/TSCSvgComponent.tsx
> +
besides the event listener settings, can't this exist as it's own function? still in the component but outside of the `useEffect`? both `chartContent` and `state.settings.mousOverPopupsEnabled` will change due to observer and reload the component properly so if you just put the return stuff inside the handler it should be the same and be a little more abstracted

2024-03-29 01:44 UTC, paologum commented
> ![image](https://private-user-images.githubusercontent.com/94872897/317924007-2dd3ca4e-7226-40f8-853a-6a448bf1c4af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NzY4OTYsIm5iZiI6MTcxMTY3NjU5NiwicGF0aCI6Ii85NDg3Mjg5Ny8zMTc5MjQwMDctMmRkM2NhNGUtNzIyNi00MGY4LTg1M2EtNmE0NDhiZjFjNGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAxNDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTdkMWMzYmExMGU3YTA2ZmQwZWNmOTAxNTY1MWQwYTc3ODQyOGU2NDY1ZjM4NWFlNzJmMjY2NTI5OTUxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bq9ThNmLNEy7x3Jl7nuidybBSRF8Ql-Mz4_r-tQ7C28)

can you make the close an x in the top right?

2024-03-29 15:03 UTC, asivath commented
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/a832d18c-905e-4d10-b024-8f904b57c724)

2024-03-29 21:25 UTC, paologum approved these changes
one question/comment

2024-03-29 21:25 UTC, paologum commented on app/src/components/TSCPopupManager.tsx
> +          }
do you think we shouldn't `pushError` here? or in `actions.fetchImage`?

2024-03-29 21:38 UTC, asivath commented on app/src/components/TSCPopupManager.tsx
> +          }
should we show errors to the user that they can't do anything about?

2024-03-29 21:39 UTC, asivath commented on app/src/components/TSCPopupManager.tsx
> +          }
acutally user datapacks can have images right?

2024-03-29 21:45 UTC, paologum commented on app/src/components/TSCPopupManager.tsx
> +          }
yeah they can/should, but also we show server errors which technically they can't do anything about

2024-03-29 22:23 UTC, merged