Tsc 133 active datapack
earthhistoryviz/tsconline pull request #65
Opened 2024-03-29 08:30 UTC by rupp3

![Screenshot 2024-03-29 031841](https://github.com/earthhistoryviz/tsconline/assets/54484966/438878a2-e623-4a6e-98e0-d75d347b8119)
![Screenshot 2024-03-29 031818](https://github.com/earthhistoryviz/tsconline/assets/54484966/e8c4addf-44f7-4bd9-8db3-bfb980de9341)

Datapacks are displayed on the datapacks settings tab, when checkbox checked they are added to the columns setting tab and when unchecked they are removed

2024-03-29 08:38 UTC, rupp3 commented
will fix dist issue tomorrow

2024-03-29 21:13 UTC, paologum requested changes

2024-03-29 21:13 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +                      onChange={() => handleCheckboxChange(datapack)}
should just be `state.config.datapacks.includes(datapack.name)`

2024-03-29 21:13 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +
this should all just be if the `state.config.datapacks.includes(name)` then call `actions.setDatapackConfig` with the array minus that datapack

if it does not include the datapack, then call it with the datapack

there shouldn't be any need for `useEffect` or a `useState` variable like `prevSelectedDatapacks`

2024-03-30 07:56 UTC, rupp3 commented on app/src/Settings.tsx
> +        return null;
nah, i think i put it out of habit and then forgot. i'll remove it

2024-04-01 15:51 UTC, rupp3 commented on app/src/SettingsTabs/Datapack.tsx
> +                      onChange={() => handleCheckboxChange(datapack)}
```
checked={state.config.datapacks.includes(datapack)}
                      onChange={() => handleCheckboxChange(datapack)}
```
changed it to this

2024-04-01 15:54 UTC, rupp3 commented
have not rebased yet due to conflicts but wanted to get this up so changes could be reviewed

2024-04-01 21:00 UTC, paologum requested changes

2024-04-01 21:00 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +        state.config.settingsPath
i would instead of `state.config.settingsPath` put `""` for now because since we are combining datapacks, the settings path technically doesn't exist at the moment. we will figure that stuff out later, so we'll just operate under the assumption it doesn't exist

2024-04-02 02:58 UTC, rupp3 commented on server/src/types.ts
> +
oops, this should not be in here. i removed all of the description stuff i did bc i knew it didnt work and was planning on making it a separate branch/task but i guess somewhere during rebasing it came back

2024-04-02 03:00 UTC, rupp3 commented on server/src/types.ts
> +  if (typeof o !== "object" || !o) throw "AssetConfig must be an object";
oops again i was copying assertAssetConfig and didnt change it

2024-04-02 05:32 UTC, rupp3 commented
removed the extra description stuff but i will fix your comments on my other branch and push it to github asap

2024-04-02 06:21 UTC, paologum requested changes
just one thing

2024-04-02 06:21 UTC, paologum commented on server/assets/server-datapacks.json
if you're changing this on your branch, you shouldn't have this file on this pr and just add this to your other branch

2024-04-02 17:25 UTC, paologum approved these changes

2024-04-02 17:52 UTC, merged