Tsc 236 add general snackbar
earthhistoryviz/tsconline pull request #67
Opened 2024-03-30 14:03 UTC by JacquiFreeElectron

![Screenshot 2024-03-29 at 11 59 10 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/65e11298-a4f8-4a05-816d-bba75c333554)
![Screenshot 2024-03-29 at 11 59 21 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/2cbfa448-70f7-4a7a-9eac-fd88c14ea2bd)
![Screenshot 2024-03-29 at 11 58 20 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/6df3e138-2bc0-4df7-bf8f-87493d5ff145)

2024-03-30 19:34 UTC, paologum requested changes
last thing, can you show me/upload what happens when the text overflows in the alert?
also the photo provided has the text slightly miscentered. You might need to `justify-content: center, align-items: center` for the text to be aligned

2024-03-30 19:34 UTC, paologum commented on app/src/App.css
> +  /*width: 100%;*/
remove this comment if you don't need it

2024-03-30 19:34 UTC, paologum commented on app/src/assets/icons/info-icon.json
just curious what website did you grab this from

2024-03-30 19:34 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  }
instead of checking the severity with an if, just make the parameter `severity: "success" | "info"`

2024-03-30 19:34 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +}); */
remove

2024-03-30 19:34 UTC, paologum commented on app/src/state/actions/util-actions.ts
> +}
no need for this, the `displayError` you're probably basing this on is specifically for server responses that throw errors where it requires a specific method to print out the server response. you can just use `pushSnackbar`

2024-03-30 19:34 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  state.openSnackbar = true;
you can deprecate `state.openSnackbar` and just make all snackbars that are pushed default to `show=true`. if they exist, they should always be shown

2024-03-30 19:34 UTC, paologum commented on app/src/components/TSCSnackbar.tsx
> +      open={state.openSnackbar}
should just be true

2024-03-30 19:59 UTC, JacquiFreeElectron commented on app/src/assets/icons/info-icon.json
LottieFiles

2024-03-30 20:01 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
> +  state.openSnackbar = true;
I tried this way, but there is always one snackbar that never goes away. I can try it again, but if it's not working, can I keep `state.openSnackb`ar?

2024-03-30 20:05 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  state.openSnackbar = true;
hmm that technically means that there exists a snackbar within the array that sticks around. i would try debugging and stuff because the array should not exist/have any contents after 5 seconds of an info/success bar getting pushed.

2024-03-30 20:07 UTC, JacquiFreeElectron commented on app/src/state/actions/general-actions.ts
> +  state.openSnackbar = true;
okk

2024-04-01 16:43 UTC, JacquiFreeElectron commented
![Screenshot 2024-04-01 at 12 27 44 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/5772bb1c-0a9f-43a3-b252-6032c9314dfc)
![Screenshot 2024-04-01 at 12 27 14 PM](https://github.com/earthhistoryviz/tsconline/assets/104879321/c6565639-5963-48ce-9515-3fdf90b94125)

2024-04-01 22:47 UTC, JacquiFreeElectron commented
https://github.com/earthhistoryviz/tsconline/assets/104879321/e20651a5-cd51-47e1-b590-3cd7e2cbfc9b

2024-04-02 01:06 UTC, paologum requested changes

2024-04-02 01:06 UTC, paologum commented on app/src/components/TSCSnackbar.css
> +.snackabr {
hmm this should probably be snackbar

2024-04-02 01:06 UTC, paologum commented on app/src/components/TSCSnackbar.tsx
> +        className="snackabr"
same

2024-04-02 01:06 UTC, paologum commented on app/src/App.css
>    flex-grow: 1;
probably move this to TSCSnackbar.css since the actual snackbar class is there. also snackabr was used so these weren't in effect so just verify it's still ok

2024-04-02 01:10 UTC, JacquiFreeElectron commented on app/src/components/TSCSnackbar.css
> +.snackabr {
😂right

2024-04-02 02:28 UTC, paologum approved these changes
looks great :D

2024-04-02 03:21 UTC, merged