Tsc 126 column width
earthhistoryviz/tsconline pull request #69
Opened 2024-04-01 12:58 UTC by lbostre

- added column menu option to change width on chart generation

![WidthMenu](https://github.com/earthhistoryviz/tsconline/assets/29764221/b551c80f-49a9-4ef2-8458-d421a254b6f0)

DEMO
https://github.com/earthhistoryviz/tsconline/assets/29764221/98e7eb58-4689-4f06-9b72-db4a9f8f6636

2024-04-09 00:10 UTC, paologum requested changes
lowkey forgot to review this so sorry it was late

2024-04-09 00:10 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +      <div style={{ display: "flex", flexDirection: "row" }}>
can you move this to css

2024-04-09 00:10 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +      : state.settingsTabs.columnHashMap.get(state.settingsTabs.columnSelected)!.width;
i think this would make more sense from an abstractability standpoint to just pass the width in as a parameter of `EditWidthField`. You can do the check somewhere in the parent component which makes this more understandable/possibly usable elsewhere

2024-04-09 00:10 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  if (isNaN(newWidth)) return;
if `updateWidth` accepts only `newWidth: number` this isn't needed

2024-04-09 00:10 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +            }}>
i know numeric format should handle everything properly, but i would add the `isNaN` here to make sure and to also `pushError` if it isn't.

2024-04-10 20:59 UTC, paologum requested changes
update a new picture when you remove the confirm button

2024-04-10 20:59 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +        </div>
the more i think about this the more i think that we shouldn't have a confirm button and it should just update on change of `NumericFormat`

if the user never presses confirm all the columns will have weird numbers they might not expect and also more importantly the java file doesn't have a confirm

you shouldn't need the error anymore and if the user doesn't have any number or the field is empty, the width should set to 20 (the java file does this)

2024-04-10 20:59 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +
i feel like this makes too many assumptions about the structure, and if we every decide to change how we do `columnSelected` or what not it would require a lot of overhead changes that we would need to sort out.

so instead you should just pass in the object and update the width (2 params). it should also check if the column has the width object and console error if it doesn't have a width

2024-04-12 13:17 UTC, lbostre commented on app/src/SettingsTabs/ColumnMenu.tsx
> +          )}
For some reason, if I change the code to `state.settingsTabs.columnHashMap.get(state.settingsTabs.columnSelected) && ..`. rather than the ```
state.settingsTabs.columnSelected &&
          state.settingsTabs.columnHashMap.get(state.settingsTabs.columnSelected)!.width &&
```
the width value is not passed in properly.

2024-04-15 21:29 UTC, paologum requested changes

2024-04-15 21:29 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +});
this should just do `columnObject.width = newWidth`

2024-04-15 21:29 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +  }
if it doesn't exist just return null, `columnObject` should always exist if this edit component is rendered

2024-04-15 21:29 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +          }
is there a reason you specifically use undefined vs just using truthy values

2024-04-15 21:29 UTC, paologum commented on app/src/state/parse-settings.ts
> +        }
can you just use `stateColumn`? or does it need `presetColumn`?

our `ColumnInfo` state object is more correct so i feel like we don't need `presetColumn` unless i'm missing something

2024-04-15 21:29 UTC, paologum commented on app/src/util/error-codes.ts
> +  INVALID_WIDTH_TYPE = "INVALID_WIDTH_TYPE"
you don't use this anymore so you should remove

2024-04-15 21:29 UTC, paologum commented on app/src/util/error-codes.ts
> +  [ErrorCodes.INVALID_WIDTH_TYPE]: "Invalid width type. Width should be a number."
same

2024-04-15 21:29 UTC, paologum commented on app/src/SettingsTabs/EditWidthField.tsx
> +  }
also if there is no width, it should return null since it can be undefined, you can add that as a check here or when you render it in the `ColumnMenu`. I would pick one or the other for everything though, so either use all return nulls on conditions or use the truthy values in `ColumnMenu` for the column and width objects

2024-04-16 02:01 UTC, lbostre commented on app/src/state/parse-settings.ts
> +        }
The stateColumn sometimes has the width undefined, while the presetColumn always has a width. If I were to just use stateColumn, I'm not sure how to the undefined case because I don't think there's a universal default width.

2024-04-16 16:33 UTC, paologum commented on app/src/state/parse-settings.ts
> +        }
i think if you don't even set/add that line if it's undefined it should still work. I would try that and generate all charts to make sure it works though but I'm like 99% sure the width for metacolumns (non-existing width columns) should not matter

2024-04-17 08:13 UTC, paologum requested changes
is there a reason my commits are like on top of yours 😭  it's lowk hard to read the pr with mine and your changes mixed together so maybe after this, try rebasing on `origin/main` again and see if the commits normalize bc it's kinda confusing. i'm not sure why it would layer our changes together tho

2024-04-17 08:13 UTC, paologum commented on app/src/state/parse-settings.ts
> +        }
i'm confused wouldn't this just be 
```
if (stateColumn && stateColumn.width) {
xml += `${indent}<setting name="width">${stateColumn.width}</setting>\n`;
}
```
i'm not sure what editWidth is off the top of my head so lmk

2024-04-17 08:13 UTC, paologum commented on shared/src/index.ts
> +  width?: number;
is there a reason width and units are on `FontLabelOptions`?

2024-04-17 08:13 UTC, paologum commented on app/src/state/actions/column-actions.ts
> +  return;
no need for a return

2024-04-17 13:00 UTC, lbostre commented on app/src/state/parse-settings.ts
> +        }
I changed it to that, but I'm still running into chart generation issues...I'm pretty sure that the issues are unrelated to this tho because they weren't working before changing this too

2024-04-17 19:00 UTC, paologum commented on shared/src/index.ts
> +  width?: number;
oh what the heck ok i was tweaking, this is fine haha

2024-04-19 16:52 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${xmlKey}" orientation="${presetColumn[key as keyof ColumnInfoTSC]}"/>\n`;
more of a question, but is there a reason you added `customColor` with nothing and `orientation` as part of the pr? it probably works but `orientation` is already checked for on line 412 below and `customColor` i'm kinda confused about

2024-04-22 16:02 UTC, lbostre commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${xmlKey}" orientation="${presetColumn[key as keyof ColumnInfoTSC]}"/>\n`;
oh nah i can remove that I think thats probably from me messing up a rebase

2024-04-23 20:27 UTC, paologum requested changes

2024-04-23 20:27 UTC, paologum commented on app/src/state/parse-settings.ts
> +        }
one small thing, we don't want the `stateColumn` to still be `isNaN` if we are actually successfully generating a chart. we want it to be actually valid so if `isNaN` then set the `stateColumn.width`. i'm not sure the specifics on whether you can actually change it here, but if you can't change the `stateColumn.width` here the other solution is

in `changeManuallyAddedColumns` in `generate-chart-actions.ts`, add a check on the width that sets it if it is `NaN` or 0

also yeah you don't have a check for 0 here so add that too

2024-04-25 05:31 UTC, paologum approved these changes
looks good ! :D

2024-04-25 18:05 UTC, merged