Tsc 267 create login frontend
earthhistoryviz/tsconline pull request #85
Opened 2024-04-16 18:55 UTC by asivath

https://github.com/earthhistoryviz/tsconline/assets/94872897/a6a3017b-9a1b-4c22-82c4-21e37a77a96f

2024-04-16 20:24 UTC, paologum requested changes
can you sign in so i can see the ui for after signing in successfully. just like hard code it for the demo so i can see the navbar sign out stuff and also the signout flow.

2024-04-16 20:24 UTC, paologum commented on app/src/Login.tsx
> +        }
you should remove error if logged in correctly

2024-04-16 20:24 UTC, paologum commented on app/src/main.tsx
> +  <GoogleOAuthProvider clientId={import.meta.env.VITE_GOOGLE_CLIENT_ID}>
does local deving need this env variable?

2024-04-16 20:24 UTC, paologum commented on app/src/Login.tsx
> +      });
is this a route we have?

2024-04-16 20:24 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +    if (response.ok) {
same question here, i'm just wondering how this works mostly

2024-04-16 20:24 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +  }
should be a display error code right?

2024-04-16 20:24 UTC, paologum commented on app/src/NavBar.tsx
> +  actions.sessionCheck();
why do you need to run a session check here? can you explain what this session check will do so i can understand this better

2024-04-16 21:15 UTC, asivath commented on app/src/main.tsx
> +  <GoogleOAuthProvider clientId={import.meta.env.VITE_GOOGLE_CLIENT_ID}>
no it's not needed unless you want to use the google login

2024-04-16 21:16 UTC, asivath commented on app/src/Login.tsx
> +      });
they exist in the backend branch I just put them here since they're for the frontend

2024-04-16 21:27 UTC, asivath commented on app/src/NavBar.tsx
> +  actions.sessionCheck();
i forgot I put that there it was for debugging. its meant to check if a user has a valid session, so probably the two places it should be is after we get a ok response from the login endpoint and some element that will always get rendered so that we can check is a user is logged in after reopening the page, maybe App.tsx?

2024-04-16 21:39 UTC, asivath commented on app/src/state/actions/general-actions.ts
> +    if (response.ok) {
same in another branch just invalidates a session

2024-04-17 00:44 UTC, asivath commented
https://github.com/earthhistoryviz/tsconline/assets/94872897/e8564fbc-0a30-4d54-8c3c-b4428e29dd6c

2024-04-17 00:52 UTC, asivath commented on app/src/main.tsx
> +  <GoogleOAuthProvider clientId={import.meta.env.VITE_GOOGLE_CLIENT_ID}>
actually since this does not need to be private I could just hardcode it so anyone should be able to use it

2024-04-17 18:47 UTC, paologum commented on app/src/NavBar.tsx
> +  actions.sessionCheck();
i think it should get called on `initialize()` and on successful login based on what you said. although do you need to check the session on startup of the app? right now there is no state that saves information between refreshes so you would just be logged out if you refresh at the moment. unless the way you implemented it will keep information through refreshes (i haven't seen that code so i'm assuming)

also we shouldn't put the session check in a raw element imo

2024-04-17 18:56 UTC, paologum requested changes

2024-04-17 18:56 UTC, paologum commented on app/src/App.tsx
> +  actions.sessionCheck();
my previous response, i think this will session check when we don't really need to on every state change

2024-04-17 18:56 UTC, paologum commented on app/src/Login.tsx
> +  };
i forgot to mention, but for debugging purposes, you should use `displayServerError` and pass it the payload from the server and the error generated in the catch. Additionally on any error on the server in your backend code, it should return a json with `{ error: <message> }`

2024-04-17 18:56 UTC, paologum commented on app/src/Login.tsx
> +          login_uri={`${import.meta.env.VITE_SERVER_URL || "https://localhost:3000"}/auth/oauth`}
is this not `devSafeUrl`?

2024-04-17 18:56 UTC, paologum commented on app/src/NavBar.tsx
> +              navigate("/");
i don't know if logging out should navigate away from where they are, bc the difference is they shouldn't be on the login screen anymore

2024-04-17 18:56 UTC, paologum commented on app/src/SignUp.tsx
> +        }}>
css

2024-04-17 18:56 UTC, paologum commented on app/src/main.tsx
> +  <GoogleOAuthProvider clientId={import.meta.env.VITE_GOOGLE_CLIENT_ID}>
did you wanna hardcode this still?

2024-04-17 18:57 UTC, paologum commented
oh yeah also, i'm assuming that you don't have a demo of the google auth because that doesn't work until backend? but if it does work can you add a demo of that

2024-04-17 19:49 UTC, asivath commented on app/src/NavBar.tsx
> +  actions.sessionCheck();
yea I'll put it in initialize(). the session gets stored in a cookie so it will persist between refreshes

2024-04-17 20:09 UTC, asivath commented
yeah the google login will try to redirect and pass stuff to the backend and will just fail

2024-04-17 21:20 UTC, paologum requested changes

2024-04-17 21:20 UTC, paologum commented on app/src/Login.tsx
>      }
the error messages should just be the ErrorMessages[ErrorCodes.UNABLE_TO_LOGIN]

2024-04-17 21:20 UTC, paologum commented on app/src/state/initialize.ts
> +  actions.sessionCheck();
idk what will require us to ask for cookie permissions but i doubt this is one of those situations right

2024-04-17 21:36 UTC, asivath commented on app/src/state/initialize.ts
> +  actions.sessionCheck();
should that be a part of this pr

2024-04-17 21:38 UTC, paologum commented on app/src/state/initialize.ts
> +  actions.sessionCheck();
mmm no i think this does a lot already so you can just make that it's own thing. since we aren't technically publicly released or whatever, it should be alright.

i would say that is one of your next priorities though

2024-04-17 21:38 UTC, paologum approved these changes

2024-04-17 21:48 UTC, merged