Translate columnInfo to type TSC, parse type TSC to xml, changes for multiple datapacks now work
earthhistoryviz/tsconline pull request #86
Opened 2024-04-17 01:51 UTC by jay-jhk-lee

2024-04-17 07:56 UTC, paologum requested changes
some small tings n dat 🕺

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +  }
why did this change off of 
```
function generateSettingsXml(stateSettings: ChartSettings, indent: string): string {
  let xml = "";
  for (const unit in stateSettings.timeSettings) {
    const timeSettings = stateSettings.timeSettings[unit];
    xml += `${indent}<setting name="topAge" source="text" unit="${unit}">\n`;
    xml += `${indent}    <setting name="text">${timeSettings.topStageAge}</setting>\n`;
    xml += `${indent}</setting>\n`;
    xml += `${indent}<setting name="baseAge" source="text" unit="${unit}">\n`;
    xml += `${indent}    <setting name="text">${timeSettings.baseStageAge}</setting>\n`;
    xml += `${indent}</setting>\n`;
    xml += `${indent}<setting name="unitsPerMY" unit="${unit}">${timeSettings.unitsPerMY * 30}</setting>\n`;
    xml += `${indent}<setting name="skipEmptyColumns">${timeSettings.skipEmptyColumns}</setting>\n`;
  }
  xml += `${indent}<setting name="variableColors">UNESCO</setting>\n`;
  xml += `${indent}<setting name="negativeChk">false</setting>\n`;
  xml += `${indent}<setting name="doPopups">${stateSettings.mouseOverPopupsEnabled}</setting>\n`;
  xml += `${indent}<setting name="enEventColBG">${stateSettings.enableColumnBackground}</setting>\n`;
  xml += `${indent}<setting name="enChartLegend">${stateSettings.enableChartLegend}</setting>\n`;
  xml += `${indent}<setting name="enPriority">${stateSettings.enablePriority}</setting>\n`;
  xml += `${indent}<setting name="enHideBlockLabel">${stateSettings.enableHideBlockLabel}</setting>\n`;
  return xml;
```

i don't see a reason to change what we previously had to convert back into `ChartSettingsTSC` since how it currently is is completely fine and doesn't require any change. it's also a lot more readable if we take the state object and build the xml file that way. since we already have to pull from `ChartSettingsTSC` into the state, changing back into `ChartSettingsTSC` seems redundant

it would also reduce the code in not having a conversion function `translateSettings`

we could in the future cut off the middle man and have them be the same thing but at the very least i don't see the need to have `translateSettings`

2024-04-17 07:56 UTC, paologum commented on app/src/state/actions/generate-chart-actions.ts
> +    console.log(xmlSettings);
remove :D

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +    column._id = "class datastore.TransectColumn:" + replaceSpecialChars(state.name, 0);
i think with my pr this can be like three lines where you have `class datastore.${columnDisplayType}: + replace...`

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +  }
same here 😢  i probably shoulda told you i was working on it today. i have all these on the column now so you don't need any if's imo from my understanding

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +      column._id = "class datastore.RootColumn:Chart Title";
i set chart titles to rootcolumns as well so we don't have to worry about weird edge cases with different titles

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +              xml += `font-family: ${newStateColumn[key][fKey]};`;
i changed some of the fonts as well so that they're more readable and direct instead of super generalized. like directly accessing the property instead of iterating over the keys. that's the direction i want the parser to head towards imo because i think the generalized concept of what we have made so far/the people before us is soooo hard to integrate for new developers.

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +      xml += `${indent}<setting name="${key}">${column[key as keyof ColumnInfoTSC]}</setting>\n`;
same here, i think if we have less if statements and more direct coding, life would be a lot easier in knowing where everything goes. so for example instead of 
```
else if (key === "justification") {
      xml += `${indent}<setting justification="${column[key as keyof ColumnInfoTSC]}" name="justification"/>\n`;
    }
```
we have
```
xml += `${indent}<setting justification="${column.justification}" name="justification"/>\n`;
```

imo it feels a lot cleaner and understandable. lmk what you think

2024-04-17 07:56 UTC, paologum commented on app/src/state/parse-settings.ts
> +}
is this method necessary? isn't it just `ChartInfoTSCToXml`

2024-04-17 07:56 UTC, paologum commented on server/hs_err_pid13487.log
remove all hs_err.logs

2024-04-17 07:56 UTC, paologum commented on server/public/presets/001-TSC2020-TEST/settings_copy.tsc
this isn't needed right

2024-04-17 07:56 UTC, paologum commented on shared/src/constants.ts
>  };
default events are 150 width and off

2024-04-17 07:56 UTC, paologum commented on shared/src/constants.ts
>    isSelected: false,
i think columns are default on right?

2024-04-17 07:56 UTC, paologum commented on shared/src/settings-types.ts
>    "class datastore.RootColumn:Chart Root"?: ColumnInfoTSC;
root should always exist, at least for us because we manually will always append root right

2024-04-22 05:46 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  }
My initial idea was that there would be two parts to parsing: columnInfo + ChartSettings -> ChartInfoTSC then ChartInfoTSC->xml. I wanted to have a function that strictly takes in a ChartInfoTSC object and creates a xml file. Since ChartInfoTSC has ChartSettingsInfoTSC and not ChartSettings, I needed to translate it. I think I did that because the settings didn't have all the options when I began. Since it does now, I'll change the ChartInfoTSC type to have ChartSettings instead of ChartInfoTSC and use your function. I do like having a middle man from columnInfo to ColumnInfoTSC since there's a lot of stuff that isn't needed to generate the xml in columninfo.

2024-04-22 05:47 UTC, jay-jhk-lee commented on server/public/presets/001-TSC2020-TEST/settings_copy.tsc
yeah

2024-04-22 06:41 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +              xml += `font-family: ${newStateColumn[key][fKey]};`;
sounds good 👌

2024-04-22 06:42 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +}
I changed it in my new pr :D

2024-04-22 06:47 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +      xml += `${indent}<setting name="${key}">${column[key as keyof ColumnInfoTSC]}</setting>\n`;
the current problem with doing `column.justification` is since the ColumnInfoTSC type isn't guaranteed to have the justification property (only RulerColumn has it), typescript doesn't let me do that. So I did a workaround with `as keyof`. I do agree with you tho

2024-04-23 20:30 UTC, paologum commented on app/src/state/parse-settings.ts
> +  }
i think though over time in the long run, `ChartInfoTSC` will have to get phased out/merged into what `ColumnInfo` is  because there is technically no need for two type of the same data structure.

2024-04-23 20:40 UTC, paologum commented on app/src/state/parse-settings.ts
> +      xml += `${indent}<setting name="${key}">${column[key as keyof ColumnInfoTSC]}</setting>\n`;
ok i guess that's fine but can you cast the key when/near its definition so that you don't cast it three times

2024-04-23 22:23 UTC, paologum requested changes

2024-04-23 22:23 UTC, paologum commented on app/src/state/parse-settings.ts
> +export function translateColumn(state: ColumnInfo): ColumnInfoTSC {
also as i said in a previous reply, this is something we're gonna phase out at some point this summer because this is redundant

2024-04-23 22:23 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${key}">${column[key].text}</setting>\n`;
same thing twice

2024-04-23 22:23 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${key}" useNamed="${column[key].standardized}">${column[key].text}</setting>\n`;
tbh these cases will never occur. the only thing that will happen is it's not default, or we have an rgb value

`useNamed` and `standardized` will never happen (at the moment) so ultimately you can just have

xml += `${indent}<setting name="${key}">${column[key].text}</setting>\n`;

or you can hard code `useNamed` to false since that's how it is for every column. i don't see a need to included any of this code if we're not going to be using it (i don't even think we should have this tbh)

2024-04-24 22:00 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +      break;
I guess we could set it to editName for chart root since it doesn't change, but the edit name for the chart title can change so it should be set to `state.name`. Basically, editName is equivalent to title and name is equivalent to id. To keep it consistent, we should set it to name regardless.

2024-04-24 22:14 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${key}" useNamed="${column[key].standardized}">${column[key].text}</setting>\n`;
I do see that `useNamed` and `standardized` will never currently, but the the goal of this function was to translate any ColumnInfoTSC into xml. The ColumnInfoTSC type can have those values, so I think we should cover all the cases. The function also covers the case you've mentioned too.`useNamed` is not always false, I've looked at settings files that have both true and false. I think we should have this since it does exist in settings.tsc.

2024-04-24 22:21 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  column.title = replaceSpecialChars(state.editName, 1);
I agree, it's a bit ambiguous. I think instead of`convertToSpecialChars`, `escapeSpecialChars` is a bit better since that's what the process is called. lmk what you think

2024-04-24 22:34 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +export function translateColumn(state: ColumnInfo): ColumnInfoTSC {
If you are referring to it being redundant in the case of parsing from ColumnInfo to xml, I agree. But I think it's valuable to have something that connects ColumnInfo to ColumnInfoTSC (unless you want to phase out the TSC types, but I think we should keep them). That could be in the form of functions for parsing ColumnInfo to xml, but I think it's easier to understand if we have a function that translates it directly.

2024-04-25 00:39 UTC, paologum commented on app/src/state/parse-settings.ts
> +      break;
actually i just checked, what matters is that the name is different only. The id has nothing to do with display. so you can just do `column._id = `class datastore.${state.columnDisplayType}:` + state.name;`

2024-04-25 00:44 UTC, paologum commented on app/src/state/parse-settings.ts
> +  column.title = replaceSpecialChars(state.editName, 1);
i was doing some searching and the "special chars" we are replacing are specific to html so i agree escape would be good so lets call it `escapeHtmlChars`

and if you could, could you make the parameters `(text: string, type: "min" | "all" = "min")` instead of type 0 vs 1 for clarity as well?

2024-04-25 00:46 UTC, paologum commented on app/src/state/parse-settings.ts
> +export function translateColumn(state: ColumnInfo): ColumnInfoTSC {
for now it's fine we can worry/discuss it when the time comes. (technically though all of tsc would be available in a regular columninfo variable, with maybe some shortcuts for things we don't support)

2024-04-25 00:48 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${key}" useNamed="${column[key].standardized}">${column[key].text}</setting>\n`;
the problem with that is that it will introduce weird cases we might not now the source of. to keep the main from having potential bugs that we are not aware of, we should keep the most amount of code limited to what we know is the case. I know it's not always the case of `useNamed = false` but nothing on our app will use any sort of named or standardized colors meaning that if they change it, they might produce weird use cases since that field will be true or standardized. we will definitely revisit it when we want to work on supporting it but for being proactive and limiting our range of features as we have been doing, i think this is the best approach

2024-04-26 04:04 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${key}" useNamed="${column[key].standardized}">${column[key].text}</setting>\n`;
I see your point. Since we don't have anything on the app that changes those fields, it will never be filled. If/when we do add functionality to change those fields, it might introduce unexpected outputs. You want to be sure that it only uses the background color since that's what we have implemented. I'll comment the code out instead of removing it since that is the correct output if those fields are defined so we can use it later if applicable.

2024-04-26 04:06 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +      break;
For the columnDIsplayType other than root, meta, and blockseries, they don't have the "Column" suffix so I have to add it. For Chart title, some chart titles have the "Chart Title in" prefix which is manually added so I have to remove it.

2024-04-26 04:15 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  column.title = replaceSpecialChars(state.editName, 1);
What do you mean by `type: "min" | "all" = "min"`? I'll change it to `type: "att" | "text"` for now

2024-04-27 09:09 UTC, paologum commented on app/src/state/parse-settings.ts
> +      break;
the code above is just `RootColumn` where I'm saying the id "doesn't matter". I'm saying you don't need to remove the prefix because all that matters is this root column does not have the same id as another root column

2024-04-27 09:11 UTC, paologum commented on app/src/state/parse-settings.ts
> +  column.title = replaceSpecialChars(state.editName, 1);
sure that works, what i was saying is that you have two different ways of escaping, one with all the escaping and one with minimum amount of escaping

2024-04-27 09:12 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="${key}" useNamed="${column[key].standardized}">${column[key].text}</setting>\n`;
sure that works :D

2024-04-27 09:25 UTC, paologum requested changes

2024-04-27 09:25 UTC, paologum commented on app/src/state/actions/generate-chart-actions.ts
> +    const xmlSettings = jsonToXml(columnCopy, chartSettingsCopy);
just curious why does this need to be a copy?

2024-04-27 09:25 UTC, paologum commented on app/src/state/parse-settings.ts
>    }
can you make the type actually `attribute` instead of `att` so it's more clear

2024-04-27 09:25 UTC, paologum commented on app/src/state/parse-settings.ts
>        }
technically for all xmls i've seen (and how rohan implemented on main), `backgorundColor` and `customColor` works like 

```
 else if (key === "backgroundColor") {
        if (stateColumn.rgb.r == 255 && stateColumn.rgb.g == 255 && stateColumn.rgb.b == 255) {
          xml += `${indent}<setting name="${xmlKey}"/>\n`;
        } else {
          xml += `${indent}<setting name="${xmlKey}" useNamed="false">rgb(${stateColumn.rgb.r},${stateColumn.rgb.g},${stateColumn.rgb.b})</setting>\n`;
        }
      } else if (key == "customColor") {
        xml += `${indent}<setting name="${xmlKey}" useNamed="false">rgb(${stateColumn.rgb.r},${stateColumn.rgb.g},${stateColumn.rgb.b})</setting>\n`;
      } 
```

2024-04-27 09:25 UTC, paologum commented on app/src/state/parse-settings.ts
> +    } else {
don't these asserts mean you can now access `column.orientation` and `column.justification` now

2024-04-27 09:25 UTC, paologum commented on shared/src/settings-types.ts
>  export function assertSequenceColumnInfoTSC(o: any): asserts o is SequenceColumnInfoTSC {
technically for this and all other values of `ColumnTSC` types that extend `ColumnBasicInfoTSC`, they should also call `assertColumnBasicInfoTSC`

2024-04-27 19:45 UTC, jay-jhk-lee commented on app/src/state/actions/generate-chart-actions.ts
> +    const xmlSettings = jsonToXml(columnCopy, chartSettingsCopy);
I don't think it has to be a copy, but since the column was made into a copy, I made a chart settings copy too. They're both states, so I wanted to keep it consistent.

2024-04-27 19:45 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +    } else {
yeah

2024-04-27 20:02 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
>        }
the rgb text was taken care of the translate function before, but I'll standardize it to the rgb type for the text and do the same thing here

2024-04-27 20:07 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +      break;
I understand, but the chart title is also classified as the root column, and I directly use the id for the xml parsing. We do need to remove the `Chart Title in` prefix because If a settings file has "RootColumn:Chart title in ka(1000)" id instead of "RootColumn:ka (1000)" for example then the file doesn't recognize the id and overwrites it with the defaults.

2024-04-27 20:21 UTC, paologum commented on app/src/state/parse-settings.ts
> +      break;
what i'm saying is that i checked and it does not need to "recognize" the id. the id means nothing, it just differentiates the different column hierarchies. it works as it should regardless of the type of id in this specific case. the id must be different that is all. besides, the case you are aritculating would only occur if we read back in the columnInfo settingsXml we generated (which we have never done thus far) and in that case the column variable would have to be the same, meaning that it would need to have `Chart title in` for it to recognize the correct column in our website

2024-04-27 20:30 UTC, paologum commented on app/src/state/parse-settings.ts
> +      break;
ah wait i see, ok but you should still use just the
```
column._id = `class datastore.${state.columnDisplayType}:` + state.name;
```
and change it in `manuallyAddedColumns` in `generate-chart-actions` (i think it's in that file) and make the name correct there instead of here where you check if the name is like that because that's technically like a normalizing function

2024-04-27 20:33 UTC, paologum commented on app/src/state/actions/generate-chart-actions.ts
> +    const xmlSettings = jsonToXml(columnCopy, chartSettingsCopy);
sure i guess, the only reason that column was made a copy is that i change the manually added columns to their original names that would technically be duplicates in the hash map, so they have to be copied, then changed

2024-04-27 20:35 UTC, paologum commented on app/src/state/parse-settings.ts
>        }
you can make it either way through checking if it's white through the string or through an rgb value, either way is fine, but the main thing is i think `backgroundColor` and `customColor` checks should be seperate, and `backgroundColor` should be empty when white to keep in line with the settings xml

2024-05-03 15:49 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +      xml += `${indent}<setting name="orientation" orientation="${column[key]}"/>\n`;
yeah I'll change it

2024-05-03 18:30 UTC, paologum requested changes

2024-05-03 18:30 UTC, paologum commented on app/src/state/parse-settings.ts
> +  if (state.width) column.width = state.width;
you should make the `ColumnTSC` type have width be optional, because leyton and i made the `columninfo` variable have optional width so it wouldn't be put in the xml as a tag. right now the width is going to be the default if it's a parent which could be mislead, so i think it should be optional and not be put in the xml if it's not there

2024-05-03 20:44 UTC, jay-jhk-lee commented on app/src/state/parse-settings.ts
> +  if (state.width) column.width = state.width;
Since ColumnTSC is supposed to be a direct representation of the settings file, I think making the width property optional on it is not a good idea since every column in a settings file has it even though the column itself might not use it (like the parent columns). I'll set the default to -1 which will clearly indicate that the width hasn't been set for this. The generated settings file from the java program will autofill the width either way. Lmk what you think

2024-05-04 05:43 UTC, paologum requested changes

2024-05-04 05:43 UTC, paologum commented on app/src/state/parse-settings.ts
> +        xml += `${indent}<setting name="width"></setting>\n`;
i think it'd be better to just not have the tag, i've verified it works without the tag, so only add the tag if the width exists

2024-05-04 05:43 UTC, paologum commented on app/src/state/parse-settings.ts
> +  column.width = column.width ? column.width : undefined;
this can be just `column.width = column.width` right?

2024-05-04 21:16 UTC, paologum approved these changes

2024-05-04 21:37 UTC, merged