description objects
earthhistoryviz/tsconline pull request #89
Opened 2024-04-19 19:10 UTC by rupp3

Changed DatapackParsingPack and activeDatapack. Still getting a type error in routes.ts when the loadIndexes function is called, not exactly sure what to put in replacement of [filename]. Previously had all of the components of DatapackParsingPack being set to an empty string or array and file set to filename but after rebase and yarn build it gave more errors so I currently have it blank.

2024-04-25 05:54 UTC, rupp3 commented
Changed the parse-datapacks test file and the json file that holds the keys to include file, description, title, and size. I made each parameter in the json file to be equal to empty strings but I don't think that's correct? I tried replacing the empty strings with what is in activeDatapacks for the Africa Bight datapack in both the test file and the json file but either way failed. Have screenshots: 
![Screenshot 2024-04-25 004136](https://github.com/earthhistoryviz/tsconline/assets/54484966/e4e243cc-2e7d-4d34-a34e-a8fd43074a7a)
![Screenshot 2024-04-25 004350](https://github.com/earthhistoryviz/tsconline/assets/54484966/f1cc1967-31c7-4088-8760-36585ce9ca71)
![Screenshot 2024-04-25 003918](https://github.com/earthhistoryviz/tsconline/assets/54484966/7e4b8ea3-e5ec-4414-a0e2-bcfe61fddc9e)

2024-04-25 22:44 UTC, paologum requested changes

2024-04-25 22:44 UTC, paologum commented on app/vite.config.ts.timestamp-1712938232587-38897d5850a4f.mjs
what is this file?

2024-04-25 22:44 UTC, paologum commented on server/src/index.ts
> +  const datapackPaths = datapacks.map((datapack) => '"' + assetconfigs.datapacksDirectory + "/" + datapack.file + '"');
i think you can just do this in one statement, you don't need to create `datapacks`, you can just make the datapack array in one.

2024-04-25 22:44 UTC, paologum commented on server/src/load-packs.ts
> +    await parseDatapacks(datapack.file, datapack.title, datapack.description, datapack.size, decryptionDirectory)
instead of adding each individual field, it would be better in the long run to just make the parameter the datapack object

2024-04-25 22:44 UTC, paologum commented on server/src/load-packs.ts
> -  console.log(`\nParsing datapacks: ${datapacks}\n`);
you should keep this

2024-04-25 22:44 UTC, paologum commented on server/src/routes.ts
>    if (!datapackIndex[filename]) {
why is this removed

2024-04-25 22:44 UTC, paologum commented on server/src/load-packs.ts
> +  datapacks: DatapackParsingPack[]
this shouldn't be `DatapackParsingPack` because the objective of this function is to create `DatapackParsingPack`'s so instead you should take the datapack description items of the object and put it into it's own object that can be fed into this method

2024-04-25 22:44 UTC, paologum commented on server/src/routes.ts
> +  };
that way with the above comment, you don't make this slightly confusing object that has a `columnInfo` object that doesn't make sense

2024-04-25 22:44 UTC, paologum commented on server/src/types.ts
> +  activeDatapacks: DatapackParsingPack[];
this would change to whatever that object is called

2024-04-25 22:44 UTC, paologum commented on shared/src/index.ts
> +  size: string;
these would be that object

2024-04-26 02:41 UTC, rupp3 commented on app/vite.config.ts.timestamp-1712938232587-38897d5850a4f.mjs
honestly no clue, did not know it was there

2024-04-26 02:48 UTC, rupp3 commented on server/src/routes.ts
>    if (!datapackIndex[filename]) {
i changed filename to filePack bc of having loadIndexes accepting a DatapackParsingPack as the last arg

2024-05-02 18:53 UTC, paologum requested changes

2024-05-02 18:53 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +                      <Tooltip title={"state.datapackInfo[index].description"} arrow placement="right">
i don't this displays the description if it's in quotes right

2024-05-02 18:53 UTC, paologum commented on server/__tests__/parse-datapacks.test.ts
> +const datapack: DatapackDescriptionInfo = { description: "", title: "", file: "", size: "" };
this should be in the describe block below instead of the top of the test

2024-05-02 18:53 UTC, paologum commented on server/src/routes.ts
> -  if (!datapackIndex[filename]) {
is there a reason you removed the `fs.existsSync(mapPackIndexFilepath)` check

2024-05-02 18:53 UTC, paologum commented on app/src/SettingsTabs/Datapack.tsx
> +                      <Tooltip title={"state.datapackInfo[index].description"} arrow placement="right">
oh wait i get why, but technically this pr should have this fixed in the end for sure

2024-05-02 18:53 UTC, paologum commented on shared/src/index.ts
> +  size: string;
so technically, you need the `DatapackDescriptionInfo` object for the information we keep in the json file, so that is good. But we also need to have it represented in `DatapackParsingPack`. Which means you should have this object inside `DatapackParsingPack` so we can access it on the app side.

2024-05-02 18:53 UTC, paologum commented on server/src/load-packs.ts
> +  );
i think you should just leave this as `string[]` and instead when you call `await grabMapImages` you do the map to filepath stuff there

2024-05-02 18:53 UTC, paologum commented on server/src/parse-datapacks.ts
> +  const decryptPaths = await grabFilepaths([datapackInfo.file], decryptFilePath, "datapacks");
here you pass in `datapackInfo` but you don't do anything with it in this method

2024-05-02 18:53 UTC, paologum commented on server/src/types.ts
> +    }
wouldn't you just call your method `assertDatapackDescriptionInfo` here

2024-05-04 22:24 UTC, rupp3 commented on server/src/routes.ts
> -  if (!datapackIndex[filename]) {
i'm thinking that when i rebase it removes things because i didn't remove that myself/on purpose

2024-05-06 08:30 UTC, paologum commented on server/src/routes.ts
> -  if (!datapackIndex[filename]) {
okok well if you rebase it'll have a conflict with this that you should change to the main version

2024-05-06 19:56 UTC, rupp3 commented on server/src/parse-datapacks.ts
> +  const decryptPaths = await grabFilepaths([datapackInfo.file], decryptFilePath, "datapacks");
datapackInfo is passed in to access the files to be called in grabFilepaths(). I just replaced files with datapackInfo.file

2024-05-07 00:07 UTC, paologum commented on server/src/parse-datapacks.ts
> +  const decryptPaths = await grabFilepaths([datapackInfo.file], decryptFilePath, "datapacks");
you can probably just keep it to `files: string` and just pass the property itself instead of the whole object for better readability

2024-05-09 18:33 UTC, paologum reviewed
thought i'd add some more comments

2024-05-09 18:33 UTC, paologum commented on server/src/routes.ts
> +    if (assetconfigs.activeDatapacks.map((datapack) => datapack.file).includes(datapack)) {
this is gonna execute map multiple times for every datapack, you should just map once

2024-05-09 18:33 UTC, paologum commented on server/__tests__/parse-datapacks.test.ts
> +    const datapacks = await parseDatapacks(datapack, "parse-datapacks-test-2.txt");
these should change back

2024-05-09 18:33 UTC, paologum commented on server/src/parse-datapacks.ts
> +  return { columnInfo: chartColumn, datapackAgeInfo, ageUnits, file, description };
if you're going to add all the description stuff here, you should pass the `DatapackDescription` object in and add each param here, just make sure that `DatapackParsingPack` has all the corresponding items

2024-05-10 07:55 UTC, rupp3 commented on server/src/parse-datapacks.ts
> +  return { columnInfo: chartColumn, datapackAgeInfo, ageUnits, file, description };
should i even be putting the description stuff in parseDatapacks? it feels like it does not need to be there but i am not sure where to put it. same goes for the app side, i still cant access the description to display on the frontend

2024-05-11 20:22 UTC, paologum commented on server/src/parse-datapacks.ts
> +  const decryptPaths = await grabFilepaths([files], decryptFilePath, "datapacks");
you can't append the required fields if you just send in the `files` here. i said something a long time ago about setting this to files so that's my fault but this should be your object so you can add the necessary parts to `DatapackParsingPack`

2024-05-11 20:24 UTC, paologum commented on server/assets/config.json
this is missing vertebrates and human culture

2024-05-11 20:25 UTC, paologum commented on shared/src/index.ts
> +  size: string;
technically you aren't using `DatapackDescriptionInfo` on `app`, so this should be in `types.ts`

2024-05-11 20:25 UTC, paologum commented on shared/src/index.ts
>  export function assertDatapackIndex(o: any): asserts o is DatapackIndex {
same

2024-05-14 17:46 UTC, paologum requested changes
this is looking really good! try to rebase for your next push

2024-05-14 17:46 UTC, paologum commented on server/assets/config.json
still missing vertebrates and human culture

2024-05-14 17:46 UTC, paologum commented on server/src/load-packs.ts
> +      { file: datapack.file, description: datapack.description, title: datapack.title, size: datapack.size },
i think you can just pass in `datapack`

2024-05-14 17:46 UTC, paologum commented on server/src/parse-datapacks.ts
> +  const size: string = datapackInfo.size;
you don't need to create temp variables for these, you can just go straight to the return

2024-05-14 17:46 UTC, paologum commented on server/src/routes.ts
>    async function errorHandler(message: string, errorStatus: number, e?: unknown) {
since you created the new fields, the app has some of these forms already built on the front end so can you send those and input them here

2024-05-14 17:46 UTC, paologum commented on server/src/routes.ts
> +    if (datapackFiles.includes(datapack)) {
for ease of readability can you name it `serverDatapacks`

2024-05-15 19:47 UTC, rupp3 commented on server/src/routes.ts
>    async function errorHandler(message: string, errorStatus: number, e?: unknown) {
not 100% sure what I need to send. I've been using DatapackIndex to access each field but it has not been working here. where on the front end are they getting built?

2024-05-17 06:21 UTC, paologum commented on server/__tests__/parse-datapacks.test.ts
> +  const datapack: DatapackDescriptionInfo = { description: "", title: "", file: "", size: "" };
you should make the strings for the test variables not empty and make them different just from a good test standpoint

2024-05-17 06:22 UTC, paologum commented on server/src/routes.ts
> +  //const serverdatapackInfo: DatapackIndex = {};
take out?

2024-05-17 06:23 UTC, paologum commented on server/src/parse-datapacks.ts
> +  }
i don't think you need this because you  pass in the value as the type `DatapackDescriptionInfo` already

2024-05-17 06:24 UTC, paologum commented on server/src/routes.ts
>    async function errorHandler(message: string, errorStatus: number, e?: unknown) {
well this function is concerned with the upload of  a datapack meaning it doesn't exist on the `DatapackIndex` until this successfully completes. Therefore meaning it should have the proper fields set in the `DatapackParsingPack` to complete successfully.

2024-06-07 06:28 UTC, paologum requested changes

2024-06-07 06:28 UTC, paologum commented on package.json
> +    "@types/lodash": "^4.17.1",
did you add this type? if not i would run `yarn remove @types/lodash` in the root directory

2024-06-07 06:28 UTC, paologum commented on server/__tests__/parse-datapacks.test.ts
>    });
i would put `datapack1` in the `it` test and call it a better name like `africaGeneralDescriptionInfo` or alternatively don't use any variable and pass it in raw

2024-06-07 06:28 UTC, paologum commented on server/__tests__/parse-datapacks.test.ts
> +  const datapack: DatapackDescriptionInfo = { description: "", title: "", file: "", size: "" };
you should just name the strings like `"description"`, etc just for 100% verification

2024-06-07 06:28 UTC, paologum commented on server/src/database.ts
> +/*
no comment

2024-06-07 06:28 UTC, paologum commented on server/src/database.ts
> +//import { exec } from "child_process";
no comment

2024-06-07 06:28 UTC, paologum commented on server/src/database.ts
> +});*/
no comment

2024-06-07 06:28 UTC, paologum commented on server/src/load-packs.ts
> +        };
`datapackParsingPack` should already have those fields properly set

2024-06-07 06:28 UTC, paologum commented on server/src/load-packs.ts
> +  datapacks: string[] = assetconfigs.activeDatapacks.map((datapack) => datapack.file),
should remove the comment since it doesn't apply

2024-06-07 06:28 UTC, paologum commented on server/src/parse-datapacks.ts
> +    size: datapackInfo.size,
if you wanted you could also do `...datapackInfo` i think but this is arbitrary so you don't have to change it, just thought i'd comment

2024-06-07 06:28 UTC, paologum commented on server/src/routes.ts
> +  };
this pr should also send/receive the user's inputed title and description from the frontend

2024-06-07 06:28 UTC, paologum commented on server/src/types.ts
>    if (typeof o.timescaleFilepath !== "string") throw 'AssetConfig must have a "timescaleFilepath" string';
don't you need this check to make sure there are `activeDatapacks`?

2024-06-07 15:37 UTC, rupp3 commented on package.json
> +    "@types/lodash": "^4.17.1",
was previously getting errors for not finding lodash but works fine without now

2024-06-14 15:32 UTC, paologum commented
can you upload a demo of you uploading and working with the datapack page after a file is uploaded

2024-07-01 21:06 UTC, paologum requested changes

2024-07-01 21:06 UTC, paologum commented on server/src/routes.ts
> +      await pump(uploadedFile.file, tempFileStream); //need to ensure the file is written
i'm not sure why we need to write it in a temp directory?
why don't you just set `uploadedFile` to the part and then let the code written before handle `uploadedFile` (the way it was `await pump` ing before instead of the overhead of temporary directories

2024-07-01 21:06 UTC, paologum commented on server/src/routes.ts
> +    console.log("No name or description uploaded");
no logs

2024-07-01 21:06 UTC, paologum commented on server/src/routes.ts
> +  if (uploadedFile.file.truncated) {
i would check size after we see if it's too large, also remove all logs and errors, and just return the correct response with the correct error codes (probably should look up the error codes)

2024-07-01 21:06 UTC, paologum commented on server/src/routes.ts
> +    console.log("Wrote map pack index to file");
remove logs

2024-07-01 21:06 UTC, paologum commented on server/src/routes.ts
> +  console.log("File uploaded to server");
remove logs

2024-07-01 21:06 UTC, paologum commented on server/src/types.ts
> +      throw "AssetConfig activeDatapacks description, title, file, or size item " + index + " must be a valid string";
i would make each of these their own `if` statement

2024-07-01 21:06 UTC, paologum commented
i would also upload a demo here

2024-07-01 21:33 UTC, rupp3 commented on server/src/database.ts
> +  });*/
NOTE: uncommenting at very end bc this makes my server not run

2024-07-01 21:37 UTC, rupp3 commented on server/src/load-packs.ts
> +    console.log(`\nParsing datapack file: ${datapack.file}\n`);
output of line 37 is 
Parsing datapacks: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] so i am going to remove the datapacks variable as well, just keeping the string

2024-07-01 22:01 UTC, rupp3 commented on server/src/routes.ts
> +      await pump(uploadedFile.file, tempFileStream); //need to ensure the file is written
when i had it just line 280 and the original pump, the server would hang in the if block. apparently need to write the file somewhere first in order to use it so i made a temp and then had it rewritten to the correct filepath

2024-07-01 22:14 UTC, rupp3 commented on server/src/routes.ts
> +  if (uploadedFile.file.truncated) {
i can just delete it. only used it to check if the file existed when i was trying the pump stuff. or i can make an error for an empty file being uploaded if that's relevant?

2024-07-02 00:28 UTC, rupp3 commented
Demo video
https://github.com/earthhistoryviz/tsconline/assets/54484966/b97e7389-4f44-44ad-ab1d-9989263ec019

2024-07-02 05:11 UTC, paologum commented
from the demo, you can see that the description being smaller than one line makes the description resize. you should make that container take up the whole parent container. (not the whole page but just the container it is in)

2024-07-02 05:18 UTC, paologum requested changes

2024-07-02 05:18 UTC, paologum commented on app/src/components/datapack_display/TSCDatapackCard.tsx
> +  }
this case should never happen because the prop is always defined

2024-07-02 05:18 UTC, paologum commented on app/src/components/datapack_display/TSCDatapackRow.tsx
> +  }
same here

2024-07-02 05:18 UTC, paologum commented on server/src/routes.ts
> +  const uuid = "username"; //request.session.get("uuid");
not supposed to be username

2024-07-02 05:18 UTC, paologum commented on server/src/routes.ts
> +//import { stringify } from "querystring";
comments?

2024-07-02 05:18 UTC, paologum commented on server/src/database.ts
> +  });*/
i wouldn't commit these comments, i would change them back and just keep these changes local and not commit them so that we don't accidentally merge undesired changes

2024-07-02 05:18 UTC, paologum commented on server/src/routes.ts
> +  const uuid = "username"; //request.session.get("uuid");
same

2024-07-02 05:18 UTC, paologum commented on server/src/routes.ts
> +  const uuid = "username"; //request.session.get("uuid");
same

2024-07-02 05:18 UTC, paologum commented on server/src/routes.ts
> +      await pump(uploadedFile.file, tempFileStream); //need to ensure the file is written
then instead of making a temp file, just do the actual file saving stuff here

2024-07-02 05:18 UTC, paologum commented on server/src/routes.ts
> +  if (uploadedFile.file.truncated) {
don't you need to set the `size`?

2024-07-02 05:19 UTC, paologum commented on server/src/routes.ts
> +    size: uploadedFile.file.bytesRead.toString()
does this put it in the format of 30mb or like 2kb?
if not, it should because this should be a user readable field

2024-07-02 18:08 UTC, rupp3 commented on server/src/routes.ts
> +    size: uploadedFile.file.bytesRead.toString()
output is just a number like "size in datapackInfo: 16965905"

2024-07-02 18:51 UTC, paologum commented on server/src/routes.ts
> +    size: uploadedFile.file.bytesRead.toString()
ok yeah you should convert it properly to a file format string, because that doesen't help the user

2024-07-02 19:30 UTC, paologum commented on server/src/routes.ts
> +      await pump(uploadedFile.file, tempFileStream); //need to ensure the file is written
i was using postman to test a different upload route i'm making and found that

```
 for await (const part of parts) {
    if (part.type === "file") {
      file = part;
    } else if (part.fieldname === "title" && typeof part.value === "string") {
      title = part.value;
    } else if (part.fieldname === "description" && typeof part.value === "string") {
      description = part.value;
    }
  }
```
doesn't hang for me

2024-07-03 16:35 UTC, rupp3 commented on server/src/routes.ts
> +      await pump(uploadedFile.file, tempFileStream); //need to ensure the file is written
it still hangs in the file if block

2024-07-03 17:06 UTC, paologum requested changes

2024-07-03 17:06 UTC, paologum commented on server/src/routes.ts
>      return;
on all these errors, you need to clean up the file

2024-07-03 17:06 UTC, paologum commented on server/src/routes.ts
> +  await mkdirp(datapackDir);
try catch, also just use `mkdir`

2024-07-03 17:06 UTC, paologum commented on server/src/routes.ts
> +      await pump(uploadedFile.file, fileStream);
try catch, and cleanup

2024-07-03 17:06 UTC, paologum commented on server/src/routes.ts
> +  }
if bytes is 0, it should not be a valid file so throw an error

2024-07-03 17:06 UTC, paologum commented on server/src/routes.ts
> +  const uuid = "username"; //request.session.get("uuid");
just a heads up but i won't approve until all the minor fixes for local deving are committed and pushed

2024-07-03 17:06 UTC, paologum commented on server/src/routes.ts
> +      await pump(uploadedFile.file, fileStream);
also, the `uploadedFile = part` i was talking about earlier only ever works for unencrypted files for some reason, i haven't looked into it more but this is fine now

2024-07-05 05:35 UTC, paologum requested changes

2024-07-05 05:35 UTC, paologum commented on app/src/components/datapack_display/TSCDatapackRow.tsx
> +          {datapack.description}
this is for the author and creation date, so it shouldn't be the description, you can leave this for now

2024-07-05 05:35 UTC, paologum commented on server/src/routes.ts
> +    await mkdir(datapackDir);
you should make it recursively just to be sure

2024-07-05 05:35 UTC, paologum commented on server/src/routes.ts
> +        fields[part.fieldname] = field.value;
to be robust you should check the type of `fieldname` and `value` in the if as well

2024-07-05 05:35 UTC, paologum commented on server/src/routes.ts
> +    await errorHandler("Name or description not provided", 404);
should bee 400

2024-07-05 05:35 UTC, paologum commented on server/src/routes.ts
> +        }
return if error

2024-07-05 05:35 UTC, paologum commented on server/src/routes.ts
> +      } else if (part.type === "field") {
check truncation here and not on line 371

2024-07-05 05:35 UTC, paologum commented on server/src/routes.ts
>    }
for above

2024-07-05 05:56 UTC, paologum commented on server/src/routes.ts
> +    await errorHandler("Name or description not provided", 404);
this should be 400

2024-07-05 17:05 UTC, rupp3 commented
I showed a demo of my branch in the meeting after you left. Prof Ogg and Aaron suggested having a way to differentiate between the server datapacks and user uploaded datapacks on the front end. Also said to remove the Upload Datapack button if a user is not logged in. I can do that in this branch but I would highkey love to merge this PR first and do those fixes on a different branch

2024-07-06 07:32 UTC, paologum approved these changes
looks great! i'll add those in a seperate task so don't worry about that for this pr. you can continue working on the public datapack stuff as well as a priority too and we'll figure out when to do the other items

2024-07-13 02:27 UTC, merged