Tsc 281 create login backend
earthhistoryviz/tsconline pull request #91
Opened 2024-04-25 19:40 UTC by asivath

User/pass auth flow:
https://www.dropbox.com/scl/fi/u0fl3p4n15d7mba7crvxj/userpassflow.mp4rlkey=sfvq26buyakyuyxk5me7cn1ww&st=ohs6vefw&dl=0
Google auth flow:
https://www.dropbox.com/scl/fi/wz6qs2imgyjk2tpm86p27/googleflow.mp4?rlkey=2ned9eajlr6nvjtf1xljmomle&st=t1a0p3yq&dl=0
Videos were too big to attach here

Google login should work for anyone, but anything that requires emails won't work since it needs a username and password for the gmail account, which includes the user/pass flow. I also updated a couple of the routes to use the session instead of username.

2024-04-25 22:48 UTC, paologum commented
for your videos, wouldn't it make more sense to instead have on a login, it checks a field in the database whether or not the user is verified, then send to verification screen instead of the hyper link on the login page? that way the only way they can send the email is if they aren't verified?

2024-04-25 23:10 UTC, asivath commented
it already does that. i think there should be somewhere you can just directly send an email as well.

2024-04-26 02:17 UTC, paologum requested changes
might've missed a few things, will relook at it after you go over this review. in the future we definitely should break this task up into smaller bits because reading this fries my brain haha

2024-04-26 02:17 UTC, paologum commented on server/src/routes.ts
> +    const { uuid, hashedPassword, emailVerified } = row as UserRow;
assert?

2024-04-26 02:17 UTC, paologum commented on server/src/routes.ts
> +  const { useCache, useSuggestedAge } = chartrequest;
change the `ChartRequest` type in `shared`

2024-04-26 02:17 UTC, paologum commented on server/src/routes.ts
> +const sendEmail = async (email: Email) => {
can you put all of these login items in it's own file called `login-routes` and export it into `index.ts`

2024-04-26 03:52 UTC, asivath commented on app/src/state/actions/general-actions.ts
> +      }
rn 401 means not logged in and 404 means the user has no datapacks. I can remove the check for 401 since it is only called when a user is logged in. if I don't filter 404 it will keep popping up when someone is logged in but has no uploaded datapacks. what should I do about that?

2024-04-26 03:52 UTC, asivath commented on app/src/state/actions/general-actions.ts
> +      credentials: "include"
it sends cookies to the server which has the session details

2024-04-26 04:04 UTC, asivath commented on server/package.json
> +    "better-sqlite3": "^9.4.4",
it's simpler to use, faster, and abstracts away things we don't need like memory management

2024-04-26 04:12 UTC, asivath commented on server/src/routes.ts
>      }
best practice in Node is to use asynchronous operations (especially for I/O) to avoid blocking the event loop. later on when there's more people using it and more routes needing to be served those operations can add up. might as well future proof it

2024-04-26 04:15 UTC, asivath commented on server/src/routes.ts
> +  request: FastifyRequest<{ Body: { token: string; password: string } }>,
it gives me errors when I remove it

2024-04-27 09:30 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      }
i think that it shouldn't throw an error if the user has no datapacks. if for some reason the user had datapacks then they don't have datapacks this needs to correctly update the datapack index. this would mean refetching the corresponding datapacks on the server ONLY (which would be returned from the route) and therefore fully reseting the datapack index by setting it to the return value of the route. hopefully that makes sense but we still want to set the index on no datapacks found.

2024-04-27 09:36 UTC, paologum commented
i responded to your comments but i'll look at your next pr changes once you respond/implement the following which we discussed in the meeting with aaron
- on user login that is NOT verified, the user is able to login BUT they are trapped on the email verification sending screen. only action they can take is to sign out. (therefore removing the hyperlink for the verification link)
- can you also make another quick video with the new ui changes

2024-04-27 09:41 UTC, paologum commented on app/src/state/actions/general-actions.ts
> +      }
no error showing for 401 is fine, i wasn't sure what the error was

2024-05-02 19:39 UTC, asivath commented
https://www.dropbox.com/scl/fi/2i4padlejrbi8jlgrpocz/updates-to-login-ui.mp4?rlkey=f40h8wcst1bn53ed5axwsruzk&st=8rzd43oc&dl=0

Used kysely instead of knex js for better typescript support

2024-05-02 23:36 UTC, paologum requested changes

2024-05-03 01:24 UTC, asivath commented on app/src/AccountRecovery.tsx
> +        actions.pushSnackbar("If your account is verified, you will have received an email.", "success");
so I added a case for 400 which is invalid form, but any other error that the route could return should just show unable to send email. instead of navigating should I show the email form again so they can retry?

2024-05-03 01:25 UTC, asivath commented on app/src/AccountRecovery.tsx
> +          );
this shouldn't happen, but if for some reason the client's browser does not properly set up a session this could occur. though if that happened they wouldn't be able to log in at all

2024-05-03 01:28 UTC, asivath commented on app/src/AccountVerify.tsx
> +  }, [token]);
since we use strict mode it causes effects and mounts to happen twice, which makes this api call happen twice. useState doesn't keep this state across the remounts so I used useRef since it won't change. if there is a better way to deal with this lmk

2024-05-03 01:35 UTC, asivath commented on app/src/AccountVerify.tsx
> +          setMessage("Your account has been verified. Thank you! Redirecting...");
> in the video the spacing looks weird for the thank you! Redirecting... part is there a simple way for you to make a new line after Thank you!

do you mean how Thank you! is not on the same line but split up? or do you mean Redirecting... should be on a new line?

2024-05-03 01:44 UTC, asivath commented on app/src/AccountVerify.tsx
> +          setMessage("Your account has been verified. Thank you! Redirecting...");
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/afe5dd96-2c89-4fca-8b6f-d08a2ca01d99)
are these the margins you want?

2024-05-03 01:50 UTC, asivath commented on server/src/database.ts
> +}
yes this won't happen though since things like username, email, are unique and the routes make sure they can't be the same. uuids should always be unique and userid is incremented by the db. i'll also add unique constraints to the table so we can be sure they are always unique.

2024-05-03 01:51 UTC, asivath commented on server/src/database.ts
> +
above

2024-05-03 01:52 UTC, asivath commented on server/src/login-routes.ts
> +    const { userId, expiresAt, verifyOrReset } = verificationRow;
yes kysely handles this

2024-05-03 01:56 UTC, asivath commented on server/src/login-routes.ts
> +    }
the compiler warns that findUser could potentially be undefined (not actually possible since there has to be a userId associated with the token) so I added this check

2024-05-03 02:04 UTC, asivath commented on server/src/login-routes.ts
> +    }
its about security and leaking as little information as possible. i don't want to provide a route that could be used to check whether a user associated with that email exists. its why in the frontend message I say something like "If your email is associated with an account and is verified we have sent an email". this prevents people from faking emails from us to users that have an account with us.

2024-05-03 02:05 UTC, asivath commented on server/src/login-routes.ts
> +    }
same logic as above

2024-05-03 02:07 UTC, asivath commented on server/src/login-routes.ts
> +      await deleteVerification({ token });
yes technically possible I could add a unique constraint to the table which would throw a generic error and make the user submit again. should I do that or something else?

2024-05-03 02:20 UTC, asivath commented on server/src/login-routes.ts
> +        "Welcome back to TSC Online! Your email is already verified. If you did not request this email, please ignore it.";
this is again about security. an attacker could use this route to figure out emails. though this is less prevalent now since we removed the account verify link, so the only way a user should be able to access this route is when their email is not verified.  if they access this by going back and resending then I send an email to them so they are not confused.

2024-05-03 02:27 UTC, asivath commented on server/src/login-routes.ts
> +    const uuid = randomUUID();
idk what you mean by key

2024-05-03 18:31 UTC, paologum commented on app/src/AccountVerify.tsx
> +          setMessage("Your account has been verified. Thank you! Redirecting...");
yeah that looks better

2024-05-03 18:31 UTC, paologum commented on app/src/AccountVerify.tsx
> +  }, [token]);
ok sounds good

2024-05-03 18:34 UTC, paologum commented on app/src/AccountRecovery.tsx
> +        actions.pushSnackbar("If your account is verified, you will have received an email.", "success");
yeah that sounds good

2024-05-03 18:36 UTC, paologum commented on server/src/login-routes.ts
> +    }
ah ok i see i see

2024-05-03 18:38 UTC, paologum commented on server/src/login-routes.ts
> +      await deleteVerification({ token });
maybe instead you could add the `userId` or the `expiresAt` to the query to make it for sure delete the right rows

2024-05-03 18:39 UTC, paologum commented on server/src/login-routes.ts
> +        "Welcome back to TSC Online! Your email is already verified. If you did not request this email, please ignore it.";
ok cool that sounds good

2024-05-03 18:40 UTC, paologum commented on server/src/login-routes.ts
> +    const uuid = randomUUID();
if you add the constraint to the db schema it should throw an error and force a resubmit right

2024-05-04 00:07 UTC, asivath commented on server/src/login-routes.ts
> +    const uuid = randomUUID();
yes

2024-05-04 00:10 UTC, asivath commented on server/src/login-routes.ts
> +      await deleteVerification({ token });
i identify who the user is by their token so if there was a repeat it would be hard to tell who the user was and therefore their userid/expiresAt

2024-05-04 00:11 UTC, asivath commented on server/src/login-routes.ts
> +      await deleteVerification({ token });
i can add a loop that checks if the token is in the db

2024-05-04 05:46 UTC, paologum commented on server/src/login-routes.ts
> +      await deleteVerification({ token });
when you generate a token, what if you made the token partially the generated token and the user id hashed? then wouldn't it be guranteed unique without having to loop?

2024-05-04 21:14 UTC, paologum requested changes
this looks good, but i'm not sure if you changed the Thank you! redirecting... part

it should have a new line after Thank you! so redirecting should have it's own line.

after you post a photo of that i'll approve

2024-05-04 21:14 UTC, paologum commented on server/src/database.ts
> -  ): QueryBuilder;
is there a reason you moved away from this

2024-05-04 21:59 UTC, asivath commented
![image](https://github.com/earthhistoryviz/tsconline/assets/94872897/6a429eea-e5e9-425c-849f-5a95cbc23760)

2024-05-04 22:00 UTC, asivath commented on server/src/database.ts
> -  ): QueryBuilder;
yeah it was causing issues where queries would return more than just what it was supposed to return and I couldn't figure out the reason so I just got rid of it

2024-05-04 22:04 UTC, paologum approved these changes

2024-05-04 22:13 UTC, merged