Tsc 302 allow users to change their email
earthhistoryviz/tsconline pull request #98
Opened 2024-05-09 19:35 UTC by asivath

https://www.dropbox.com/scl/fi/d1byydyzewqqyw0rzh25e/reset_email_example.mp4?rlkey=hnv8q3zwcnweqgeyfd9hip9gz&st=gumed8h0&dl=0
This video shows the flow for a user who didn't request their email to be changed. If they meant to then it will follow the normal email verification flow which I didn't show. 

I needed to modify the database to implement this feature so I introduced migrations, which I explain with comments in database.ts and migrations.ts.

2024-05-10 00:21 UTC, paologum requested changes

2024-05-10 00:21 UTC, paologum commented on server/db/migrate.ts
so fun so fun, i'm gonna probably migrate `file metadata` to be in the database because it's gonna have migrating issues as well. that should be fine right

2024-05-10 00:21 UTC, paologum commented on server/db/migrations/2024.05.08-17.59.45-adjust-columns-in-verification-table.ts
> +                            SELECT userId, token, expiresAt, verifyOrReset FROM verification`.execute(db);
is this not a Kysely command we can execute

2024-05-10 00:21 UTC, paologum commented on server/src/database.ts
> +*/
so this schema will never change ever

2024-05-10 00:21 UTC, paologum commented on server/src/database.ts
> +
should do this in a promise

2024-05-10 00:21 UTC, paologum commented on server/src/login-routes.ts
> +    };
just a comment, but your next task should probably be making a general email sender that is just a styled email given some params since we have so many emails at this point

2024-05-10 00:21 UTC, paologum commented on server/src/login-routes.ts
> +      return;
is there ever a worry that so many people have expired tokens and never reaccess it over long periods of time and there's just a buildup of expired tokens in the db. should we clean that up in that scenario?

2024-05-10 00:21 UTC, paologum commented on server/src/login-routes.ts
> +  if (!token || !email) {
check regex for email

2024-05-10 00:21 UTC, paologum commented on server/src/login-routes.ts
> +    }
let's say that a google user changes their email to a non-google account. then how do they sign in with no password?

additionally if they switch over to another google account that should be fine then right

2024-05-10 00:21 UTC, paologum commented on server/src/types.ts
> +  invalidateSession: number;
is there no way to make these booleans for better readability?

2024-05-10 00:33 UTC, asivath commented on app/src/ResetEmail.tsx
> +  const handlelSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
crazy i should probably look into a spell checker

2024-05-10 00:35 UTC, asivath commented on app/src/AccountRecovery.tsx
this where users go to if they click the link for invalidating their password

2024-05-10 00:39 UTC, asivath commented on app/src/ResetEmail.tsx
> +            errorCode = ErrorCodes.EMAIL_ALREADY_EXISTS;
yea it used to be a thing but I removed it, forgot to remove this

2024-05-10 00:41 UTC, asivath commented on server/db/migrate.ts
yes should be fine

2024-05-10 00:49 UTC, asivath commented on server/db/migrations/2024.05.08-17.59.45-adjust-columns-in-verification-table.ts
> +                            SELECT userId, token, expiresAt, verifyOrReset FROM verification`.execute(db);
yeah i found a way to do it

2024-05-10 00:58 UTC, asivath commented on server/src/database.ts
> +*/
yeah the initial table creation commands and any migrations pushed to main should never be changed. that's why I thought we should document the actual schema there after all migrations

2024-05-10 01:31 UTC, asivath commented on server/src/login-routes.ts
> +      return;
yeah I can clean them up

2024-05-10 01:34 UTC, asivath commented on server/src/login-routes.ts
> +  if (!token || !email) {
technically this email is not entered by the user it comes from the db which has already gone through the check but i'll add it anyway since a user could alter the email in the address or copy it wrong

2024-05-10 02:13 UTC, asivath commented on server/src/login-routes.ts
> +    }
we already don't allow google accounts and user/password accounts to mix so should I allow google users to do that? if we want to I could get rid of the password in the form (which is kind of redundant since they have to be signed in to access it) and assign google users a random password they can use to sign in and they can also change their password

2024-05-10 02:33 UTC, paologum commented on app/src/ResetPassword.tsx
> +            : "Password Recovery"}
nvm i lied loader goes above

2024-05-10 02:50 UTC, asivath commented on server/src/types.ts
> +  invalidateSession: number;
i've looked into ways other people have done [it](https://github.com/kysely-org/kysely/issues/123) but since it wasn't super easy I didn't bother. lmk if you think I should use one of those methods

2024-05-10 03:15 UTC, asivath commented on app/src/ResetPassword.tsx
> +            : "Password Recovery"}
the stall happens from initialize, when I comment out all its actions it loads fine

2024-05-10 21:47 UTC, asivath commented on server/src/login-routes.ts
> +    }
i've allowed google users to swtich to user/pass but I have no way of knowing if a users new email is a google account so I'm not sure how to handle that. this could be solved by allowing user/pass and google accounts to mix, so wdyt?

2024-05-11 19:03 UTC, paologum commented on server/src/login-routes.ts
> +    }
i think we just don't allow them to go to google accounts after switching to user/pass so what you have sounds good

2024-05-11 19:08 UTC, paologum commented on server/src/types.ts
> +  invalidateSession: number;
ok yeah we can just leave it as it is. also i watched a tiktok that said that we could store enums (like the`reason`) into binary where each bit represents a reason. ie `00` is `password`, `10` is `invalidate, and `01` is `verify`. then we have like a dict mapping for the binary numbers. this makes queries run faster since they aren't checking strings if you query with binary operations like & or |. 

i think this is interesting although something that probably doesn't matter all to much for us since our scale is not on any crazy level and the amount of enums we have for `reason` are so little. thought it was fun though

2024-05-11 22:02 UTC, asivath commented on server/src/login-routes.ts
> +      await deleteVerification({ userId: userId, reason: "verify" });
true there is no real reason I can think of to keep them

2024-05-11 22:05 UTC, asivath commented on server/src/login-routes.ts
> +      await deleteVerification({ userId: userId, reason: "verify" });
actually except for invalidate tokens since if a attacker send multiple reset emails they could delete the actual users invalidate token

2024-05-11 22:51 UTC, paologum approved these changes

2024-05-12 02:21 UTC, merged